### ISSUE TITLE
能不能把系统模块进行拆分『结论：春节肝了 5 天，已经发布』

### ISSUE THREAD

**Issue by qq742464260** [YunaiV/ruoyi-vue-pro#10]
能不能把系统模块进行拆分，感觉全部弄在一起不是非常好

**Comment by YunaiV** [comment]
> 能不能把系统模块进行拆分，感觉全部弄在一起不是非常好

这个问题，其实我也纠结过。

对于一个单体应用，按照系统模块拆成 maven 工程，对依赖的处理其实很麻烦。

**Comment by qq742464260** [comment]
可拆可合 742464260 ***@***.*** 签名由 网易邮箱大师 定制 在2021年04月02日 19:38，芋道源码 写道： 能不能把系统模块进行拆分，感觉全部弄在一起不是非常好 这个问题，其实我也纠结过。 对于一个单体应用，按照系统模块拆成 maven 工程，对依赖的处理其实很麻烦。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by YunaiV** [comment]
> 可拆可合 742464260 ***@***.*** 签名由 网易邮箱大师 定制 在2021年04月02日 19:38，芋道源码 写道： 能不能把系统模块进行拆分，感觉全部弄在一起不是非常好 这个问题，其实我也纠结过。 对于一个单体应用，按照系统模块拆成 maven 工程，对依赖的处理其实很麻烦。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我琢磨下，怎么做可能合适一点，嘿嘿。

从微服务架构上来说，一般是 nginx =》bff =》rpc service 这样的。
从单体架构上来说，一般是 nginx =》bff 这样的。
如果拆分成多个子 maven module 来说，和微服务架构本质的区别，在于是 local invoke 和 remote invoke 的差别。

如果是基于这个思路，单纯拆出 maven module ，并且这个 module 带 Controller 又不是特别合适。原因是，多个 maven module 是有一些调用关系。

有什么好的建议哇？

**Comment by lanemy** [comment]
艿艿, 有没有可能改造成DDD实践的项目?
