### ISSUE TITLE
第一步将项目进行初始化的打包ok，第二步，执行 YudaoServerApplication 类，进行启动就报错了

### ISSUE THREAD

**Issue by zhf1234** [YunaiV/ruoyi-vue-pro#105]
cn.iocoder.boot:yudao-module-member:pom:${revision} was not found in https://maven.aliyun.com/repository/public during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of aliyunmaven has elapsed or updates are forced

**Comment by YunaiV** [comment]
认真阅读 https://doc.iocoder.cn/quick-start/ 文档
