### ISSUE TITLE
国产化改造-数据库-兼容达梦数，系统-中标麒麟

### ISSUE THREAD

**Issue by zw22weiqin** [YunaiV/ruoyi-vue-pro#106]
大佬，国产化能做下兼容吗
我使用的是activity7的，切换了默认了flowable
1.我参考这个进行了改造（添加dm的适配）
flowable:https://www.jianshu.com/p/24142518acf7
activity:https://blog.csdn.net/CHINESEZZZ/article/details/113738582

2.mysql迁移到达梦数据库，乱码问题
参考： https://blog.csdn.net/liaoyue11/article/details/119751011
字段长度设置3倍后还是出现错误，简单执行以下语句后再导出错误执行的表再执行
ALTER TABLE SYSDBA.system_menu MODIFY NAME varchar(100);
ALTER TABLE SYSDBA.system_notice MODIFY TITLE varchar(100);
ALTER TABLE SYSDBA.system_operate_log MODIFY NAME varchar(150);
ALTER TABLE SYSDBA.system_sms_channel MODIFY SIGNATURE varchar(100);
ALTER TABLE SYSDBA.system_social_user MODIFY NICKNAME varchar(100);
 
CREATE TABLE "SYSDBA"."ACT_RU_EVENT_SUBSCR"
(
 "ID_" VARCHAR(64) NOT NULL,
 "REV_" INT NULL,
 "EVENT_TYPE_" VARCHAR(255) NOT NULL,
 "EVENT_NAME_" VARCHAR(255) NULL,
 "EXECUTION_ID_" VARCHAR(64) NULL,
 "PROC_INST_ID_" VARCHAR(64) NULL,
 "ACTIVITY_ID_" VARCHAR(64) NULL,
 "CONFIGURATION_" VARCHAR(255) NULL,
 "CREATED_" TIMESTAMP(0) DEFAULT NULL,
 "PROC_DEF_ID_" VARCHAR(64) NULL,
 "SUB_SCOPE_ID_" VARCHAR(64) NULL,
 "SCOPE_ID_" VARCHAR(64) NULL,
 "SCOPE_DEFINITION_ID_" VARCHAR(64) NULL,
 "SCOPE_TYPE_" VARCHAR(64) NULL,
 "TENANT_ID_" VARCHAR(255) DEFAULT '' NULL
)
;
CREATE TABLE "SYSDBA"."ACT_HI_TSK_LOG"
(
 "ID_" BIGINT IDENTITY(1,1) NOT NULL,
 "TYPE_" VARCHAR(64) NULL,
 "TASK_ID_" VARCHAR(64) NOT NULL,
 "TIME_STAMP_" TIMESTAMP(0) DEFAULT NULL,
 "USER_ID_" VARCHAR(255) NULL,
 "DATA_" VARCHAR(4000) NULL,
 "EXECUTION_ID_" VARCHAR(64) NULL,
 "PROC_INST_ID_" VARCHAR(64) NULL,
 "PROC_DEF_ID_" VARCHAR(64) NULL,
 "SCOPE_ID_" VARCHAR(255) NULL,
 "SCOPE_DEFINITION_ID_" VARCHAR(255) NULL,
 "SUB_SCOPE_ID_" VARCHAR(255) NULL,
 "SCOPE_TYPE_" VARCHAR(255) NULL,
 "TENANT_ID_" VARCHAR(255) DEFAULT '' NULL
);

CREATE TABLE "SYSDBA"."ACT_EVT_LOG"
(
 "LOG_NR_" BIGINT IDENTITY(1,1) NOT NULL,
 "TYPE_" VARCHAR(64) NULL,
 "PROC_DEF_ID_" VARCHAR(64) NULL,
 "PROC_INST_ID_" VARCHAR(64) NULL,
 "EXECUTION_ID_" VARCHAR(64) NULL,
 "TASK_ID_" VARCHAR(64) NULL,
 "TIME_STAMP_" TIMESTAMP(0) DEFAULT   NULL,
 "USER_ID_" VARCHAR(255) NULL,
 "DATA_" BLOB NULL,
 "LOCK_OWNER_" VARCHAR(255) NULL,
 "LOCK_TIME_" TIMESTAMP(0) NULL,
 "IS_PROCESSED_" TINYINT DEFAULT 0
 NULL
)

3.配置数据源后，启动有些报错的
关键字屏蔽的可以参考：
https://blog.51cto.com/u_15127535/4081733
关键字：system_tenant.domain，infra_config.group  这两个关键字设置屏蔽了还是不生效，我直接改字段名称了
符号：`  去除

4.自动生成代码，参考
读取数据库表信息做成适配的？
```
<if test="params.driverClassName != null and params.driverClassName == 'com.mysql.cj.jdbc.Driver'">
			SELECT TABLE_NAME, ENGINE, TABLE_COMMENT, CREATE_TIME FROM INFORMATION_SCHEMA.TABLES
			WHERE TABLE_SCHEMA = (select database())
			<if test="params.tableName != null and params.tableName.trim() != ''">
				AND TABLE_NAME LIKE '%${params.tableName}%'
			</if>
			ORDER BY CREATE_TIME DESC
		</if>
		<if test="params.driverClassName != null and params.driverClassName == 'oracle.jdbc.driver.OracleDriver'">
			SELECT TABLE_NAME, COMMENTS TABLE_COMMENT FROM
				(SELECT ROWNUM AS RN,USER_TAB_COMMENTS.TABLE_NAME TABLE_NAME,USER_TAB_COMMENTS.COMMENTS COMMENTS,USER_TABLES.TABLESPACE_NAME
				FROM USER_TAB_COMMENTS
				LEFT JOIN USER_TABLES
				ON USER_TABLES.TABLE_NAME = USER_TAB_COMMENTS.TABLE_NAME
				WHERE 1 = 1
				<if test="params.tableName != null and params.tableName.trim() != ''">
					AND USER_TABLES.TABLE_NAME LIKE CONCAT(CONCAT('%', #{params.tableName}), '%')
				</if>
				)
		</if>
		<if test="params.driverClassName != null and params.driverClassName == 'dm.jdbc.driver.DmDriver'">

			SELECT c.TABLE_NAME,c.comments TABLE_COMMENT,
			o.created CREATE_TIME,o.OWNER ENGINE   FROM user_tab_comments c
			LEFT JOIN ALL_OBJECTS o on c.TABLE_NAME=o.OBJECT_NAME
			where  table_name NOT LIKE 'QRTZ_%'
			AND table_name NOT LIKE 'GEN_%'
			AND table_name NOT LIKE '#%'
			and o.OBJECT_TYPE='TABLE' AND o.OWNER=(select username from user_users)
			<if test="params.tableName != null and params.tableName.trim() != ''">
				AND TABLE_NAME LIKE '%${params.tableName}%'
			</if>
			ORDER BY CREATE_TIME DESC
		</if>
		```
目前还在改造中。。。

**Comment by YunaiV** [comment]
可以了么？

**Comment by YunaiV** [comment]
加我微信 wangwenbin-server 么？

**Comment by sunyx9015** [comment]
大佬，改造完了吗，我也有这需求，给参考一下

**Comment by YunaiV** [comment]
现在程序是已经都支持了，数据库脚本需要自己解决下。

如果感兴趣，可以 pr 一下。
