### ISSUE TITLE
账号未登录

### ISSUE THREAD

**Issue by Kevin-Ben** [YunaiV/ruoyi-vue-pro#110]
URL: /dev-api/admin-api/system/social-auth-redirect?type=30

怎么在未登录的情况下，放行

**Comment by YunaiV** [comment]
可以看看 https://doc.iocoder.cn/resource-permission/#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%9D%83%E9%99%90%E9%85%8D%E7%BD%AE 文档哈。
