### ISSUE TITLE
有交流群嘛

### ISSUE THREAD

**Issue by wwt164888** [YunaiV/ruoyi-vue-pro#112]

**Comment by YunaiV** [comment]
https://doc.iocoder.cn/qun/

**Comment by chinghoi** [comment]
被加好友过于频繁了

**Comment by happy-leraner** [comment]
我也是，加不了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月24日 20:13 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | Re: [YunaiV/ruoyi-vue-pro] 有交流群嘛 (Issue #112) |

被加好友过于频繁了

**Comment by huanlirui** [comment]
要收钱，199入星球？

**Comment by happy-leraner** [comment]
是啊，



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年04月03日 13:12 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [YunaiV/ruoyi-vue-pro] 有交流群嘛 (Issue #112) |

要收钱，199入星球？

**Comment by happy-leraner** [comment]
被坑了，问个问题都没地方



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年04月03日 13:12 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [YunaiV/ruoyi-vue-pro] 有交流群嘛 (Issue #112) |

要收钱，199入星球？

**Comment by MoShengA** [comment]
为什么项目数据库表不全啊，找死人

**Comment by YunaiV** [comment]
微信添加好友有频率限制，所以碰到频繁，可以等 5 分钟再试试。
