### ISSUE TITLE
事务警告

### ISSUE THREAD

**Issue by mixcg** [YunaiV/ruoyi-vue-pro#116]
问题：日志警告 Sqlsession was not registered for synchronization because DataSource is not transactional 
出现时机：部分transactional注解的事务性方法
环境: mysql单数据源 仅配置了动态数据源的master节点

这个是因为啥造成的？会影响事务吗？该怎么解决？

**Comment by YunaiV** [comment]
可以提供下更详细的日志说明么？

**Comment by mixcg** [comment]
又研究了下 如果调用mybatis plus的batch相关方法就会出现这个警告

**Comment by mixcg** [comment]
> 可以提供下更详细的日志说明么？


又研究了下 如果调用mybatis plus的batch相关方法就会出现这个警告
