### ISSUE TITLE
返回前端时日期格式化不生效

### ISSUE THREAD

**Issue by wuwen635028360** [YunaiV/ruoyi-vue-pro#117]
在DO中给某个属性增加日期格式化注解后无效。
`@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
private Date planStartDate;`
返回结果还是时间戳不生效
![uTools_1648361071763](https://user-images.githubusercontent.com/34561441/160268950-b2e33c29-31a4-49b9-9261-f52c746cbb17.png)

**Comment by zengpinlin** [comment]
这个 web 工程有一个YudaoJacksonAutoConfiguration自动配置类，去掉LocalDateTime序列化看看

**Comment by wuwen635028360** [comment]
> 这个 web 工程有一个YudaoJacksonAutoConfiguration自动配置类，去掉LocalDateTime序列化看看

注释了好像也没啥用呢

**Comment by wuwen635028360** [comment]
不应该在DO中改注解，应该是在对应的RespVO中添上@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")注解
