### ISSUE TITLE
运行一段时间会莫名其妙CPU飙升和狂报错记录

### ISSUE THREAD

**Issue by jjzhoujun** [YunaiV/ruoyi-vue-pro#119]
使用local模式进行package打包成  jar，放到国产化服务器（ARM64，配置32C64G）上用如下命令运行
nohup java -jar yudao-server.jar >> out.log 2>&1&
起初一切正常，CPU平稳运行，top看占用的CPU保持在2%左右平稳运行，但是过了几分钟，系统的定时任务（自定义的那部分定时任务local模式下默认我也没开），日志打印“加载全量租户、sms之类的打印”，然后CPU一直就占用26%左右。。。
    但是看日志暂时也还没报错，没管，持续开了一天，发现日志文件突然编程了 34G（如下图），tail -f 看了下狂爆 sms 的错误。

![sms报错信息](https://user-images.githubusercontent.com/5793642/160850467-80b7a024-7849-40dc-a48c-094a327769e9.jpg)

![cpu占用飙升](https://user-images.githubusercontent.com/5793642/160850307-3a43b0d4-b689-497c-9c64-97e027d6549e.png)

![日志文件out爆满](https://user-images.githubusercontent.com/5793642/160849896-60540cd6-57ae-4e1e-bb0e-b0e49a7f9f76.png)

**Comment by jjzhoujun** [comment]
> redis 版本是？

Redis server v=6.2.6 sha=00000000:0 malloc=libc bits=64 build=a913c997b68c854e
使用的ruoyi-vue-pro的基线代码版本是release的 v1.6.1 ，自己也只是在上面加了一个页面的CRUD功能，以及删掉了一些原有数据库里的测试账户和测试租户，只留了系统租户。

**Comment by crimson-gao** [comment]
遇到相同 bug 了，我可以手动把这个异步任务去掉吗

**Comment by crimson-gao** [comment]
而且此时 redis 中没有 key 了

**Comment by crimson-gao** [comment]
刚初始化时是存在两个 key 的 
<img width="266" alt="image" src="https://user-images.githubusercontent.com/39024757/161013990-de74d295-e650-42c4-93cf-fbc06213a2d3.png">

出错可能是因为 key 被清空或者过时了？

**Comment by crimson-gao** [comment]
有可能和 redis 版本有关系，我本地跑的 6.2 版本没问题。远程机器上跑的 7.0 出问题了。
不懂 redis，是不是这部分代码是不是，定时或者在 sms channel 变化时（做了update、delete、create），触发 initSmsClient 函数，更新 sms client。回头看看 redis 消息是怎么回事


ps：这 initSmsClient 中间更新了一个成员变量 maxUpdateTime，会不会有线程安全问题。但是大概率和这个问题关联不大。

**Comment by YunaiV** [comment]
看了下，可能是 redisson 的 bug，最近会升级下这个库~

**Comment by jjzhoujun** [comment]
昨天我同事发现系统的 crontab -l 打印出来的是乱码，里面写着一些  redis 和 yudao-server 的一些内容，并且把他之前已经配置好的内容给冲掉了。  我后来就手动把  crontab 内容都清空了。  
但是由于业务需要，我目前代码昨天去掉了“支付模块”“工作流模块”，以及将系统的 limits.conf open files调大到65536，目前编译运行 jar 包将近一天，定时任务、CPU占用、日志记录等都一切正常，暂未发现异常。

**Comment by YunaiV** [comment]
> 昨天我同事发现系统的 crontab -l 打印出来的是乱码，里面写着一些 redis 和 yudao-server 的一些内容，并且把他之前已经配置好的内容给冲掉了。 我后来就手动把 crontab 内容都清空了。 但是由于业务需要，我目前代码昨天去掉了“支付模块”“工作流模块”，以及将系统的 limits.conf open files调大到65536，目前编译运行 jar 包将近一天，定时任务、CPU占用、日志记录等都一切正常，暂未发现异常。

嗯呐，不需要的模块，最好是下掉哈。

感谢你的留言，我会写到上线须知

**Comment by jjzhoujun** [comment]
> > 昨天我同事发现系统的 crontab -l 打印出来的是乱码，里面写着一些 redis 和 yudao-server 的一些内容，并且把他之前已经配置好的内容给冲掉了。 我后来就手动把 crontab 内容都清空了。 但是由于业务需要，我目前代码昨天去掉了“支付模块”“工作流模块”，以及将系统的 limits.conf open files调大到65536，目前编译运行 jar 包将近一天，定时任务、CPU占用、日志记录等都一切正常，暂未发现异常。
> 
> 嗯呐，不需要的模块，最好是下掉哈。
> 
> 感谢你的留言，我会写到上线须知

![image](https://user-images.githubusercontent.com/5793642/162577714-6c088bbe-3b2e-4090-931d-c6e38262567d.png)
去掉不需要的模块，不知道为啥平稳运行了几天，今天又突然一直报错，而且把crontab里原来的别人的任务给冲掉了。。。并且日志把存储都占满了。。  还是请帮忙看看

**Comment by jjzhoujun** [comment]
启动的命令是用   nohup java -jar yudao-server.jar > out.log 2>&1 &

**Comment by YunaiV** [comment]
> > > 昨天我同事发现系统的 crontab -l 打印出来的是乱码，里面写着一些 redis 和 yudao-server 的一些内容，并且把他之前已经配置好的内容给冲掉了。 我后来就手动把 crontab 内容都清空了。 但是由于业务需要，我目前代码昨天去掉了“支付模块”“工作流模块”，以及将系统的 limits.conf open files调大到65536，目前编译运行 jar 包将近一天，定时任务、CPU占用、日志记录等都一切正常，暂未发现异常。
> > 
> > 
> > 嗯呐，不需要的模块，最好是下掉哈。
> > 感谢你的留言，我会写到上线须知
> 
> ![image](https://user-images.githubusercontent.com/5793642/162577972-eac8ab1f-cf65-4364-80fb-fb1f4f563777.png)
> 
> 去掉不需要的模块，不知道为啥平稳运行了几天，今天又突然一直报错，而且把crontab里原来的别人的任务给冲掉了。。。并且日志把存储都占满了。。 还是请帮忙看看

最好说明下是啥日志 = = 我演示环境跑了 2 个月，暂时没碰到问题。。

**Comment by jjzhoujun** [comment]
用tail -n 100 导出了最后100条的错误日志，发现应该是一直报日志里的错误，导致空间被占满了整个磁盘，见下附件。

**Comment by jjzhoujun** [comment]
我发现可能的一种复现方法了，在程序运行时候， 把 redis 里的 system.mail.send  key 给手工或者被哪些程序删掉后，就会一直报这个错误了。。。
当然在我服务器上自己运行时候，应该是没人手动删除这些key，可能出现哪类异常导致对应的redis key不见了？ 然后程序一直报错？

**Comment by directionyu** [comment]
遇到同样的问题+1  NOGROUP No such key 'system.mail.send' or consumer group

**Comment by chuangqi** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by hxgqh** [comment]
这个问题还存在，怎么解决？这个issue怎么关闭了

**Comment by xiangxiaobo392** [comment]
这个问题很严重,日志都把磁盘占满了,请问有解决方案没
