### ISSUE TITLE
UserTypeEnum.MEMBER 这个是不是应该是 UserTypeEnum.ADMIN

### ISSUE THREAD

**Issue by guoxiaod** [YunaiV/ruoyi-vue-pro#122]
https://github.com/YunaiV/ruoyi-vue-pro/blob/d60be0bb53431856ed2574379f3cf1162d2bf4a5/yudao-module-system/yudao-module-system-impl/src/main/java/cn/iocoder/yudao/module/system/service/auth/AdminAuthServiceImpl.java#L197

这个
UserTypeEnum.MEMBER
是不是应该是
UserTypeEnum.ADMIN

**Comment by YunaiV** [comment]
是的，pr 修改下哇？

**Comment by YunaiV** [comment]
已修复。
