### ISSUE TITLE
参数校验

### ISSUE THREAD

**Issue by crazyStar00** [YunaiV/ruoyi-vue-pro#124]
<img width="819" alt="image" src="https://user-images.githubusercontent.com/18380553/161975707-7001b717-72af-48fd-affa-59baa8faddf9.png">

既然，不管怎样service都要做校验，那是不是就应该把校验放在service，不然双重校验了。

**Comment by YunaiV** [comment]
道理是这个道理哈，Controller 自带了 binding 体系，也会触发校验
