### ISSUE TITLE
缓存类型可不可以做成可配置的

### ISSUE THREAD

**Issue by qq742464260** [YunaiV/ruoyi-vue-pro#13]
有些环境其实并没有或者不允许安装redis，可不可以把缓存做成可配置的，有条件的可选redis，没条件本地缓存可选guava/caffine

**Comment by YunaiV** [comment]
redis 在项目中，会有三个定位
1. 在线缓存，例如说用户的在线会话、等等
2. 订阅发布，例如说刷新本地缓存
3. MQ 消息队列，例如说异步发送消息

所以可能去掉 redis 会有一定难度~~~

**Comment by qq742464260** [comment]
> 
> 
> redis 在项目中，会有三个定位
> 
>     1. 在线缓存，例如说用户的在线会话、等等
> 
>     2. 订阅发布，例如说刷新本地缓存
> 
>     3. MQ 消息队列，例如说异步发送消息
> 
> 
> 所以可能去掉 redis 会有一定难度~~~

好的
