### ISSUE TITLE
使用内嵌模式，退出登录后没有回到登录页面

### ISSUE THREAD

**Issue by cayzlh** [YunaiV/ruoyi-vue-pro#132]
使用内嵌模式启动项目，在管理后台点退出之后，页面没有跳转到登录页面，而是提示用户未登录

<img width="546" alt="image" src="https://user-images.githubusercontent.com/12791269/164650437-40149403-71be-447a-b4af-58387356eef8.png">

**Comment by YunaiV** [comment]
试试最新的代码，已经 fix 了哈
