### ISSUE TITLE
代码生成器biz-resouces多了级路径

### ISSUE THREAD

**Issue by KLSOBIG** [YunaiV/ruoyi-vue-pro#136]
![image](https://user-images.githubusercontent.com/35753627/165490236-64159be0-542d-4dea-8f5a-6a0f9682b2e7.png)
![image](https://user-images.githubusercontent.com/35753627/165491167-e4cc44fc-06a3-4794-bfe6-10f9474f5407.png)

**Comment by YunaiV** [comment]
可以 pr 修复下。

**Comment by YunaiV** [comment]
已修复。
