### ISSUE TITLE
readme中，ruoyi-vue-cloud gitee 和github对应地址的内容不一样

### ISSUE THREAD

**Issue by devbian** [YunaiV/ruoyi-vue-pro#138]
<img width="599" alt="image" src="https://user-images.githubusercontent.com/620615/165695533-62e949e3-d021-4328-9abf-2da5fea93082.png">
gitee对应的是ruoyi-vue-cloud
但是，github直接是对应的onemall，github上貌似没有ruoyi-vue-cloud

**Comment by YunaiV** [comment]
已经修复，谢谢。
