### ISSUE TITLE
自动生成代码功能报错

### ISSUE THREAD

**Issue by leosanqing** [YunaiV/ruoyi-vue-pro#141]
升级到最新代码(5.5拉的最新代码)，之前是正常的(上一个版本正常)，看代码这个是5.1号提交的
如果表没有注释会报错

<img width="806" alt="image" src="https://user-images.githubusercontent.com/20400582/166938638-6d8a972a-c396-4ba1-85a0-51e3bd038645.png">
<img width="534" alt="image" src="https://user-images.githubusercontent.com/20400582/166939311-19ae9ad1-2f8e-41f5-bea0-7dfeee07887c.png">

<img width="886" alt="image" src="https://user-images.githubusercontent.com/20400582/166938738-b3cec9ed-d30e-4367-ab65-4aaafac43ba5.png">

**Comment by leosanqing** [comment]
好像是导入的时候，只要有一个字段没有注释就会报错，这个是否不太合理

**Comment by YunaiV** [comment]
合理的。不然生成的代码，注释是不够完整的。
例如说数据库实体，swagger 的接口文档，validator 的提示。
