### ISSUE TITLE
sql server下在线用户模块无法正常访问

### ISSUE THREAD

**Issue by yqjack** [YunaiV/ruoyi-vue-pro#145]
org.springframework.jdbc.UncategorizedSQLException: Error attempting to get column 'token' from result set.  Cause: com.microsoft.sqlserver.jdbc.SQLServerException: 将 nvarchar 值转换为 JDBC 数据类型 BIGINT 时发生错误。
; uncategorized SQLException; SQL state [null]; error code [0]; 将 nvarchar 值转换为 JDBC 数据类型 BIGINT 时发生错误。; nested exception is com.microsoft.sqlserver.jdbc.SQLServerException: 将 nvarchar 值转换为 JDBC 数据类型 BIGINT 时发生错误。

**Comment by YunaiV** [comment]
导入最新的表，已经修复哈。
