### ISSUE TITLE
DataPermission注解没有生效

### ISSUE THREAD

**Issue by orangefororange** [YunaiV/ruoyi-vue-pro#148]
新增加了一个模块，数据查询不需要数据权限，在方法或类上加上@DataPermission(enable=false) 没有生效。查询语句还是加上了限定条件,

>   `@GetMapping("/page")`
    `@ApiOperation("获得服务范围分类，优势所在介绍。分页")
    @PreAuthorize("@ss.hasPermission('official:server-range:query')")
    @DataPermission(enable = false)
    public CommonResult<PageResult<ServerRangeRespVO>> getServerRangePage(@Valid ServerRangePageReqVO pageVO) {
        PageResult<ServerRangeDO> pageResult = serverRangeService.getServerRangePage(pageVO);
        return success(ServerRangeConvert.INSTANCE.convertPage(pageResult));
    }`
> `SQL: SELECT COUNT(*) AS total FROM official_server_range WHERE deleted = 0 AND tenant_id = 1`

**Comment by YunaiV** [comment]
我看是没有加上的，可以在看看文档哈。

https://doc.iocoder.cn/data-permission/
