### ISSUE TITLE
代码生成没有处理BigDecimal类型

### ISSUE THREAD

**Issue by cayzlh** [YunaiV/ruoyi-vue-pro#150]
## 场景

数据库字段类型为：decimal
生成Java字段类型为：BigDecimal

## 问题

生成的Java类没有引入BigDecimal包

<img width="234" alt="image" src="https://user-images.githubusercontent.com/12791269/169475162-eb5140b2-7a36-4df8-8754-52ef46951e3f.png">

## 版本
** 1.6.1**

**Comment by YunaiV** [comment]
已修复。
