### ISSUE TITLE
应用打包结果和文档中不一致，打包错误

### ISSUE THREAD

**Issue by lixunhui** [YunaiV/ruoyi-vue-pro#154]
### 基本信息

- ruoyi-vue-pro 版本：最新版
- 操作系统：Mac OS
- 数据库：mysql

### 复现步骤
<img width="543" alt="image" src="https://user-images.githubusercontent.com/4917509/170086382-6492c65e-f795-4b73-bb37-c463741154c0.png">

### 报错信息
预期结果为：yudao-server.jar
实际结果为：yudao-module-bpm-biz-activiti-1.6.2-snapshot.jar

**Comment by YunaiV** [comment]
这个是子模块的 jar 包噢，可以学习下 maven 的相关知识噢。
