### ISSUE TITLE
子菜单展示问题

### ISSUE THREAD

**Issue by jingjianhai** [YunaiV/ruoyi-vue-pro#157]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：
- 操作系统：
- 数据库：

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：xxxxxx

### 复现步骤

第一步，alwaysShow 设置还是显示唯一的子菜单  主菜单不显示  很鸡肋的配置

第二步，

第三步，

### 报错信息

带上必要的截图

**Comment by YunaiV** [comment]
具体怎么配置的？

**Comment by YunaiV** [comment]
由于没有进一步的回复，该 Issue 先暂时关闭。
后续有疑问，可以继续提问。
