### ISSUE TITLE
字典管理，字典数据的搜索栏的状态下拉框没有数据

### ISSUE THREAD

**Issue by alexchanchan** [YunaiV/ruoyi-vue-pro#162]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

字典管理 -> 字典数据
搜索栏的状态下拉框没有数据

- ruoyi-vue-pro 版本：master分支
- 操作系统：
- 数据库：

### 你猜测可能的原因

statusOptions 没有初始化赋值

### 复现步骤

直接打开即可，见截图

### 报错信息

带上必要的截图
![微信截图_20220618212014](https://user-images.githubusercontent.com/13378806/174439714-746ab071-db61-4efa-9d78-8803174d567b.png)
![微信截图_20220618212106](https://user-images.githubusercontent.com/13378806/174439721-e311207f-c8c3-403e-9635-6f894cc1a911.png)
![微信截图_20220618212126](https://user-images.githubusercontent.com/13378806/174439731-a8033b56-8b85-44fa-b0c7-5d3c4c8737a3.png)

**Comment by YunaiV** [comment]
可以 pr 一下哈。

**Comment by YunaiV** [comment]
已修复
