### ISSUE TITLE
DataIntegrityViolationException: null value in column "user_id" of relation "system_login_log" violates not-null constraint

### ISSUE THREAD

**Issue by aboutZZ** [YunaiV/ruoyi-vue-pro#163]
### 基本信息

- ruoyi-vue-pro 版本：1.6.2
- 操作系统：Win10
- 数据库：PostgreSQL

### 你猜测可能的原因
https://github.com/YunaiV/ruoyi-vue-pro/blob/309ba2d3f183168fb01b838545f539aff1892fbd/yudao-module-system/yudao-module-system-biz/src/main/java/cn/iocoder/yudao/module/system/service/auth/AdminAuthServiceImpl.java#L142
`system_login_log`表定义中`user_id`字段 `NOT NULL`，在代码中，`createLoginLog`插入了一条`user_id`为`null`的数据

### 复现步骤

登录时，输入错误的验证码后，点击登录按钮

### 报错信息
系统异常

**Comment by YunaiV** [comment]
已修复。
