### ISSUE TITLE
启动时间过长

### ISSUE THREAD

**Issue by aboutZZ** [YunaiV/ruoyi-vue-pro#164]
代码中大量用到了`@PostConstruct`进行各种缓存加载，导致启动时间过长。应当在使用到该数据时进行缓存，找不到缓存，先从数据库查询，然后放入缓存

**Comment by aboutZZ** [comment]
> 这个我觉得只有在开发时才是问题. 主要是项目没有集成spring boot devtools

我的项目没用到工作流及支付，去掉这些模块后，启动时间减少了10s

**Comment by YunaiV** [comment]
慢的原因，是工作流、MQ 的初始化带来的，和缓存关系不大哈。
你可以和 @aboutZZ 一样，去掉自己不要的模块
