### ISSUE TITLE
在数据库表新增字段后，代码生成器生成错误（只有刚添加的字段，原来的字段消失不见）

### ISSUE THREAD

**Issue by aboutZZ** [YunaiV/ruoyi-vue-pro#165]
在数据库表新增字段后，代码生成器生成错误（只有刚添加的字段，原来的字段消失不见）

### 基本信息

- ruoyi-vue-pro 版本：1.6.2
- 操作系统：Win10
- 数据库：PostgreSQL

### 复现步骤

1. 代码生成页面中，点击导入，选择一张表导入
2. 点击编辑配置字段，生成代码
3. 在数据库中，给这张表中新增一个字段，例如：`add_status`
4. 代码生成页面中，点击同步按钮
5. 此时生成的字段只有刚添加的那个字段`add_status`，其余字段没了。
![截图](https://s2.loli.net/2022/06/25/euCU5NMSIi2DpKA.png)
6. 再次点击同步按钮，这次原先的字段恢复了，但是没有新增的字段`add_status`。
7. 再次点击同步按钮，又变成步骤5的状态了
8. 再次点击同步按钮，又变成步骤6的状态了。。。循环。。。

**Comment by YunaiV** [comment]
已修复。
