### ISSUE TITLE
flowable生成xml的process id在前端会被重置，从而出现id重复的bug

### ISSUE THREAD

**Issue by wangjun-ql** [YunaiV/ruoyi-vue-pro#166]
### 基本信息

- ruoyi-vue-pro 版本：69a3a835a5a208450bcb172f6a530342aa5f7d7f
- 操作系统：win10
- 数据库：mysql5.7

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：在ProcessDesigner.vue文件中的createNewDiagram(xml)函数重置了xml
![image](https://user-images.githubusercontent.com/55046688/175903412-86b0f499-5783-4a34-a253-e384649e8333.png)

### 复现步骤

第一步，
新增一个流程模型，绘制一个泳道，泳道内简单的绘制一个开始和结束事件
第二步，
保存，并重新打开，只会看到那个泳道

### 报错信息
unparsable content <bpmn2:process> detected\n\tline: 5\n\tcolumn: 2\n\tnested error: duplicate ID <bcbcvb>', error: Error: duplicate ID <bcbcvb>
带上必要的截图
![image](https://user-images.githubusercontent.com/55046688/175904012-389b038e-af6f-45fa-8a27-4304cce1b7b1.png)
错误的图片
![image](https://user-images.githubusercontent.com/55046688/175904296-e22a72a0-e8d1-4f96-9193-7ab26f3a9795.png)
正确的图片
![image](https://user-images.githubusercontent.com/55046688/175904370-ccfceeba-4b75-44aa-9475-4e5f9e9f49f8.png)

**Comment by YunaiV** [comment]
pr 了最新的代码，在试试看哈。
