### ISSUE TITLE
接口幂等没有处理

### ISSUE THREAD

**Issue by anderstang** [YunaiV/ruoyi-vue-pro#168]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：1.6.2
- 操作系统：mac
- 数据库：mysql

### 你猜测可能的原因

没有处理接口幂等

### 复现步骤

第一步，创建租户，填写内容

第二步，快速多次点击确定按钮

### 报错信息

会创建多个相同的租户，登录时，输入租户名称是，报错，数据库中有多条数据

**Comment by YunaiV** [comment]
可以增加一个幂等注解；
