### ISSUE TITLE
Weak password vulnerability in the management system

### ISSUE THREAD

**Issue by docin123456** [YunaiV/ruoyi-vue-pro#170]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：RuoYi v3.8.3
- 操作系统：windows
- 数据库：mysql5.6

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：Weak password vulnerability in the management system

### 复现步骤

![image](https://user-images.githubusercontent.com/85209555/181746516-f6f0c728-1e53-4629-9d4c-387884a22961.png)

### 报错信息

带上必要的截图

**Comment by YunaiV** [comment]
不错的功能，可以 PR 支持哈。
