### ISSUE TITLE
文档和代码代码不一致

### ISSUE THREAD

**Issue by balajinima** [YunaiV/ruoyi-vue-pro#172]
在文档“项目结构” 章节中 说明 Mapper 接口要放在dal.mapper包下，但实际放在了mysql目录下
![image](https://user-images.githubusercontent.com/6326356/184322409-70f06fbd-2f15-44ba-a604-a5ae80d539d1.png)

![image](https://user-images.githubusercontent.com/6326356/184322300-a762e09b-e020-4f72-8e58-936f274722eb.png)

**Comment by YunaiV** [comment]
感谢，已修复。
