### ISSUE TITLE
Vue3前端模板校验错误提示问题

### ISSUE THREAD

**Issue by BlueMaplePlus** [YunaiV/ruoyi-vue-pro#173]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：
- 操作系统：Win10
- 数据库：MySQL

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：vue-element-plus-admin组件？

### 复现步骤

启动系统后进入租户套餐管理，点击添加-选择任意套餐都会出现“该项为必填项”的错误提示

### 报错信息

![image](https://user-images.githubusercontent.com/28829169/184869082-41fab253-6e1c-446d-ac04-dfd84f0afd64.png)

**Comment by YunaiV** [comment]
已解决。
