### ISSUE TITLE
自定义图标未在图标选择器中出现

### ISSUE THREAD

**Issue by aboutZZ** [YunaiV/ruoyi-vue-pro#175]
依据文档 [自定义图标](https://doc.iocoder.cn/vue2/icon/#_2-%E8%87%AA%E5%AE%9A%E4%B9%89%E5%9B%BE%E6%A0%87)，在`src/icons/svg/`中添加自定义图标`map.svg`
重启前端项目后，图标选择器中未找到自定义map图标

[![v2s2ZR.png](https://s1.ax1x.com/2022/08/26/v2s2ZR.png)](https://imgse.com/i/v2s2ZR)

**Comment by aboutZZ** [comment]
https://github.com/YunaiV/ruoyi-vue-pro/blob/185ea9e8614174bb395e6b8ab51e0eadaa42ab42/yudao-ui-admin/src/components/IconSelect/requireIcons.js#L2-L11)

查看源码发现引用的是`src/assets/icons/svg`下的图标，请删除`src/icons`下的文件夹，并更正文档

**Comment by YunaiV** [comment]
已修复，非常感谢！
