### ISSUE TITLE
Apollo配置中心-后台验证码开关设置多次设置失效

### ISSUE THREAD

**Issue by BlueMaplePlus** [YunaiV/ruoyi-vue-pro#177]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：1.6.4
- 操作系统：Win10
- 数据库：MySQL5.7

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：Apollo配置中心问题？

### 复现步骤

第一步，启动后端，默认yudao.captcha.enable为true

第二步，进入 [基础设施 -> 配置管理] 菜单，将配置项 yudao.captcha.enable 修改为 false，前端登录无需验证码。

第三步，如果再次将yudao.captcha.enable 修改为 true，前端无法显示验证码，需要重启后端才行！

### 报错信息

多次修改 yudao.captcha.enable 配置，日志均显示更新成功，但是new value的值一直为第1次修改的值！

2022-08-27 01:51:05.980 |  INFO 6500 | Apollo-Config-1 [TID: N/A] c.f.a.s.p.AutoUpdateConfigChangeListener | Auto update apollo changed value successfully, new value: **false**, key: yudao.captcha.enable, beanName: captchaServiceImpl, field: cn.iocoder.yudao.module.system.service.common.CaptchaServiceImpl.enable

**Comment by happier2** [comment]
> 碰到问题，请在 [YunaiV/ruoyi-vue-pro/issues](https://github.com/YunaiV/ruoyi-vue-pro/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) 搜索是否存在相似的 issue。
> 
> 不按照模板提交的 issue，会被系统自动删除。
> 
> ### 基本信息
> * ruoyi-vue-pro 版本：1.6.4
> * 操作系统：Win10
> * 数据库：MySQL5.7
> 
> ### 你猜测可能的原因
> （必填）我花费了 2-4 小时自查，发现可能的原因是：Apollo配置中心问题？
> 
> ### 复现步骤
> 第一步，启动后端，默认yudao.captcha.enable为true
> 
> 第二步，进入 [基础设施 -> 配置管理] 菜单，将配置项 yudao.captcha.enable 修改为 false，前端登录无需验证码。
> 
> 第三步，如果再次将yudao.captcha.enable 修改为 true，前端无法显示验证码，需要重启后端才行！
> 
> ### 报错信息
> 多次修改 yudao.captcha.enable 配置，日志均显示更新成功，但是new value的值一直为第1次修改的值！
> 
> 2022-08-27 01:51:05.980 | INFO 6500 | Apollo-Config-1 [TID: N/A] c.f.a.s.p.AutoUpdateConfigChangeListener | Auto update apollo changed value successfully, new value: **false**, key: yudao.captcha.enable, beanName: captchaServiceImpl, field: cn.iocoder.yudao.module.system.service.common.CaptchaServiceImpl.enable

由于Jasypt对所有的环境PropertySource进行Decorator，而且Jasypt自身有缓存机制，导致Apollo配置失效，可以将Jasypt依赖去掉或者按照Apollo上的issue解决

[apollo issues 2162](https://github.com/apolloconfig/apollo/issues/2162)

**Comment by YunaiV** [comment]
已修复
