### ISSUE TITLE
建议将“基础设施/定时任务”页面的”操作“列的那坨链接按钮优化一下

### ISSUE THREAD

**Issue by leeoo** [YunaiV/ruoyi-vue-pro#18]
建议将“基础设施/定时任务”页面的”操作“列的那坨链接按钮优化一下，参考”系统管理/用户管理“页面的”操作“列，把优先级低的链接按钮放到”更多操作“下拉菜单中。

**Comment by YunaiV** [comment]
收到，搞一搞。

有兴趣 pr 下么，啊哈哈哈

**Comment by wuxiaohua17** [comment]
quartz换成xxl-job是不是更合适？

**Comment by YunaiV** [comment]
> quartz换成xxl-job是不是更合适？

可以替换哈。看团队需要。主要这个是个 all in one 的项目，所以没去接入 xxl-job

**Comment by YunaiV** [comment]
已经优化
