### ISSUE TITLE
新建的模块和数据源,但是列表不能正确获取字典

### ISSUE THREAD

**Issue by Stars-XK** [YunaiV/ruoyi-vue-pro#180]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：2022.08.29的版本
- 操作系统：deepin
- 数据库：mysql

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：大概是新建的数据源和新的模块导致数据访问不到?

### 复现步骤

第一步，创建新数据源

第二步，创建新模块

第三步，创建新页面,给字段关联字典

第四步,  在新建的页面中新增数据,发现字典不能正常获取

### 报错信息

![image](https://user-images.githubusercontent.com/39972726/187189001-b817bd51-fc92-4e06-9574-ba0425d4d8ca.png)
![image](https://user-images.githubusercontent.com/39972726/187189097-d8976b95-db14-4254-a992-20595012a0e4.png)
![image](https://user-images.githubusercontent.com/39972726/187189176-05517595-54c0-4892-b9c5-db27d365055d.png)

**Comment by YunaiV** [comment]
1. 刷新下页面
2. 重启下 server

**Comment by YunaiV** [comment]
由于没有后续的回复，该 issue 先暂时关闭。
后续有问题，可以继续回复该 issue~
