### ISSUE TITLE
想要实现指定下一任务审批人该怎么做？

### ISSUE THREAD

**Issue by HongZeTao** [YunaiV/ruoyi-vue-pro#182]
### 基本信息

- ruoyi-vue-pro 版本：
- 比如下一任务的分配规则是一个用户组，但是需当前任务处理人指定一个，而不是随机

### 当前：

- 创建 task 时，查询分配规则获取可处理任务的任务处理人，再将任务随机分配给某一个
- 创建 task 前，先获取到 DelegateExecution 根据运行实例信息【execution】生成 【运行 task】再执行自定义 BpmUserTaskActivityBehavior.handleAssignments()分配任务
![image](https://user-images.githubusercontent.com/63632718/188847315-5a1e217f-bd17-40ab-978a-78582bdaede4.png)
![image](https://user-images.githubusercontent.com/63632718/188848816-9a6f9aca-ec30-41d2-b62f-7f663144c7be.png)

###　思考：
获取当前任务时，去获取下一ｕｓｅｒｔａｓｋ，存在则获取到分配规则相应用户，选择并ｃｏｍｐｌｅｔｅ

**Comment by YunaiV** [comment]
如果下一个任务比较明确，直接调用 calculateTaskCandidateUsers 就可以了。
如果情况比较多，得模拟一次任务的执行，获得真实的下一个任务。

这块要后续进行下实现。

**Comment by YunaiV** [comment]
该 issue 先关闭，已经整合到工作流后续的计划。
