### ISSUE TITLE
BUG - 租户可修改删除菜单

### ISSUE THREAD

**Issue by rzh0001** [YunaiV/ruoyi-vue-pro#183]
### 基本信息
租户可以修改、删除菜单配置，操作后系统菜单配置直接改变，导致出错。

- ruoyi-vue-pro 版本：最新
- 操作系统：
- 数据库：

### 你猜测可能的原因

应该输属于设计问题，可考虑改成租户管理员删除时，去掉角色表中的配置，或者其他方案

### 复现步骤

第一步，登录租户管理

第二步，删除菜单

第三步，登录主管理员，被删除的菜单消失了

### 报错信息
无报错

**Comment by YunaiV** [comment]
使用不正确哈，菜单管理，不应该分配给非系统的租户。
菜单是全局性的东东
