### ISSUE TITLE
工作流模块可以迁移出来到别的项目吗?

### ISSUE THREAD

**Issue by MdcGIt** [YunaiV/ruoyi-vue-pro#184]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息
工作流模块可以迁移出来到别的项目吗? 
比如说我想把ruoyi-vue-pro的activiti工作流模块引入到我们自己的项目中,是否支持?  模块是否完全解耦了   
- ruoyi-vue-pro 版本：
- 操作系统：
- 数据库：

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：xxxxxx

### 复现步骤

第一步，

第二步，

第三步，

### 报错信息

带上必要的截图

**Comment by YunaiV** [comment]
不能直接迁移，必须以这个脚手架为基础。
这个就像，使用 spring 的项目，不可能直接迁移到使用 guice 的项目。
