### ISSUE TITLE
下载下来后,登录验证图片无法显示

### ISSUE THREAD

**Issue by kuitao1018** [YunaiV/ruoyi-vue-pro#185]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：1.6.3.1611
- 操作系统：win10
- 数据库：wu

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：验证图片无法显示 不能跳过 

### 复现步骤

vscode插件都下了的

### 报错信息

![1664445066813](https://user-images.githubusercontent.com/38758237/193000577-b80ed7ce-ae2b-4638-bc1f-3233ad75041b.png)

**Comment by Techoc** [comment]
切换分支 我切换到1.6.2就好了

**Comment by kuitao1018** [comment]
> 切换分支 我切换到1.6.2就好了

1.6.2 三个分支都试了 ,还是不行 ,是否要配合后台服务器

**Comment by YunaiV** [comment]
提供复现步骤哈。=

**Comment by JacksonChen-czc** [comment]
> 提供复现步骤哈。=

1、clone代码。master分支
2、配置完数据库，redis后，启动项目，
3、直接访问方式一的前端，无法登录。

排查：/admin-api/system/captcha/get-image接口报错”账号未登录“

调试：将/admin-api/system/captcha/get-image允许匿名访问如下：

                // 1.5 验证码captcha 允许匿名访问
                .antMatchers("/captcha/get", "/captcha/check","/admin-api/system/captcha/get-image").permitAll()

结果接口返回404，项目中也没找到对象的接口代码。好像是图片验证码功能未实现，但是前端已经在调用？

**Comment by YunaiV** [comment]
已修复！
