### ISSUE TITLE
列表Table多选删除怎么实现

### ISSUE THREAD

**Issue by kuitao1018** [YunaiV/ruoyi-vue-pro#187]
使用原生控件解决

**Comment by kuitao1018** [comment]
<Table
        :columns="allSchemas.tableColumns"
        **:selection="true"**
        :data="tableObject.tableList"
        :loading="tableObject.loading"
        :pagination="{
          total: tableObject.total
        }"
        v-model:pageSize="tableObject.pageSize"
        v-model:currentPage="tableObject.currentPage"
        @register="register"
        :header-cell-style="{background:'#E7F0FF',color:'#333333'}"
        border
      >

selection="true" 属性修改后可以看到多选框 请问怎么获取 多选后的数据 


 const renderTableSelection = () => {
      const { selection, reserveSelection, align, headerAlign } = unref(getProps)
      // 渲染多选
      return selection ? (
        <ElTableColumn
          type="selection"
          reserveSelection={reserveSelection}
          align={align}
          headerAlign={headerAlign}
          width="50"
        ></ElTableColumn>
      ) : undefined
    }

 <ElTable
          // @ts-ignore
          ref={elTableRef}
          data={unref(getProps).data}
          **onSelection-change={selectionChange}**
          {...unref(getBindValue)}
        >
          {{
            default: () => rnderTableColumn(),
            // @ts-ignore
            append: () => getSlot(slots, 'append')
          }}
        </ElTable>

 selectionChange  这个方法多选的时候 打印出来的 还是单选 
 能帮忙解决一下吗?  很急很急很急

**Comment by YunaiV** [comment]
element ui 可以去了解下相关的文档哈。
