### ISSUE TITLE
多租户忽略问题

### ISSUE THREAD

**Issue by ctrl1109** [YunaiV/ruoyi-vue-pro#188]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。
没有
不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：1.6.2
- 操作系统：win
- 数据库：mysql

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：不是特别清楚，每次启动错了一次以后就正常了

### 复现步骤

第一步，给不需要多租户过滤的mapper 加上  @InterceptorIgnore(tenantLine = "true")
也试过  @TenantIgnore

第二步，启动后  @TenantIgnore 无效，还是会用的多租户的过滤拆解sql，然后报sql错误
![image](https://user-images.githubusercontent.com/101610374/196325179-199c4f4d-7b1d-4d1e-a3dd-69b025904699.png)
@InterceptorIgnore(tenantLine = "true")用这个注解的话，第一次接口调用报同意的错误，第二次及后面的调用就不会报错，正常了。
第三步，

### 报错信息

带上必要的截图

**Comment by softboy99** [comment]
请也加到代码生成器上，配置界面上也加，生成的代码自动加
