### ISSUE TITLE
定时任务“执行一次“无反应，也无报错

### ISSUE THREAD

**Issue by nothingp** [YunaiV/ruoyi-vue-pro#189]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：最新的main分支
- 操作系统：windows
- 数据库：mysql8

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：未知

### 复现步骤

第一步，
点击定时任务执行一次，无反应

第二步，

第三步，

### 报错信息

带上必要的截图

**Comment by YunaiV** [comment]
需要将定时任务的开关打开哈。
