### ISSUE TITLE
添加新菜单显示问题

### ISSUE THREAD

**Issue by bq985** [YunaiV/ruoyi-vue-pro#192]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：1.6.4
- 操作系统：windwos
- 数据库：mysql8

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：前端左边菜单显示的问题

### 复现步骤

第一步，
以管理员身份登录，并进入到菜单管理功能，新增菜单目录，菜单显示正常
第二步，
在新加的菜单目录下添加菜单及按钮，在菜单管理功能界面显示正常。
第三步，
退出系统，重新登录，在左边的操作菜单中，没有菜单的菜单目录会正常显示，但是，下面有菜单的菜单目录没有显示，只显示菜单。
### 报错信息

带上必要的截图
![image](https://user-images.githubusercontent.com/61642599/198886165-de22eb34-85dd-464a-ae66-d626465f4b42.png)

**Comment by kuitao1018** [comment]
你解决了没 页面跳转 好像会跳到项目外面去 有没有碰到 ,你这个问题 应该和权限有关 设置一下权限看能不能出来

**Comment by YunaiV** [comment]
如果只有一个子菜单，默认展示在顶层
