### ISSUE TITLE
升级最新版本后，定时spring.quartz.auto-startup的属性一直是false

### ISSUE THREAD

**Issue by nothingp** [YunaiV/ruoyi-vue-pro#199]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：最新的分支
- 操作系统：
- 数据库：

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：xxxxxx

### 复现步骤

第一步，用docker 加载镜像，用非local的环境启动，加载不到属性

第二步，

第三步，

### 报错信息

带上必要的截图

**Comment by YunaiV** [comment]
测试了下，不存在这个情况，建议自查下哈。
