### ISSUE TITLE
基础设施-代码生成-整个模块不能使用

### ISSUE THREAD

**Issue by andywang2023** [YunaiV/ruoyi-vue-pro#202]
1、导入时提示data_type不能为空；
2、手工把那个字段设置改为可以为空，导入后，进行后面的生成代码的编辑配置，点提交保存，各种报错。根本原因还是data_type为空导致。

<img width="508" alt="p1" src="https://user-images.githubusercontent.com/122243051/211230893-4319fbbc-5e66-4dd5-92a5-839f51dd5147.png">
<img width="978" alt="p2" src="https://user-images.githubusercontent.com/122243051/211230897-9e2589f3-4185-4624-a124-3dae8b6b991a.png">
<img width="239" alt="p3" src="https://user-images.githubusercontent.com/122243051/211230907-071ec48b-9160-44c5-86ce-9c5919ac1cc0.png">

**Comment by YunaiV** [comment]
已修复！
