### ISSUE TITLE
swagger response中的data 不能展开

### ISSUE THREAD

**Issue by ecshoper** [YunaiV/ruoyi-vue-pro#203]
1. knife4j 中 response 返回的data 都不能展开 展示正常的参数
```
"definitions": f
"CommonResultewxIsapisignaturex":"type":"object"properties":f
"code":"type":"integer""format":"int32"
data":
"type":"object
"msg":
"type":"string'
"title";"CommonResultuwxIsapisignaturex"
```

data":
"type":"object  这个地方是有问题 正常应该是 $ref="#/definitions/xxxx对象"

**Comment by YunaiV** [comment]
<img width="1633" alt="image" src="https://user-images.githubusercontent.com/2015545/211690089-149e3c0e-7590-446c-b430-28cc6c715902.png">

我这里都可以，建议自查下噢。
