### ISSUE TITLE
进入菜单管理报404

### ISSUE THREAD

**Issue by balzaron** [YunaiV/ruoyi-vue-pro#207]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：1.6.6-snapshot
- 操作系统：mac
- 数据库：mysql

### 你猜测可能的原因

vue调用错无

### 复现步骤

第一步，
进入菜单管理直接404

### 报错信息

带上必要的截图
<img width="204" alt="image" src="https://user-images.githubusercontent.com/9757578/215235928-c929aa8f-9843-483a-9fcd-d18ad4a1be51.png">
<img width="864" alt="image" src="https://user-images.githubusercontent.com/9757578/215235969-ef04f03a-0184-421f-8d77-bbdeed694878.png">

**Comment by YunaiV** [comment]
需要导入 vue3 的菜单噢。
主要原因是，vue2 和 vue3 的组件路径不同，导致菜单无法全部兼容。

**Comment by zws-code** [comment]
我对比了一下 vue2 和 vue3 的菜单数据.  除了多出来的菜单和修改时间.没发现有不同的组件路径的. 
但是就是用vue2的菜单 vue3 就会404, 太奇怪了
