### ISSUE TITLE
流程图条件网关中间的“x”不显示以及部分流程线显示有问题

### ISSUE THREAD

**Issue by ykyh-arch** [YunaiV/ruoyi-vue-pro#208]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：2022年10月13日 master
- 操作系统：window10
- 数据库：mysql5.7

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：前端的bpmn-js使用出问题

### 复现步骤

第一步，建立oa_leave请假流程

第二步，发起流程

第三步，走完流程，查看流程审批图

### 报错信息
![微信截图_20230128164253](https://user-images.githubusercontent.com/33443746/215256434-147c90ee-1b49-41e0-a6be-d90fbe5ea2d3.png)

**Comment by YunaiV** [comment]
收到。https://gitee.com/zhijiantianya/ruoyi-vue-pro/issues/I67CJS 会在这个 issue 统一进行 fix 噢
最近在处理 Vue3 的工作流，所以处理起来不会这么快~
