### ISSUE TITLE
基础设施-代码生成-同步异常和编辑页面反显问题

### ISSUE THREAD

**Issue by andywang2023** [YunaiV/ruoyi-vue-pro#209]
1、导入需要生成代码的表后，点击“同步”按钮异常，如下图：
![image](https://user-images.githubusercontent.com/122243051/215312504-189c89e0-8a92-48d1-95dc-2a21c07a5c92.png)
![image](https://user-images.githubusercontent.com/122243051/215312536-eb0edf7d-72d7-49f1-ba5f-1e09ebe2fbeb.png)

2、生成代码时的字段选择的是“Boolean是否类型”，可以新增和在列表中反显，但打开编辑页面时未能反显，如下3个图
![image](https://user-images.githubusercontent.com/122243051/215313683-f9e5bc4d-d600-4e7e-90a2-343550bfa978.png)
![image](https://user-images.githubusercontent.com/122243051/215313801-a070596d-f59a-441a-a739-a88e51043bb8.png)
![image](https://user-images.githubusercontent.com/122243051/215313815-b7759609-3041-47f6-80c9-fff6e24f5b09.png)

**Comment by andywang2023** [comment]
增加发现问题：
3、在查询条件的自定义的下拉条件部分，点击右边的清除图标后，里面的内容是清除了，但查询的结果却反而查不出来。
![image](https://user-images.githubusercontent.com/122243051/215314146-1e9c9ac8-2b46-483f-a57d-813ec8c0f123.png)
![image](https://user-images.githubusercontent.com/122243051/215314157-c52522bf-6e22-4053-adfe-038654ea4953.png)
![image](https://user-images.githubusercontent.com/122243051/215314132-77e5524c-910b-418d-be11-eee6595f9c0e.png)

**Comment by YunaiV** [comment]
收到~ 有兴趣 fix 一下么？

**Comment by fengyunhe** [comment]
代码生成空指针问题修复，替换为这几行：
`
 //计算需要修改的字段，插入时重新插入，删除时将原来的删除
        BiPredicate<TableField, CodegenColumnDO> pr =
                (tableField, codegenColumn) -> {
                    return Objects.equals(tableField.getType(), codegenColumn.getDataType())
                            && tableField.getMetaInfo().isNullable() == codegenColumn.getNullable()
                            && tableField.isKeyFlag() == codegenColumn.getPrimaryKey()
                            && Objects.equals(tableField.getComment(), codegenColumn.getColumnComment());
                };
`

**Comment by YunaiV** [comment]
> 代码生成空指针问题修复，替换为这几行： `//计算需要修改的字段，插入时重新插入，删除时将原来的删除 BiPredicate<TableField, CodegenColumnDO> pr = (tableField, codegenColumn) -> { return Objects.equals(tableField.getType(), codegenColumn.getDataType()) && tableField.getMetaInfo().isNullable() == codegenColumn.getNullable() && tableField.isKeyFlag() == codegenColumn.getPrimaryKey() && Objects.equals(tableField.getComment(), codegenColumn.getColumnComment()); };`

这个已经合并修复
