### ISSUE TITLE
Vue3版本前端404问题

### ISSUE THREAD

**Issue by CoderRyou** [YunaiV/ruoyi-vue-pro#210]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：1.7.0
- 操作系统：windows 10
- 数据库：Mysql 8.0.12

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：xxxxxx

### 复现步骤

第一步，点击“用户管理”或“菜单管理”404

第二步，

第三步，

### 报错信息

带上必要的截图
![企业微信截图_20230202111413](https://user-images.githubusercontent.com/57828491/216222619-ab351456-0965-4e9b-8ad7-b9d013e13e94.png)

**Comment by liiklin** [comment]
菜单问题

**Comment by YunaiV** [comment]
已修复
