### ISSUE TITLE
maven多模块下版本管理问题${revision}

### ISSUE THREAD

**Issue by 643562798** [YunaiV/ruoyi-vue-pro#219]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：1.7.0-snapshot
- 操作系统：win10
- 数据库：mysql

### 你猜测可能的原因

当另外的项目引用 ruoyi-vue-pro 中的某个 jar 时，无法引用会报错

### 复现步骤

第一步，新建一个项目

第二步，引入一下依赖
```
        <dependency>
            <groupId>cn.iocoder.boot</groupId>
            <artifactId>yudao-common</artifactId>
            <version>1.7.0-snapshot</version>
        </dependency>
```
第三步，编译打包

### 报错信息
![b47e7b2b442f89207b71b9c54920bb7](https://user-images.githubusercontent.com/11897786/221815678-68dcc1a9-1bbd-44b8-81bb-3b1360ce7e17.png)

**Comment by 643562798** [comment]
Maven多模块结构下版本管理的正确姿势(CI Friendly Versions) - ${revision} - 个人文章 - SegmentFault 思否
https://segmentfault.com/a/1190000019280804

**Comment by YunaiV** [comment]
参考 https://gitee.com/zhijiantianya/ruoyi-vue-pro/pulls/441 处理
