### ISSUE TITLE
问题 1.租户管理员可以删除自己  2.租户管理员自己可以更新自己角色的菜单权限

### ISSUE THREAD

**Issue by YanXinDarker** [YunaiV/ruoyi-vue-pro#220]
版本信息-分离版-最新

**基本信息**
1.租户管理员可以删除自己  
2.租户管理员自己可以更新自己角色的菜单权限
    
**复现步骤**
1.租户管理员delete自己 
第一步，新建租户登录后台
第二步，系统管理-用户管理
第三步，删除自己，提示无该操作权限  但是依然删除成功！！！

2.自己可以更新自己角色的菜单权限
第一步，新建租户登录后台
第二步，系统管理-角色管理
第三步，菜单权限-全不选-刷新后只有首页，无法再次选择分配菜单

**Comment by YunaiV** [comment]
这两块目前暂时不做限制哈。
