### ISSUE TITLE
租户的请求未传递，请进行排查

### ISSUE THREAD

**Issue by guobin510** [YunaiV/ruoyi-vue-pro#222]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：<revision>1.6.6-snapshot</revision>
- 操作系统：win10
- 数据库：mysql

### 你猜测可能的原因

我按文档新建了一个模块。新增了demo/test
![image](https://user-images.githubusercontent.com/10906487/222107553-7d92a11b-7715-4459-931e-73cd9ad0ce95.png)
这里也添加了过滤
![image](https://user-images.githubusercontent.com/10906487/222107753-5b8010cd-6313-473f-a68a-b93ee93300af.png)
用postman通过网关请求也没有问题。但是后台却报一下错误
![image](https://user-images.githubusercontent.com/10906487/222107942-403f7e6c-75a4-4030-9288-cd7413574648.png)
![image](https://user-images.githubusercontent.com/10906487/222108358-ddf0085d-581c-4156-a485-0efe531b7e87.png)

我在TenantSecurityWebFilter->isIgnoreUrl 方法中添加了日志。request.getRequestURI()的值不是我请求的app-api/demo/test/get url，而是 /rpc-api/infra/api-access-log/create 这个不知道为什么。
![image](https://user-images.githubusercontent.com/10906487/222108890-0f94cf2a-fc2b-44ce-af2e-074ff58820e8.png)

（必填）我花费了 2-4 小时自查，发现可能的原因是：一直没有发现问题在哪里。断点调式了，

**Comment by YunaiV** [comment]
cloud 的问题，辛苦提交到 cloud 项目哈。
