### ISSUE TITLE
项目首次编译失败

### ISSUE THREAD

**Issue by Altman29** [YunaiV/ruoyi-vue-pro#223]
### 基本信息

- ruoyi-vue-pro 版本：gitee clone下来的 master分支
- 操作系统：mac
- 数据库：datagrip

### 你猜测可能的原因

不太清楚，编译说 yudao-common 编译失败

### 复现步骤

首次使用，编译完成后，执行```mvn clean package -Dmaven.test.skip=true```
### 报错信息

带上必要的截图

![Uploading image.png…]()

**Comment by Altman29** [comment]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project yudao-common: Compilation failure
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :yudao-common

**Comment by YunaiV** [comment]
使用 JDK 版本？

**Comment by YunaiV** [comment]
No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?

**Comment by Altman29** [comment]
你好，使用的是1.8

**Comment by Altman29** [comment]
![image](https://user-images.githubusercontent.com/15527839/223719868-eea3a831-5d7f-42ac-b83f-d0f8f10a56ce.png)

**Comment by Altman29** [comment]
![image](https://user-images.githubusercontent.com/15527839/223720043-f4dca2b9-cbe3-4d28-b6a5-2399f8084d2e.png)
错误截图；

**Comment by YunaiV** [comment]
java -version，在命令行敲下。看看返回的是什么。

**Comment by zhzb** [comment]
同样的问题。何解？Windows 11平台。

**Comment by RimuruTem** [comment]
如果跟我一样用的IDEA可以在file-setting里修改maven路径为自己下载的版本。今天弄了一上午解决了。
![image](https://user-images.githubusercontent.com/71238290/227451607-35454231-846a-4657-91bc-8e02c1754f29.png)

**Comment by happy-leraner** [comment]
我也是花了一条才搞定编译



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月24日 15:19 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | Re: [YunaiV/ruoyi-vue-pro] 项目首次编译失败 (Issue #223) |

如果跟我一样用的IDEA可以在file-setting里修改maven路径为自己下载的版本。今天弄了一上午解决了。

**Comment by YunaiV** [comment]
本地测试，不存在这个问题哈。
macos
jdk 1.8.0_144
maven 3.8.x、3.9.0、3.9.1 

都没问题。
