### ISSUE TITLE
找不到POM文件

### ISSUE THREAD

**Issue by less-famous-ITer** [YunaiV/ruoyi-vue-pro#226]
PS D:\Projects\**DaXue\teachingmanagement> mvn clean install package '-Dmaven.test.skip=true'
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: cn.iocoder.boot:yudao-dependencies:pom:1.6.6-snapshot was not found in https://maven.aliyun.com/repository/public dur
ing a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of aliyunmaven has e
lapsed or updates are forced @ cn.iocoder.boot:yudao:${revision}, D:\Projects\**DaXue\teachingmanagement\pom.xml, line 52, column 25
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project cn.iocoder.boot:yudao:1.6.6-snapshot (D:\Projects\**DaXue\teachingmanagement\pom.xml) has 1 error
[ERROR]     Non-resolvable import POM: cn.iocoder.boot:yudao-dependencies:pom:1.6.6-snapshot was not found in https://maven.aliyun.com/repository/public
 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of aliyunmaven h
as elapsed or updates are forced @ cn.iocoder.boot:yudao:${revision}, D:\Projects\**DaXue\teachingmanagement\pom.xml, line 52, column 25 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by less-famous-ITer** [comment]
<img width="714" alt="image" src="https://user-images.githubusercontent.com/108137214/223909703-adce1f5d-13a9-40c3-bdd0-bfbc4b806dc5.png">
阿里云的仓库里也找不到对应的POM

**Comment by YunaiV** [comment]
看下 https://doc.iocoder.cn/quick-start/ 文档噢。
