### ISSUE TITLE
执行mvn clean package -Dmaven.test.skip=true报错

### ISSUE THREAD

**Issue by RobersonLuo** [YunaiV/ruoyi-vue-pro#229]
### 基本信息

- ruoyi-vue-pro 版本：刚clone的最新版本
- 操作系统：windows 10
- 数据库：mysql 8.0

### 你猜测可能的原因

初次使用，根本就没头绪。

### 复现步骤
执行 mvn clean package -Dmaven.test.skip=true

### 报错信息

![image](https://user-images.githubusercontent.com/7013492/224473454-271d0101-eddb-4895-879b-cc017936bbd7.png)

**Comment by superfishers** [comment]
我也遇到一样的问题，使用的maven3.9，把maven版本改为3.5.4就好了。

**Comment by ZevFung** [comment]
> 我也遇到一样的问题，使用的maven3.9，把maven版本改为3.5.4就好了。

一样的问题，这个方法解决了我的问题

**Comment by YunaiV** [comment]
都是 windows 么？我刚 mac 测试 3.9 版本，没问题也。

**Comment by RobersonLuo** [comment]
搞定了：
1、设置JAVA_HOME、MAVEN_HOME环境变量；
2、将Maven的包下载源地址，从国外服务器切换到国内镜像即可（阿里云Maven源）
https://developer.aliyun.com/mvn/guide

**Comment by fk6655** [comment]
> 都是 windows 么？我刚 mac 测试 3.9 版本，没问题也。
我是Windows，java -version 1.8.0_351，maven版本3.9.0 都是报这个错误


> 搞定了： 1、设置JAVA_HOME、MAVEN_HOME环境变量； 2、将Maven的包下载源地址，从国外服务器切换到国内镜像即可（阿里云Maven源） https://developer.aliyun.com/mvn/guide

老哥我的环境配置没问题也会报错…为什么你这样整就好了呢，好神奇
