### ISSUE TITLE
mall模块逻辑判断BUG

### ISSUE THREAD

**Issue by imchenr** [YunaiV/ruoyi-vue-pro#230]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：1.7.1
- 操作系统：macOS
- 数据库：mariadb

### 你猜测可能的原因

cn.iocoder.yudao.module.product.service.category.ProductCategoryServiceImpl

validateCategory方法，103行，针对分类是否正常的判断有误

```
if (Objects.equals(category.getStatus(), CommonStatusEnum.ENABLE.getStatus())) {
    throw exception(CATEGORY_DISABLED, category.getName());
}
```

应该改为

```
if (Objects.equals(category.getStatus(), CommonStatusEnum.DISABLE.getStatus())) {
    throw exception(CATEGORY_DISABLED, category.getName());
}
```

### 复现步骤

正常添加商品即可

### 报错信息

<img width="399" alt="image" src="https://user-images.githubusercontent.com/79409344/224935854-11d62930-6603-4adc-b8eb-99bbc9c12531.png">

**Comment by YunaiV** [comment]
好的，可以 pr 一下噢。

**Comment by YunaiV** [comment]
已修复
