### ISSUE TITLE
mybatis plus join 副表逻辑删除问题

### ISSUE THREAD

**Issue by zhanglianfen** [YunaiV/ruoyi-vue-pro#233]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：1.7.1
- 操作系统：win11
- 数据库：mysql

### 复现步骤

mybatis plus join 关联副表的逻辑删除会添加到where语句后，如果使用left join 会导致查询结果没有数据
查阅文档将 mybatis-plus-join-boot-starter 升级到1.4.4版本，进行配置可以将逻辑删除的位置改到 on 处
配置
# MyBatis Plus Join 的配置项
mybatis-plus-join:
  logic-del-type: on  #副表逻辑删除条件的位置 支持 where / on  默认 where

**Comment by YunaiV** [comment]
已经修复。
