### ISSUE TITLE
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project yudao-common: Fatal error compiling: ЧĿ귢а: 11 -> [Help 1]

### ISSUE THREAD

**Issue by 654409314** [YunaiV/ruoyi-vue-pro#237]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：1.7.1
- 操作系统：win10
- 数据库：mysql8
- jdk:1.8_161
-maven: 3.6.1
### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：打包编译报错
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project yudao-common: Fatal error compiling: ЧĿ귢а: 11 -> [Help 1]

### 复现步骤

第一步，

第二步，

第三步，

### 报错信息

带上必要的截图

**Comment by YunaiV** [comment]
测试也这个问题哈。
