### ISSUE TITLE
Mvn install报错

### ISSUE THREAD

**Issue by LambertDT** [YunaiV/ruoyi-vue-pro#238]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：最新
- 操作系统：MacOS
- 数据库：MySQL

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：MacOS系统问题。  同样的代码编译，MacOS报错，win10不报错

### 复现步骤

第一步，
mvn clean package install '-Dmaven.test.skip=true'
第二步，
报错
第三步，

### 报错信息
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-jar-plugin:3.3.0:jar (default-jar) on project yudao-spring-boot-starter-biz-weixin: You have to use a classifier to attach supplemental artifacts to the project instead of replacing them. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :yudao-spring-boot-starter-biz-weixin
带上必要的截图
![image](https://user-images.githubusercontent.com/51145381/228177649-8dc23fa0-1fbf-4b63-a774-5f4aac17d093.png)

**Comment by Sky96712** [comment]
你的idea版本是什么？我的本地环境是idea2023.1，jdk1.8.0_361，也出现一模一样的问题

**Comment by YunaiV** [comment]
> 你的idea版本是什么？我的本地环境也是Mac idea:2023.1，jdk1.8.0_361，也出现一模一样的问题

maven 版本多少？

**Comment by YunaiV** [comment]
本地测试，maven 3.9.1 3.9.0 3.8.x 版本都没问题。
这个 issue 暂时关闭，有问题单独开 issue 哈。
