### ISSUE TITLE
Caused by: java.sql.SQLSyntaxErrorException: Table 'arsmoOA_pro.ACT_GE_PROPERTY' doesn't exist

### ISSUE THREAD

**Issue by 654409314** [YunaiV/ruoyi-vue-pro#240]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：
- 操作系统：
- 数据库：

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：
Caused by: java.sql.SQLSyntaxErrorException: Table 'ruoyi-vue-pro.ACT_GE_PROPERTY' doesn't exist

### 复现步骤

第一步，所有模块都放开

第二步，重新编译打包

第三步，启动服务最好报错找不到这个表

### 报错信息
Caused by: java.sql.SQLSyntaxErrorException: Table 'ruoyi-vue-pro.ACT_GE_PROPERTY' doesn't exist
![image](https://user-images.githubusercontent.com/41300336/228401168-31f52e9c-7fa1-47e5-bc77-413961dda695.png)

带上必要的截图

**Comment by 654409314** [comment]
应该初始化sql但是没有初始化

**Comment by YunaiV** [comment]
应该是已经修复了这个问题。

https://www.cnblogs.com/anenyang/p/15155697.html

可以拉下 master 版本
