### ISSUE TITLE
设置头像超出字段长度

### ISSUE THREAD

**Issue by lunasaw** [YunaiV/ruoyi-vue-pro#242]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息
system_users#avatar 设置字段长度
com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'avatar' at row 1

- ruoyi-vue-pro 版本：latest
- 操作系统：macos 11
- 数据库：mysql5.7

### 你猜测可能的原因

上传minio 由String sha256Hex = DigestUtil.sha256Hex(content); + 文件名后缀拼接，得到length 超过字段长度100

### 复现步骤

第一步，

第二步，

第三步，

### 报错信息

带上必要的截图
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/52351139/229296150-26fdeb73-b650-4176-ba51-2b0c85e657c3.png">

**Comment by lunasaw** [comment]
可以的话，没有文件名avatar 生成的时候，考虑截取16位字符即可？

**Comment by YunaiV** [comment]
已调整 avatar 字段长度
