### ISSUE TITLE
ExcelUtils.read 不能获取正确对象

### ISSUE THREAD

**Issue by balzaron** [YunaiV/ruoyi-vue-pro#245]
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/9757578/229414762-ac90acf4-5413-4774-953b-0963814f6a89.png">

我发现这个util的read不能读取一个excelproperty的pojo对象, 我修改了一个基于hutool的excelUtils
<img width="1348" alt="image" src="https://user-images.githubusercontent.com/9757578/229414391-771f41ee-4909-45a5-9e6f-bc1f1b98efe8.png">
这样可以正确读取excel内容. pr是这github还是gitee可以提交? 或者作者大大不需要PR也可以

**Comment by balzaron** [comment]
<img width="1348" alt="image" src="https://user-images.githubusercontent.com/9757578/229414301-9094f280-d2a4-4b15-893b-ccfe479f0d36.png">
能够正确读取了.

**Comment by YunaiV** [comment]
实体上，是不是少添加了 @Accessors(chain = false) // 设置 chain = false，避免用户导入有问题

**Comment by YunaiV** [comment]
由于没有回复，暂时先关闭 issue
