### ISSUE TITLE
开启多租户缓存，Redis Key没有多租户隔离

### ISSUE THREAD

**Issue by ZevFung** [YunaiV/ruoyi-vue-pro#246]
项目启动TenantRedisCacheManager的getCache方法有执行
public Cache getCache(String name) {
        // 如果开启多租户，则 name 拼接租户后缀
        if (!TenantContextHolder.isIgnore()
            && TenantContextHolder.getTenantId() != null) {
            name = name + ":" + TenantContextHolder.getTenantId();
        }

        // 继续基于父方法
        return super.getCache(name);
    }

**Comment by YunaiV** [comment]
https://doc.iocoder.cn/saas-tenant/#_5-5-redis-%E5%B1%82%E3%80%90%E9%87%8D%E8%A6%81%E3%80%91
