### ISSUE TITLE
审批流程，审批人审批的时候报错

### ISSUE THREAD

**Issue by yun36524** [YunaiV/ruoyi-vue-pro#247]
![image](https://user-images.githubusercontent.com/104484993/229994054-df2c7dc1-a923-4fc5-9b76-54301669175a.png)

![image](https://user-images.githubusercontent.com/104484993/229994185-c1c58333-796c-43d9-8831-0b58fc2fa75d.png)

图上红框标注的地方，空指针错误

已排查到的原因：
查询发起人的id是正确的的，但是会自动拼接当前登录用户的deptId作为查询条件之一，导致查询的startUser是null，
最终导致发起人没能成功落库到流程表

这个地方 --似乎--写了事务，但是未能成功限制以上错误

**Comment by yun36524** [comment]
![image](https://user-images.githubusercontent.com/104484993/229995004-3bc16409-3d6e-4bf0-ad85-63b1f2f56069.png)

**Comment by yun36524** [comment]
更正：发起人落库成功了，但是红框的代码是报错的，就是因为拼接了deptId

**Comment by yun36524** [comment]
> 更正：发起人落库成功了，但是红框的代码是报错的，就是因为拼接了deptId

![image](https://user-images.githubusercontent.com/104484993/229996024-2e7c0e73-a08a-4229-8077-af07b5c43fb5.png)

**Comment by yun36524** [comment]
![image](https://user-images.githubusercontent.com/104484993/229999386-42e1e5d8-2065-4b54-9d2a-1d23c75f278c.png)
查询已办任务列表，也会拼deptId，这个逻辑是什么

**Comment by 654409314** [comment]
我也遇到这个问题不知道在哪边拼接的deptId文档上面也没有说明，有的地方根本不需where后拼接deptId,在哪里拼接的应该具体告知下

**Comment by kongxubihai** [comment]
拼接deptId了，请排查下数据权限的问题，参考链接：https://doc.iocoder.cn/data-permission/#_1-%E5%AE%9E%E7%8E%B0%E5%8E%9F%E7%90%86
