### ISSUE TITLE
商品分类({})已禁用 , 判断逻辑错误.位于 yudao-module-mall 模块 ProductCategoryServiceImpl 

### ISSUE THREAD

**Issue by XHXJ** [YunaiV/ruoyi-vue-pro#249]
https://github.com/YunaiV/ruoyi-vue-pro/blob/b024c716edf1a7280fbb5f4e77231db331b37988/yudao-module-mall/yudao-module-product-biz/src/main/java/cn/iocoder/yudao/module/product/service/category/ProductCategoryServiceImpl.java#L103

提交记录:
https://github.com/YunaiV/ruoyi-vue-pro/commit/2f9eef589b68bffe1ab19a7b68d4a101ecbc5e6e

源代码:
```
        if (Objects.equals(category.getStatus(), CommonStatusEnum.ENABLE.getStatus())) {
            throw exception(CATEGORY_DISABLED, category.getName());
        }
```
现在是正常开启的商品分类会抛出异常"商品分类({})已禁用，无法使用"

应改为:
```
        if (Objects.equals(category.getStatus(), CommonStatusEnum.DISABLE.getStatus())) {
            throw exception(CATEGORY_DISABLED, category.getName());
        }
```

**Comment by YunaiV** [comment]
已修复。
