### ISSUE TITLE
进行钉钉登录，扫码后没有进入系统

### ISSUE THREAD

**Issue by ZhangChaoZhong** [YunaiV/ruoyi-vue-pro#253]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：!119 【众测版】合并最新的 Vue3 重构
- 操作系统：win10
- 数据库：mysql 8.0.26

### 你猜测可能的原因
扫码后，url里面的type值为空，但是vue3代码我不懂就没有去看了

### 复现步骤

第一步，
用的最新的vue3，以及后端代码。
vue3配置：VITE_APP_TENANT_ENABLE=true
后端配置：tenant: # 多租户相关配置项
              enable: true
启动前端：npm run dev
第二步，
点击钉钉登录，扫码后，出现下面的问题
### 报错信息
后端没有报错
![1](https://user-images.githubusercontent.com/30583522/231654839-2107cfa1-5da9-4f7e-83fe-0df13b2cf5e5.PNG)
前端卡在这里
![2 PNG](https://user-images.githubusercontent.com/30583522/231654856-92739c77-9293-4e64-9043-b97db16ce309.jpg)

**Comment by YunaiV** [comment]
已经修复。
