### ISSUE TITLE
在流程模型里面点击分配规则按钮无效

### ISSUE THREAD

**Issue by LiamWo** [YunaiV/ruoyi-vue-pro#255]
### 基本信息

- ruoyi-vue-pro 版本：1.7.1
- 操作系统：win10
- 数据库：MySQL8.0
- idea 2023

### 你猜测可能的原因

我从早上九点到晚上十点半，测试了ruoyi-vue-pro 和yudao-cloud，前端也从yudao-ui-admin-vue3换到yudao-ui-admin，
数据库也是删了又装，但是始终未找到问题。感觉像是api没有启用。

![屏幕截图 2023-04-13 221050](https://user-images.githubusercontent.com/105887402/231797166-69630f67-794f-4a7e-84c5-baeb724e3413.png)

**Comment by LiamWo** [comment]
因为死活点不了分配规则，所以尝试直接发布，结果如图

**Comment by YunaiV** [comment]
最好提供下 bpmn 图~暂时没碰到这个问题。

**Comment by LiamWo** [comment]
![1](https://user-images.githubusercontent.com/105887402/232226199-cc8e04b5-ad74-47ac-8f99-6ee97aa3349c.png)
![2](https://user-images.githubusercontent.com/105887402/232226202-b2fd5a68-cf0b-4ef8-b454-484c5a28a0e0.png)
![3](https://user-images.githubusercontent.com/105887402/232226203-2006aae8-5ccf-4db8-8841-b62cd759183e.png)
![4](https://user-images.githubusercontent.com/105887402/232226204-af9c38b1-9443-452f-a6ab-eaab57d4de11.png)
不知道这样看的清不清楚。

**Comment by LiamWo** [comment]
![5](https://user-images.githubusercontent.com/105887402/232226303-d9bab14a-d909-4191-ac76-356d99a540da.png)
少了一张

**Comment by LiamWo** [comment]
这个问题可能是因为我运行了多个不同版本的系统导致的，昨天重装系统后功能就正常了
