### ISSUE TITLE
Mysql切换到Oracle数据库后，代码生成模块 点击导入后，读取列表信息显示超时

### ISSUE THREAD

**Issue by wen3114687** [YunaiV/ruoyi-vue-pro#256]
### 基本信息

- ruoyi-vue-pro 版本：1.7.0
- 操作系统：windows 10
- 数据库：oralce 12c r2

### 你猜测可能的原因

切换到oracle数据库后，发现代码生成模块中，打开数据库表列表时一直出现超时。
后来跟了一下代码，发现DatabaseTableServiceImpl.java 这个类的 getTableList0方法  （44行）
其中一句
` DataSourceConfig dataSourceConfig = new DataSourceConfig.Builder(config.getUrl(), config.getUsername(),
                config.getPassword()).build();`
配置上有点问题。
      
因为和mysql的区别是，oralce需要指定schema，所以这行代码导致了oracle的版本在代码生成模块读取表信息的时候，报超时异常。
因为没指定schema，所以将oracle里所有的系统表也获取了，断点显示有999+的对象。

修改了一下
` DataSourceConfig dataSourceConfig = new DataSourceConfig.Builder(config.getUrl(), config.getUsername(),
                config.getPassword()).schema(config.getName()).build();`
加了 .schema方法，传一个schema名字，(这里我传了config中的用户名进去....因为建库的时候库名和用户名一样...不推荐这样做)
这样在oracle的环境下，代码生成可以获取到表信息了，而且这个方法不影响mysql的配置。

### 复现步骤

第一步，
数据库使用oracle

第二步，
启动项目

第三步，
点击代码生成模块
点击导入

### 报错信息

带上必要的截图
<img width="547" alt="微信图片_20230417173242" src="https://user-images.githubusercontent.com/20286123/232445779-e4ab5849-ba9c-438e-ba2e-3ce778c49e9a.png">

**Comment by ChenBigBig** [comment]
好像sql server也是存在这个问题的待修复

**Comment by Arlen-sc** [comment]
![7f454dba4d63db63fae41499c722994](https://github.com/YunaiV/ruoyi-vue-pro/assets/52154292/dcdef796-102a-4c96-b205-e7a4452369a5)
暂时解决方案是添加这个，但是经过测试，发现generator对SQLserver或者Oracle的数据结构读取还是存在问题，SQLServer读取结构不完整，Oracle就不知道了

**Comment by xb594328980** [comment]
能读到表注解和字段的注解吗，我这设置了但是读取不到

**Comment by sdlushao** [comment]
能提供下oracle的sql文件吗

**Comment by YunaiV** [comment]
已经修复。

https://gitee.com/zhijiantianya/ruoyi-vue-pro/commit/c6eed9a6360995c56abccd25f594351e53cd54d0

视图、自带部分表影响的
