### ISSUE TITLE
WXLitePayClient、WXNativePayClient、WXPubPayClient几个类doUnifiedOrder方法暂未实现吗？

### ISSUE THREAD

**Issue by 52Lau** [YunaiV/ruoyi-vue-pro#257]
### 基本信息

- ruoyi-vue-pro 版本：最新版

如下图，微信相关的这几个都是注释掉的，是没实现还是放开就可以了

<img width="1296" alt="image" src="https://user-images.githubusercontent.com/37538641/233093727-5a46d92e-5445-41ce-9fca-2fc861b2fefe.png">

**Comment by YunaiV** [comment]
已经实现。
