### ISSUE TITLE
多租户体系下会考虑加一层机构的概念吗

### ISSUE THREAD

**Issue by liuzhen9327** [YunaiV/ruoyi-vue-pro#259]
机构属于租户下，机构管理员可以维护自己机构内的角色，可以拥有自己机构下已有功能的权限控制

**Comment by YunaiV** [comment]
不错的建议，有兴趣贡献一下么？

**Comment by YunaiV** [comment]
> 最近正在做这个需求，我尽量做到通用化，后面有成果的话我提个pr 😂

好的哈。非常欢迎 pr 共享哈。= = 我们太忙，所以需要更多人来 PR 功能。

**Comment by happy-leraner** [comment]
改动这个大，我想二次开发都感觉好难，啥时候出稳定版本



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年04月27日 22:51 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | Re: [YunaiV/ruoyi-vue-pro] 多租户体系下会考虑加一层机构的概念吗 (Issue #259) |

最近正在做这个需求，我尽量做到通用化，后面有成果的话我提个pr 😂

好的哈。非常欢迎 pr 共享哈。= = 我们太忙，所以需要更多人来 PR 功能。

**Comment by YunaiV** [comment]
由于暂时没有同学贡献，说明可能需求量不大，非通用化需求，暂时关闭。
