### ISSUE TITLE
逻辑删除唯一索引报错

### ISSUE THREAD

**Issue by LZJZMT** [YunaiV/ruoyi-vue-pro#261]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：1.7.2
- 操作系统：macos
- 数据库：mysql

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：表结构设计是不是没考虑到删除后再新增会报唯一索引冲突

### 复现步骤

第一步，建立唯一索引,比如member_user表uk_mobile

第二步，逻辑删除18888888888用户

第三步，新增18888888888用户报唯一索引冲突,建议表结构统一升级,BaseDO新增deletedTime

### 报错信息

带上必要的截图

**Comment by luoyang125024608** [comment]
这是你自己该考虑的问题呀。所有逻辑删除都要自己去考虑唯一索引的问题。

**Comment by kongxubihai** [comment]
建立唯一索引时，需要额外增加 delete_time 字段，添加到唯一索引字段中，避免唯一索引冲突。例如说，system_users 使用 username 作为唯一索引：

未添加前：先逻辑删除了一条 username = yudao 的记录，然后又插入了一条 username = yudao 的记录时，会报索引冲突的异常。
已添加后：先逻辑删除了一条 username = yudao 的记录并更新 delete_time 为当前时间，然后又插入一条 username = yudao 并且 delete_time 为 0 的记录，不会导致唯一索引冲突。
参考官方文档： https://doc.iocoder.cn/mybatis/#_1-2-%E9%80%BB%E8%BE%91%E5%88%A0%E9%99%A4
