### ISSUE TITLE
 同一账号同时登录多台设备的个数配置

### ISSUE THREAD

**Issue by David0622** [YunaiV/ruoyi-vue-pro#262]
### 基本信息

- ruoyi-vue-pro 版本：1.7.3

当前的会员模块和系统用户登录没有限制同一账号在多处同时登录的问题，有些业务系统是不允许同时登录这样的使用场景的，建议添加一个配置项，允许同时登录的账号个数

**Comment by YunaiV** [comment]
不错的建议，有兴趣可以 pr 下哈。

**Comment by hss01248** [comment]
还有个刚需是允许同一个账号在不同端(手机,web,pc)的设备同时登录,同类型的设备只能登录一个/或n个.

**Comment by YunaiV** [comment]
> 还有个刚需是允许同一个账号在不同端(手机,web,pc)的设备同时登录,同类型的设备只能登录一个/或n个.

确实，特别一些知识付费的软件。

有兴趣贡献一下么？

**Comment by hss01248** [comment]
已经实现: https://blog.hss01248.tech/pages/7939b5/
但现在项目夹杂很多业务功能,后面看看怎么拆一下提一个pull request

**Comment by YunaiV** [comment]
> 已经实现: https://blog.hss01248.tech/pages/7939b5/ 但现在项目夹杂很多业务功能,后面看看怎么拆一下提一个pull request

看了下实现，功能没啥问题哈。

建议是，token 表增加一个 terminal 字段，表示设备。然后 oauth_client 可以配置每个 terminal 可以登录的数量。

**Comment by imaben** [comment]
+1 
有同样的需求，请求尽快合并主干

**Comment by YunaiV** [comment]
https://gitee.com/zhijiantianya/ruoyi-vue-pro/pulls/510/

可关注该 pr
