### ISSUE TITLE
sql文件更新时，能否提供更新文件

### ISSUE THREAD

**Issue by 2436536** [YunaiV/ruoyi-vue-pro#265]
目前合并项目最新版本时，sql文件冲突难以融合，能否提供针对上一版本的sql更新文件

### 基本信息

- ruoyi-vue-pro 版本：1.7.2
- 操作系统：mac
- 数据库：mysql5.7

**Comment by YunaiV** [comment]
后续会考虑提供，近期精力顾不上。
