### ISSUE TITLE
新增模块的sql执行语句控制台不打印

### ISSUE THREAD

**Issue by 654409314** [YunaiV/ruoyi-vue-pro#267]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：
- 操作系统：win10
- 数据库：mysql8

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：xxxxxx

### 复现步骤

第一步，按照文档新增模块

第二步，新增模块的数据库

第三步，重启后页面执行查询控制台不打印执行的mybatis的sql日志，其他模块我点击查询按钮控制台都会打印sql执行日志，这个我疑惑两天不知道框架是怎么处理的

### 报错信息

带上必要的截图

**Comment by 654409314** [comment]
自己新增的模块 不打印mybatis执行的sql日志

**Comment by YunaiV** [comment]
参考 application-local.yaml 文件，需要配置下 logger 配置项，设置为 debug
