### ISSUE TITLE
开启流程模块报错Error creating bean with name 'bpmProcessInstanceApiImpl

### ISSUE THREAD

**Issue by z1bracd** [YunaiV/ruoyi-vue-pro#269]
### 基本信息

- ruoyi-vue-pro 版本：1.7.2
- 操作系统：win11
- 数据库：mysql

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：

### 复现步骤

取消掉流程模块的注释，运行时报错，这个应该是什么原因呢

### 报错信息

![image](https://user-images.githubusercontent.com/75820568/237006598-980b8fdd-2295-4003-b69b-ec56b8c22659.png)

**Comment by z1bracd** [comment]
Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'bpmProcessInstanceApiImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'bpmProcessInstanceServiceImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'runtimeServiceBean' defined in class path resource [org/flowable/spring/boot/ProcessEngineServicesAutoConfiguration.class]: Unsatisfied dependency expressed through method 'runtimeServiceBean' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'processEngine': FactoryBean threw exception on object creation; nested exception is org.flowable.common.engine.api.FlowableException: Error initialising eventregistry data model

**Comment by YunaiV** [comment]
解决了么？本地暂时无法复现。

**Comment by 666wwx** [comment]
我也是同样的问题

**Comment by z1bracd** [comment]
已经解决了，是本地数据库需要修改一下配置。将default-storage-engine设为INNODB
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/75820568/1e6b69d0-88f0-40c3-b540-d437eda00e35)

**Comment by YunaiV** [comment]
好的哈。
