### ISSUE TITLE
Java后台中的.http结尾的文件作用是什么？是必须的吗

### ISSUE THREAD

**Issue by autumn11** [YunaiV/ruoyi-vue-pro#270]
Java后台中的.http结尾的文件（比如：OAuth2ClientController.http）作用是什么？是必须的吗？能删除么

**Comment by autumn11** [comment]
@zivyuan @jihao @mapleafly @csg0328 大佬帮忙看看

**Comment by HerbertGao** [comment]
[IntelliJ IDEA HTTP Client](https://www.jetbrains.com/help/idea/http-client-in-product-code-editor.html)

**Comment by YunaiV** [comment]
https://www.iocoder.cn/Spring-Boot/IDEA-HTTP-Client/
