### ISSUE TITLE
【欢迎贡献】定时任务开启/关闭报错[Required request parameter 'id' for method parameter type Long is not present]

### ISSUE THREAD

**Issue by dapeng0201** [YunaiV/ruoyi-vue-pro#273]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：1.7.2
- 操作系统：windows10
- 数据库：mysql

### 你猜测可能的原因

使用的vben-admin, 在api里添加headers: { 'Content-Type': 'application/x-www-form-urlencoded' }可正常请求

### 报错信息
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/28396334/65fe9229-2b91-42dd-982a-81afd90f1af3)
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/28396334/5f428c15-abfa-4532-a363-d28c1f89fd8f)
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/28396334/0894b44b-a62d-4f2e-aea4-2684881ddc0f)
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/28396334/add20f48-ccd8-48bb-8c00-4a93e308bc06)

前端修改content-type后正常请求
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/28396334/576ebe32-bce3-43de-a5d6-b295ad22a081)
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/28396334/dcdb076f-65c1-4671-8704-7caed307e4c4)

带上必要的截图

**Comment by YunaiV** [comment]
不错的建议，有兴趣 pr 下么？

**Comment by freesme** [comment]
vben项目没有在当前项目中管理，经验证当前项目下的 yudao-ui-admin 未出现该问题，或许应该在 [yudao-ui-admin-vben](https://github.com/yudaocode/yudao-ui-admin-vben) 中提交 issue?

**Comment by YunaiV** [comment]
对的哈。
