### ISSUE TITLE
一键改包失败

### ISSUE THREAD

**Issue by liupchina** [YunaiV/ruoyi-vue-pro#277]
### 基本信息

- ruoyi-vue-pro 版本：1.7.2
- 操作系统：
- 数据库：

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：xxxxxx

### 复现步骤

第一步，

第二步，

第三步，

### 报错信息

<img width="1552" alt="image" src="https://github.com/YunaiV/ruoyi-vue-pro/assets/19354900/dd8b4ea9-d10a-4559-b9ea-a8d1e1ba4b70">
<img width="782" alt="image" src="https://github.com/YunaiV/ruoyi-vue-pro/assets/19354900/317cc5d2-3426-4967-86a2-05c73afe182c">

**Comment by YunaiV** [comment]
使用最新的代码
