### ISSUE TITLE
导入IDEA DataPermissionUtilsTest文件包没有导入

### ISSUE THREAD

**Issue by gujiniCY** [YunaiV/ruoyi-vue-pro#279]
### 基本信息

- ruoyi-vue-pro 版本：https://gitee.com/zhijiantianya/ruoyi-vue-pro/tree/mini/
- 操作系统：Windows10
- 数据库：

### 复现步骤

我的JDK版本是jdk1.8.0_341，Maven 3.6.2.

我以查看文档中执行`mvn clean install package '-Dmaven.test.skip=true'` IDEA中执行成功

启动还是报类不存在？

可能是 IDEA 的 bug，点击 [File -> Invalidate Caches] 菜单，清空下缓存，重启后在试试看。

同时我也有清理缓存，重启IDEA

### 报错信息

![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/27911820/d3dba710-16fa-40ca-b40c-bb3b93dd66be)

**Comment by gujiniCY** [comment]
我把所有报错的test包都删除掉可以启动

**Comment by YunaiV** [comment]
好的哈。先用 master 分支。
