### ISSUE TITLE
验证码滑块无法显示

### ISSUE THREAD

**Issue by xinpiaoyuanfang** [YunaiV/ruoyi-vue-pro#282]
基本信息
ruoyi-vue-pro 版本：1.7.3-snapshot
操作系统：windows
数据库：postgres
你猜测可能的原因
（必填）我花费了 2-4 小时自查，发现可能的原因是：服务端调 验证码 报错，另外我把所有的包名都改了，包括数据库数据里面调用的包名也都改了，服务正常启动了，数据库、redis配置都没有问题，不知道什么原因了

复现步骤
第一步，
启动服务端服务，表 QRTZ_CRON_TRIGGERS 无数据，启动时报了下面的错，应该不影响

第二步，
启动前端，npm run dev
第三步，
登陆无法显示出验证码图片
<img width="1766" alt="2ae6596968e2fcd0800d2fe9d1e9a7a" src="https://github.com/YunaiV/ruoyi-vue-pro/assets/38042291/18f701ff-6294-4679-b22b-324bf6a46338">

报错信息
带上必要的截图
<img width="1881" alt="375d7e00ea84093222d51575b17ee63" src="https://github.com/YunaiV/ruoyi-vue-pro/assets/38042291/3a98b325-ad30-4809-9088-74d718dcdf47">

**Comment by YunaiV** [comment]
本地无法复现，建议自查下。
