### ISSUE TITLE
pg版本sql 有一些bug，目前发现 system_menu always字段类型错误，后续再更新

### ISSUE THREAD

**Issue by xinpiaoyuanfang** [YunaiV/ruoyi-vue-pro#283]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：1.7.3-snapshot
- 操作系统：win11
- 数据库：postgres

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：system_menu always字段类型错误

### 复现步骤

第一步，前端更新菜单，报错

### 报错信息

带上必要的截图
![656dd5020089a7b633ca42d1a080670](https://github.com/YunaiV/ruoyi-vue-pro/assets/38042291/9e996036-bd69-4733-b120-3437b2256646)
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/38042291/c634d216-4951-4de4-ba89-70f7503d7065)

![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/38042291/3ef85b67-a464-4d6b-b7ea-1e7deaff8d67)

**Comment by xinpiaoyuanfang** [comment]
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/38042291/2b889006-c0fd-4b02-8942-2f1517af852f)
system_notify_message 这张表什么问题？？

**Comment by YunaiV** [comment]
已经修复。
