### ISSUE TITLE
vue2管理后台用户的性别直接显示字典值

### ISSUE THREAD

**Issue by isljsy** [YunaiV/ruoyi-vue-pro#285]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：master
- 操作系统：windows 11
- 数据库：mysql

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：systemsers.sex 是 tinyint 类，而字典表system_dict_data.value是varchar类，elementui的选择器不认为0="0"，所以不匹配字典，显示0

### 复现步骤

第一步，系统管理 -> 用户管理 -> 修改

第二步，

第三步，

### 报错信息

带上必要的截图

![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/55614027/f522a079-de5c-4185-ab6c-8f24caaa504b)

**Comment by 1135004584** [comment]
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/30108520/c9750691-73de-4837-b3e8-427b3046dea3)

应该是脏数据，性别字典没有0

**Comment by 1135004584** [comment]
@isljsy isljsy

**Comment by YunaiV** [comment]
需要 parseInt 下哈。
