### ISSUE TITLE
短信模板更改，增添出错

### ISSUE THREAD

**Issue by uu88s** [YunaiV/ruoyi-vue-pro#290]
![cc523e4f2bd5074b3b733716fd654fb](https://github.com/YunaiV/ruoyi-vue-pro/assets/90900461/c470cc92-a417-45b3-8ab2-3fa1bc75b3bd)
![a6df9eaa428b6fbf03abe9092754c4e](https://github.com/YunaiV/ruoyi-vue-pro/assets/90900461/0738f8bc-aaaf-4c46-bf51-d48f38bfce81)

**Comment by coder-cuizw** [comment]
应该是前端vue3版本调用的问题吧，这个报错才是说明了原因
<img width="1403" alt="image" src="https://github.com/YunaiV/ruoyi-vue-pro/assets/44410149/3d434997-841b-4e12-a643-ef48767aded6">

**Comment by YunaiV** [comment]
已修复
