### ISSUE TITLE
YudaoJacksonAutoConfiguration 使 @JsonFormat 失效

### ISSUE THREAD

**Issue by muze-xu** [YunaiV/ruoyi-vue-pro#291]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：v1.7.3
- 操作系统：win11
- 数据库：mysql

### 你猜测可能的原因
从vo返回给前端的时候想以 "yyyy-MM-dd HH:mm:ss" 但是 加了 注解 @JsonFormat(pattern = FORMAT_YEAR_MONTH_DAY_HOUR_MINUTE_SECOND, timezone = TIME_ZONE_DEFAULT) 返回仍然是时间戳
（必填）我花费了 2-4 小时自查，发现可能的原因是：YudaoJacksonAutoConfiguration 配置注释调就好了，希望能优化可用使用 JsonFormat

### 复现步骤

第一步，

第二步，

第三步，

### 报错信息

带上必要的截图

**Comment by superwuman** [comment]
我也遇到这个问题了，请问你是怎么解决的

**Comment by YunaiV** [comment]
https://doc.iocoder.cn/validator/#_5-1-query-%E6%97%B6%E9%97%B4%E4%BC%A0%E5%8F%82
