### ISSUE TITLE
【Q3 或 Q4 支持】消息中间件换成rabbitmq或rocketmq

### ISSUE THREAD

**Issue by 491134648** [YunaiV/ruoyi-vue-pro#294]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：
- 操作系统：
- 数据库：

### 你猜测可能的原因
有些环境消息中间件已经有相关方案了，能否提供其他消息中间件的集成方案
（必填）我花费了 2-4 小时自查，发现可能的原因是：xxxxxx

### 复现步骤

第一步，

第二步，

第三步，

### 报错信息

带上必要的截图

**Comment by YunaiV** [comment]
不错的建议。

Q3 或者 Q4 会开启这块的改造。

**Comment by YunaiV** [comment]
为什么要改造消息队列？
① 对于 boot 项目来说，一般情况下，用不到 MQ。
② 对于 cloud 项目来说，一方面可能和 boot 一样不需要 MQ，一方面 spring cloud stream、bus 学习成本太高。

MQ 改造的想法：
① boot 项目，支持 redis stream 和 rocketmq 作为消息队列，默认不启用，按需开启。
② cloud 项目，干掉 spring cloud stream 和 bus。然后，和 boot 项目保持一致，基于 redis stream 和 rocketmq 两种。

因为默认不开启 MQ 消息队列，有两块要改造：
① 内存缓存：全部使用 Redis 缓存替代。
② 短信、邮件发送：使用 Spring Event 事件“异步”订阅替代。如果有需要，文档提供改造 MQ 的说明。

**Comment by YunaiV** [comment]
已支持：
https://doc.iocoder.cn/message-queue/event/
https://doc.iocoder.cn/message-queue/redis/
https://doc.iocoder.cn/message-queue/rocketmq/
https://doc.iocoder.cn/message-queue/rabbitmq/
https://doc.iocoder.cn/message-queue/kafka/
