### ISSUE TITLE
PAY_NOTIFY_LOCK问题

### ISSUE THREAD

**Issue by isyunketu** [YunaiV/ruoyi-vue-pro#295]
RedisKeyDefine PAY_NOTIFY_LOCK = new RedisKeyDefine("通知任务的分布式锁",
            "pay_notify:lock:", // 参数来自 DefaultLockKeyBuilder 类
            RedisKeyDefine.KeyTypeEnum.HASH, RLock.class, RedisKeyDefine.TimeoutTypeEnum.DYNAMIC); // Redisson 的 Lock 锁，使用 Hash 数据结构

return String.format(PAY_NOTIFY_LOCK.getKeyTemplate(), id);

问题："pay_notify:lock:"是不是写错了，String.format没有效果，而且锁的力度过大。

**Comment by YunaiV** [comment]
已修复，= = 少了一个 %s
最近写单测，被我抓到了。
