### ISSUE TITLE
项目中get请求，后端以对象接收，swagger页面中请求页面显示请求参数为一个json，希望请求参数是对象里面的每个属性，请问应该怎么设置？

### ISSUE THREAD

**Issue by LiXinnnnnn** [YunaiV/ruoyi-vue-pro#296]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：1.7.2
- 操作系统：win11
- 数据库：mysql

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：没找到问题原因

### 复现步骤

目前系统swagger中的问题是，以获取用户分页接口为例子，点击后请求地址为/user/page?reqVo={"pageNo":1,"pageSize":1 }
希望展示效果  /user/page?pageNo=1&pageSize=1

### 报错信息

带上必要的截图

![pic](https://github.com/YunaiV/ruoyi-vue-pro/assets/22066942/42956266-8ece-4dc8-99ce-d4ce695dabbc)

**Comment by 1135004584** [comment]
添加@RequestBody标记。。。

**Comment by LiXinnnnnn** [comment]
已搜到解决了，忘记关闭了，谢谢

**Comment by zhang4543** [comment]
请问如何解决的?加了@requestbody标记会报错,是不是需要把代码改成接收json字符串然后,在转换成对象?
