### ISSUE TITLE
字典内元素的关闭不起作用，实际还是会显示出来

### ISSUE THREAD

**Issue by 666wwx** [YunaiV/ruoyi-vue-pro#300]

**Comment by 1135004584** [comment]
什么意思，能描述的更加详细点吗

**Comment by 1135004584** [comment]
@666wwx

**Comment by 1135004584** [comment]
调用接口的时候加上status=1就可以排除掉关闭的元素了
http://localhost:48080/admin-api/system/dict-data/page?pageNo=1&pageSize=10&dictType=system_user_sex&status=1

![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/30108520/ae2bcee9-41a7-4c06-b03e-756b91fbbc0c)

**Comment by 666wwx** [comment]
请问，前端调用地址是在那个位置，还有这个可以针对特定的角色不展示吗

**Comment by 666wwx** [comment]
就是你描述的问题，但我不清楚在那个位置修改，具体那个文件
