### ISSUE TITLE
【欢迎贡献】关于菜单管理中能不能再设置菜单时，可以添加参数。建议参照ruoyi官方版本

### ISSUE THREAD

**Issue by tequilawu** [YunaiV/ruoyi-vue-pro#303]
ruoyi官方版本的菜单管理：
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/21970305/0ed62f76-8aa0-432b-8026-634f968f66d2)

ruoyi pro版本的菜单管理：
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/21970305/8a545381-2fb5-4cd7-b3f7-96a2b71a9441)

还望可以纳入开发计划

**Comment by tequilawu** [comment]
或者是在yudao中是否有地方可以配置这个路由参数呢？

**Comment by tequilawu** [comment]
@zivyuan

**Comment by YunaiV** [comment]
不错的建议，有没同学有兴趣贡献下？

**Comment by xiaoxinxing66** [comment]
同样发现了这个问题。。。我看看好做吗，争取贡献一下

**Comment by YunaiV** [comment]
Vue3 已支持 https://gitee.com/yudaocode/yudao-ui-admin-vue3/commit/f75e8d1fd450b975aa8d3e60738ccf917eb8dfa3
