### ISSUE TITLE
整合最新的支付模块后，后台不停的打印“缓存支付渠道...”

### ISSUE THREAD

**Issue by Colin07** [YunaiV/ruoyi-vue-pro#307]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：
- 操作系统：
- 数据库：

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：可能是哪里定时器加了这个

### 复现步骤

第一步，
启动项目后，后台直接打印

### 报错信息

带上必要的截图
![QQ图片20230720110439](https://github.com/YunaiV/ruoyi-vue-pro/assets/30275465/144a358b-4e1f-4b11-8484-df71640156c6)

**Comment by dengwenwen** [comment]
/**
     * 通过定时任务轮询，刷新缓存
     *
     * 目的：多节点部署时，通过轮询”通知“所有节点，进行刷新
     */
    @Scheduled(initialDelay = 60, fixedRate = 60, timeUnit = TimeUnit.SECONDS)
    public void refreshLocalCache() {
        // 注意：忽略自动多租户，因为要全局初始化缓存
        TenantUtils.executeIgnore(() -> {
            // 情况一：如果缓存里没有数据，则直接刷新缓存
            if (CollUtil.isEmpty(channelCache)) {
                initLocalCache();
                return;
            }

            // 情况二，如果缓存里数据，则通过 updateTime 判断是否有数据变更，有变更则刷新缓存
            LocalDateTime maxTime = CollectionUtils.getMaxValue(channelCache, PayChannelDO::getUpdateTime);
            if (channelMapper.selectCountByUpdateTimeGt(maxTime) > 0) {
                initLocalCache();
            }
        });
    }

**Comment by YunaiV** [comment]
正常情况。可以选择自己关闭 pay 模块，或者删除 logger 打印。
