### ISSUE TITLE
最新代码在Jrebel下无法启动

### ISSUE THREAD

**Issue by Colin07** [YunaiV/ruoyi-vue-pro#309]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息
最新的代码，不使用Jrebel可以正常启动，使用Jrebel启动时候报错，报依赖对象注入失败
- ruoyi-vue-pro 版本：
- 操作系统：
- 数据库：

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：不清楚

### 复现步骤

第一步，
使用Jrebel启动项目

### 报错信息

带上必要的截图

![QQ图片20230720220237](https://github.com/YunaiV/ruoyi-vue-pro/assets/30275465/8718bc36-f068-44cd-bd9f-ab1e59d24144)

**Comment by YunaiV** [comment]
暂时没碰到，建议自查下哈。
