### ISSUE TITLE
可以把初始化sql文件中的菜单数据分拆出来吗？

### ISSUE THREAD

**Issue by gujiniCY** [YunaiV/ruoyi-vue-pro#312]
### 基本信息

- ruoyi-vue-pro 版本：最新master分支
- 操作系统：
- 数据库：

### 你猜测可能的原因

现在mini分支很久没有同步代码了

初始化SQL中菜单表有很多的菜单用不上，比如商城，公众号等。

可能能使用到的就系统管理，基础设施。初始化系统的时候得把菜单都删掉。

**Comment by YunaiV** [comment]
建议手动处理哈。

太多 sql 维护不过来噢。
