### ISSUE TITLE
【欢迎贡献】微信支付初始化 client 客户端错误，导致发起支付报错，错误码：CUSTOM_ERROR，错误提示：v3请求构造异常！

### ISSUE THREAD

**Issue by 52Lau** [YunaiV/ruoyi-vue-pro#319]
### 基本信息

- ruoyi-vue-pro 版本：1.8
- 操作系统：mac
- 数据库：mysql8.0

### 你猜测可能的原因

参数错误，实际为证书错误

微信小程序支付，下单后，发起支付报错，错误码：CUSTOM_ERROR，错误提示：v3请求构造异常！
实际还有个报错原因没有打印，完善代码如下
`static String getErrorMessage(WxPayException e) {
        StringBuilder errorMessage = new StringBuilder();
        if (StrUtil.isNotEmpty(e.getErrCode())) {
            errorMessage.append(e.getErrCodeDes());
        }
        if (StrUtil.isNotEmpty(e.getCustomErrorMsg())) {
            errorMessage.append(e.getCustomErrorMsg());
        }
        if(e.getCause()!=null&&e.getCause().getMessage()!=null){
            errorMessage.append(e.getCause().getMessage());
        }
        return errorMessage.toString();
    }`

然后对比历史版本，发现客户端初始化的时候是copyProperties的，对比下来，发现多了"keyContent","privateKeyContent","privateCertContent"这三个，所以要忽略
<img width="970" alt="image" src="https://github.com/YunaiV/ruoyi-vue-pro/assets/37538641/476aa206-fe8d-4393-9be6-e37ae12d7967">
<img width="1202" alt="image" src="https://github.com/YunaiV/ruoyi-vue-pro/assets/37538641/877b8c16-04b0-48be-9cf7-936e15db7380">

**Comment by YunaiV** [comment]
好的噢，有兴趣 pr 下哇？

**Comment by momo-big** [comment]
我也是刚刚发现这个bug，然后想着来提bug，结果发现已经有大佬提出来了，早知道过来看看也就不用浪费我一个早上的时间了

**Comment by YunaiV** [comment]
已经修复。
