### ISSUE TITLE
【欢迎贡献】支付手续费计算不正确，超过付款金额

### ISSUE THREAD

**Issue by 52Lau** [YunaiV/ruoyi-vue-pro#320]
<img width="637" alt="image" src="https://github.com/YunaiV/ruoyi-vue-pro/assets/37538641/d9849d93-d5b2-4f76-b224-f6cdfaf570ac">
<img width="743" alt="image" src="https://github.com/YunaiV/ruoyi-vue-pro/assets/37538641/3a33f232-2fff-48c4-8dae-5ceae4526fa8">

**Comment by YunaiV** [comment]
额。。bug 了

你填的手续费比例是多少？

**Comment by 52Lau** [comment]
填的2，页面上单位是%，另外支付相关的几个表中channel_notify_data字段，长度超长

**Comment by YunaiV** [comment]
感谢修复。
