### ISSUE TITLE
文档错误

### ISSUE THREAD

**Issue by BaLaLaLs** [YunaiV/ruoyi-vue-pro#327]
### 基本信息
在商城手册页面 第二步 
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/23353559/60924542-2501-4956-aedb-cc2948d78fa4)

### 你猜测可能的原因
yudao-module-mp 是微信公众号模块而非商城模块。

**Comment by YunaiV** [comment]
已修复，谢谢。
