### ISSUE TITLE
【欢迎贡献】微信公众号菜单添加跳转小程序失败

### ISSUE THREAD

**Issue by 52Lau** [YunaiV/ruoyi-vue-pro#330]
微信公众号菜单添加跳转小程序失败，修复如下

<img width="906" alt="image" src="https://github.com/YunaiV/ruoyi-vue-pro/assets/37538641/24a37c2c-d5d7-4ebc-aad5-3b243c5a16d0">

**Comment by YunaiV** [comment]
可以 pr 贡献下哈。

**Comment by freesme** [comment]
@YunaiV 已根据 @52Lau  提供的方式提交，未进行功能验证

**Comment by YunaiV** [comment]
已修复。感谢
