### ISSUE TITLE
boot3-dev分支代码未同步问题

### ISSUE THREAD

**Issue by zwingf** [YunaiV/ruoyi-vue-pro#336]
### 基本信息

- ruoyi-vue-pro 版本： 最新boot3-dev分支
- 操作系统：Windows10
- 数据库：MySQL

### 你猜测可能的原因

有7月26号feature分支修改了登录菜单获取方式,未同步到boot3-dev分支

### 复现步骤

使用vue3前端后台登录,菜单获取方式被合并到登录接口中,最新boot3-dev分支未同步该改动

### 报错信息

![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/27192846/fdf6afb6-7023-45ec-bf20-1017f0ab35ea)

**Comment by YunaiV** [comment]
暂时没精力哈，等 Q4 在搞 boot3
