### ISSUE TITLE
支付模块定时任务找不到客户端

### ISSUE THREAD

**Issue by 52Lau** [YunaiV/ruoyi-vue-pro#338]
[getPayClient][渠道编号(2) 找不到客户端]
[cradle-admin]2023-09-03 23:20:00.055 [quartzScheduler_Worker-6] ERROR [] c.c.p.s.order.PayOrderServiceImpl 537 expireOrder - [expireOrder][渠道编号(2) 找不到对应的支付客户端]

在支付应用删除之后，对应的渠道没有删除，定时任务仍然会执行

**Comment by YunaiV** [comment]
建议数据都跑完后,在删除 = =
