### ISSUE TITLE
项目偶发http code返回426,response 显示Upgrade Required

### ISSUE THREAD

**Issue by harley2011** [YunaiV/ruoyi-vue-pro#341]
### 基本信息

- ruoyi-vue-pro 版本：1.8.0-snapshot
- 操作系统：Mac 
- 数据库：MYSQL5.7.42

### 你猜测可能的原因

我花费了 2-4 小时自查，发现可能的原因是：目前没有发现，之前项目刚建起来，有偶发碰到过，后面未发现，今天是跑着跑着出现426，猜测可能是因为jar包版本冲突

### 复现步骤

第一步，

第二步，

第三步，

### 报错信息

curl --location --request POST 'http://127.0.0.1:48080/app-api/shoppingcar/offUseCar' \
--header 'tenant-id: 1' \
--header 'Authorization: Bearer 737c96ccf8644d23b314fbbe9cadf151' \
--header 'User-Agent: Apifox/1.0.0 (https://apifox.com)' \
--header 'Accept: */*' \
--header 'Host: 127.0.0.1:48080' \
--header 'Connection: keep-alive'

<img width="1047" alt="image" src="https://github.com/YunaiV/ruoyi-vue-pro/assets/4181768/416eea38-2743-40f9-b8f6-049225a57a6a">

**Comment by YunaiV** [comment]
应该是本地环境问题，建议自查。

**Comment by GirHubCom** [comment]
请问下怎么解决的呢

**Comment by YunaiV** [comment]
lsof -i:48080

把本地占用的服务 kill 吊，然后重启下后端服务，即可
