### ISSUE TITLE
【欢迎贡献】支付异步通知问题

### ISSUE THREAD

**Issue by putiyang** [YunaiV/ruoyi-vue-pro#350]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：1.8.1-snapshot
- 操作系统：win10
- 数据库：mysql 8.0

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：支付异步回调并发问题,异步回调成功后PayNotifyTaskDO 的状态修改为SUCCESS后,第二次执行通知状态改为REQUEST_SUCCESS

### 复现步骤

第一步，

第二步，

第三步，

### 报错信息

带上必要的截图
![1695635407458](https://github.com/YunaiV/ruoyi-vue-pro/assets/43053326/ba4f1ce0-5e7a-48d2-87dc-30c31ff4ee85)

**Comment by YunaiV** [comment]
收到，我看看怎么解。

**Comment by YunaiV** [comment]
这个应该已经修复，可以在观测下
