### ISSUE TITLE
Knife4j 文档增加分组不显示

### ISSUE THREAD

**Issue by xfn-jjw** [YunaiV/ruoyi-vue-pro#351]
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/85837341/7b4c36e2-b391-4a0c-b1ba-da4609be3854)
新增接口分组 Knife4j 文档地址中不显示，是需要什么其他配置吗
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/85837341/334782e0-7400-4206-b2b5-10bd9352822c)

**Comment by YunaiV** [comment]
没问题，看看是不是没创建这个 bean 哈。
