### ISSUE TITLE
分离校验逻辑与DB写入逻辑是否更合适？

### ISSUE THREAD

**Issue by PansonPanson** [YunaiV/ruoyi-vue-pro#355]
### 基本信息

- ruoyi-vue-pro 版本：v1.8.2
- 操作系统：MacOS
- 数据库：MySQL

### 你猜测可能的原因

最近在看权限相关的逻辑，发现【管理后台 - 认证】的【使用账号密码登录】[登录接口](https://github.com/YunaiV/ruoyi-vue-pro/blob/82545ddaacac1d7c7c01a5da9df005e9b8c3b759/yudao-module-system/yudao-module-system-biz/src/main/java/cn/iocoder/yudao/module/system/controller/admin/auth/AuthController.java#L66)的校验逻辑，校验逻辑和DB写入逻辑放在同一个方法里面，按照单一职责原则，分离校验逻辑与DB写入逻辑是否更合适？
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/16064908/52be0fe4-08ee-40a5-b6ff-7d58d8607a11)
### 复现步骤

第一步，

第二步，

第三步，

### 报错信息

带上必要的截图

**Comment by YunaiV** [comment]
可以分离，但是也可以不分离。
