### ISSUE TITLE
redis连接问题

### ISSUE THREAD

**Issue by blueuuufish** [YunaiV/ruoyi-vue-pro#359]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：
- 操作系统：
- 数据库：redis

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：配置文件的格式不对，当我连接ali服务器的redis会自动连接到本地的

### 复现步骤

第一步，

第二步，

第三步，

### 报错信息

带上必要的截图
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/123882636/3303b08d-6ef7-4908-83de-7d82363dc0d7)
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/123882636/f53a1c16-8955-4379-99ca-c9a081105f9f)

![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/123882636/11dc11e2-9c7f-4e87-9dd0-906a4161c9a1)

**Comment by YunaiV** [comment]
看看 profile 是不是没设置对。
