### ISSUE TITLE
代码生成中，int识别成了日期

### ISSUE THREAD

**Issue by l523402485** [YunaiV/ruoyi-vue-pro#360]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：1.8.2
- 操作系统：win10
- 数据库：mysql

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：xxxxxx

### 复现步骤

第一步，

第二步，

第三步，

### 报错信息

带上必要的截图
![QQ截图20231020162754](https://github.com/YunaiV/ruoyi-vue-pro/assets/35321032/8de51fb3-5e63-49e1-85a3-243b645b98a0)
![QQ截图20231020163142](https://github.com/YunaiV/ruoyi-vue-pro/assets/35321032/a43a3002-9f93-4c7e-bcd1-c73240585b6e)

**Comment by YunaiV** [comment]
发下原始的 sql 看看哈。

**Comment by YunaiV** [comment]
由于长期没有回复，暂时关闭该 issue
