### ISSUE TITLE
点击页面顶部的面包屑中的链接，出现404页面

### ISSUE THREAD

**Issue by husted88** [YunaiV/ruoyi-vue-pro#362]
点击页面顶部的面包屑中的链接，出现404页面，如下图
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/39751426/86df41d6-b018-4a92-9cc2-fedc3bb00f9f)

![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/39751426/20f97b00-0302-44d5-b124-6f0d1743d05a)

**Comment by YunaiV** [comment]
好的，可以考虑使用 Vue3 版本。
