### ISSUE TITLE
postgresql的sql文件不是最新的

### ISSUE THREAD

**Issue by caobo0824** [YunaiV/ruoyi-vue-pro#363]
- ruoyi-vue-pro 版本：最新版
- 操作系统：win10/linux
- 数据库：postgresql

### 你猜测可能的原因

postgresql不是最新的

### 复现步骤
postgresql

### 报错信息
字段不存在
带上必要的截图
后端查询报错

**Comment by YunaiV** [comment]
好的，11 月会补齐下。
