### ISSUE TITLE
报错,系统异常

### ISSUE THREAD

**Issue by shenxiaobei** [YunaiV/ruoyi-vue-pro#366]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

最新

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：图形验证码获取不到

### 复现步骤

第一步，使用文档搭建完毕后,访问web看到的

第二步，

第三步，

### 报错信息

带上必要的截图
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/101985304/184e589d-90a0-4281-a97f-d2ddb2ea7372)

**Comment by YunaiV** [comment]
看看后端是不是没启动。
