### ISSUE TITLE
[技术] 有没有考虑把错误码 改为 枚举 然后继承接口ErrorCode (把 ErrorCode 也改成接口)

### ISSUE THREAD

**Issue by Lemon-cc-hang** [YunaiV/ruoyi-vue-pro#368]
例如:
<img width="514" alt="image" src="https://github.com/YunaiV/ruoyi-vue-pro/assets/62475939/9084508a-cece-4efa-a5b9-937099402abd">

<img width="924" alt="image" src="https://github.com/YunaiV/ruoyi-vue-pro/assets/62475939/5bfab507-8175-4acd-91c1-df279948c837">

可以更直观的看到 错误码和对应的错误信息, 也更好维护 可以在 ErrorCode 中直接找到继承于 它的 枚举 而且也是可以直接兼容之前的写法的

**Comment by Lemon-cc-hang** [comment]
<img width="796" alt="image" src="https://github.com/YunaiV/ruoyi-vue-pro/assets/62475939/318b6b60-d61b-41ec-ac12-8791974bb4ca">

<img width="778" alt="image" src="https://github.com/YunaiV/ruoyi-vue-pro/assets/62475939/e984d0e7-7c53-4aca-87fe-354db6989c17">

上面的一张图好像出不来, 补充一下

**Comment by zsf513** [comment]
> 例如: <img alt="image" width="514" src="https://user-images.githubusercontent.com/62475939/280908431-9084508a-cece-4efa-a5b9-937099402abd.png">
> <img alt="image" width="924" src="https://user-images.githubusercontent.com/62475939/280908796-5bfab507-8175-4acd-91c1-df279948c837.png">
> 
> 可以更直观的看到 错误码和对应的错误信息, 也更好维护 可以在 ErrorCode 中直接找到继承于 它的 枚举 而且也是可以直接兼容之前的写法的

是的，这样做确实很直观好维护。目前我的项目就是这样处理的

**Comment by YunaiV** [comment]
蛮好的，我之前搞过。
不过有点忘记，为啥后来放弃了这种 = = 

项目就暂时不改了，收益还暂时不太大。
