### ISSUE TITLE
一键改包时没有考虑到当artifactId包含符号时的情况

### ISSUE THREAD

**Issue by Umenezumi** [YunaiV/ruoyi-vue-pro#369]
### 基本信息

- ruoyi-vue-pro 版本：1.8.3

### 你猜测可能的原因

如果配置的 artifactId 为 xxx-platform （存在符号）则生成的代码不可用

![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/64912137/d96e3db9-0774-4430-8b34-159f7c55b6fc)

##

**Comment by YunaiV** [comment]
好的，先暂时不要加哈。
