### ISSUE TITLE
MYSQL数据库 SQL文件不全

### ISSUE THREAD

**Issue by leilei0220** [YunaiV/ruoyi-vue-pro#371]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：
- 操作系统：
- 数据库：

### 你猜测可能的原因

找了 RELESE   微服务 非微服务最新的包，都无完整SQL文件

### 复现步骤

第一步，

第二步，

第三步，

### 报错信息

![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/52106167/874b0398-89ee-4180-9726-b157045c48e7)

**Comment by leilei0220** [comment]
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/52106167/77618267-3a57-46b5-ad67-260c0d24babe)
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/52106167/da1ce17e-e669-4838-bff4-6fdcfa4c7684)

**Comment by leilei0220** [comment]
mp前缀开头表，以及商城模块下所有的表都没有喃

**Comment by AnisJiang** [comment]
估计得加入知识星球才能拿到sql文件吧

**Comment by zz530267002** [comment]
要加知识星球才能拿得到，199块

**Comment by leilei0220** [comment]
ok，要加入星球

**Comment by liyujiang-gzu** [comment]
> 要加知识星球才能拿得到，199块

 扩展功能的SQL作为增值服务收费可以理解，但至少要在README中提一下，不然都会以为是作者忘记加入代码库了。
