### ISSUE TITLE
三方登录菜单和页面现在是去掉了吗

### ISSUE THREAD

**Issue by weimin768** [YunaiV/ruoyi-vue-pro#373]
![菜单-三方应用](https://github.com/YunaiV/ruoyi-vue-pro/assets/8459160/d55c5785-06d2-49d2-bece-7b580287ab53)
![菜单-三方用户](https://github.com/YunaiV/ruoyi-vue-pro/assets/8459160/3ec662fc-021e-4c1f-b1ec-5c1e21723c1b)
在开发指南中，三方登录里面有三方登应用和三方用户这两个页面，在当前的版本中找不到页面了，另外，mysql的脚本中也没有这两个页面的的菜单配置项了，请问现在是去掉了吗，现在还支持数据库的方式配置三方登录吗

**Comment by YunaiV** [comment]
导入下最新 SQL，已经有了噢。
