### ISSUE TITLE
状态码定义不方便记忆问题

### ISSUE THREAD

**Issue by zsf513** [YunaiV/ruoyi-vue-pro#374]
目前的状态码都是数字类型，全局错误码使用0-999，业务错误码一共10 位数字，而且分成 4 段。如果业务过多，不便于记忆辨识。建议做成以下方式，更利于辨识：
1、错误码使用字符串类型；
2、全局错误码使用gbl_前缀然后拼接0-999;
3、业务错误码使用具体的业务前缀，例如system模块的业务使用sys_开头，pay模块使用pay_开头，sms模块使用sms_开头......

如果接口报错，根据错误码第一眼就能定位到是哪个模块的错误

**Comment by YunaiV** [comment]
不错的建议。目前主流还是以数字为主，所以暂时没考虑这种方式。

可以根据自己业务改造哈。
