### ISSUE TITLE
master-boot3 启动报错  Factory method 'filterChain' threw exception with message: This method cannot decide whether these patterns are Spring MVC patterns or not. If this endpoint is a Spring MVC endpoint, please use requestMatchers(MvcRequestMatcher); otherwise, please use requestMatchers(AntPathRequestMatcher).

### ISSUE THREAD

**Issue by luxx-lq** [YunaiV/ruoyi-vue-pro#375]
### 基本信息

- ruoyi-vue-pro 版本：1.8.3-snapshot
- 操作系统：win10
- 数据库：mysql

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：https://github.com/spring-projects/spring-security/issues/13568

### 复现步骤

启动报错

### 报错信息

![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/58515565/89e40a45-9b4c-4e87-8377-7fcf1fbe880e)

**Comment by YunaiV** [comment]
已修复
