### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by maioria** [YunaiV/ruoyi-vue-pro#377]
Annotation-specified bean name 'productCategoryController' for bean class [cn.iocoder.yudao.module.crm.controller.admin.productcategory.ProductCategoryController] conflicts with existing, non-compatible bean definition of same name and class [cn.iocoder.yudao.module.product.controller.admin.category.ProductCategoryController]

**Comment by YunaiV** [comment]
crm 暂时内测，不用打开噢。
