### ISSUE TITLE
你真的是打着开源的幌子，在那各种骗关注、拉群，收费，真的恶心

### ISSUE THREAD

**Issue by 6gunner** [YunaiV/ruoyi-vue-pro#382]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：
- 操作系统：
- 数据库：

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：xxxxxx

### 复现步骤

第一步，

第二步，

第三步，

### 报错信息

带上必要的截图

**Comment by tetsu-proton-me** [comment]
具体有什么收费的行为呢？

**Comment by Howietron** [comment]
老想白嫖，免费的才是最贵的，而且据我所知收费也只有知识星球收费吧

**Comment by 6gunner** [comment]
看个文档，先让关注公众号，关注完让点start，还得所有项目点；点完想看看文档又让加入星球，我拜托你能不能直接点说收费。

**Comment by XuanRanDev** [comment]
> 通过收费，也能够激励贡献者和维护者继续付出精力和时间。
芋道，以开发者为中心，打造中国第一流的快速开发平台，**全部开源**，个人与企业可 100% 免费使用。

如果做不到完全免费，就别在README里面扯什么_全部开源_、_完全免费_；同时也建议咱们赶快吧ruoyi-vue-pro中的这个ruoyi改掉吧，别让别人以为这是同一个作者出的东西。
