### ISSUE TITLE
工作流bug

### ISSUE THREAD

**Issue by jxyk2007** [YunaiV/ruoyi-vue-pro#389]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息
工作流在分配规则时，只有“用户分组”有效，其他的“角色”“部门成员”“自定义脚本”，都不行。
- ruoyi-vue-pro 版本：
- 操作系统：
- 数据库：

### 你猜测可能的原因

（必填）我花费了 24-72 小时自查，发现可能的原因是：未知

### 复现步骤

第一步，新建流程模型

第二步，任务分配规则，选择部门成员，或者选择角色，选择对应的角色组

第三步，发起流程

### 报错信息

带上必要的截图

**Comment by YunaiV** [comment]
测试了下，暂时没碰到这个问题，建议自查下哈。
