### ISSUE TITLE
Bug Report: 演示地址无法登陆

### ISSUE THREAD

**Issue by hsiong** [YunaiV/ruoyi-vue-pro#390]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：v1.8.3
- 操作系统：Mac OS 13.4.1 (c) / Windows 11 22H2
- 数据库：暂无

### 你猜测可能的原因

（必填）F12查看接口, 提示 502 Bad Gateway  异常, 我猜测可能是 nginx 等代理服务出现了问题, 或者域名解析出现了异常

### 复现步骤

第一步，访问以下网址
+ 演示地址【Vue3 + element-plus】：http://dashboard-vue3.yudao.iocoder.cn/
+ 演示地址【Vue3 + vben(ant-design-vue)】：http://dashboard-vben.yudao.iocoder.cn/
+ 演示地址【Vue2 + element-ui】：http://dashboard.yudao.iocoder.cn/

第二步，点击登录

### 报错信息
截图如下: 

![Screenshot 2023-12-22 at 14 58 43](https://github.com/YunaiV/ruoyi-vue-pro/assets/37357447/dd668f15-f9af-4a10-884c-ffc28d1f2a5f)

![Screenshot 2023-12-22 at 14 59 15](https://github.com/YunaiV/ruoyi-vue-pro/assets/37357447/9105c380-93ee-422a-8541-25dc1bb0b4b2)

![Screenshot 2023-12-22 at 14 59 35](https://github.com/YunaiV/ruoyi-vue-pro/assets/37357447/1f62c47b-920c-463a-8a0d-a69267e0cbf8)

**Comment by YunaiV** [comment]
阿里云不定期抖动，目前已经恢复
