### ISSUE TITLE
Mac apple silicon设备(M1/M2/M3)下项目启动报错，netty-resolver-dns-native-macos依赖不正确

### ISSUE THREAD

**Issue by ch1lam** [YunaiV/ruoyi-vue-pro#391]
### 基本信息

- ruoyi-vue-pro 版本：1.8.3
- cpu：M2 Pro
- 操作系统：Mac OS X 13.6.2
- 数据库：mysql 5.7

### 原因
redis的间接依赖中有一个netty-resolver-dns-native-macos依赖，依赖的默认版本是x86的，不支持arrch64。
在gitee找到相同问题——[Mac M1芯片启动报错](https://gitee.com/zhijiantianya/ruoyi-vue-pro/issues/I5EN5B)
怀疑是这个[commit](https://github.com/YunaiV/ruoyi-vue-pro/commit/436fef7efaaee88b3874c72c36f7488fac729dff)导致这个bug再次复现

### 复现步骤
在idea中直接启动

### 报错信息
```zsh
2023-12-26 10:56:25.236 | ERROR 75819 | main [TID: N/A] i.n.r.d.DnsServerAddressStreamProviders  
| Unable to load io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider, fallback to system defaults. This may result in incorrect DNS resolutions on MacOS. 
Check whether you have a dependency on 'io.netty:netty-resolver-dns-native-macos'. Use DEBUG level to see the full stack: java.lang.UnsatisfiedLinkError: failed to load the required native library
```
<img width="1679" alt="image" src="https://github.com/YunaiV/ruoyi-vue-pro/assets/39334548/5f8532e3-445c-4d62-8ea1-0584786cfb90">

#### 方法一

在`yudao-spring-boot-starter-redis`包中的`pom.xml`文件加上netty-all依赖

```xml
<dependency>
    <groupId>io.netty</groupId>
    <artifactId>netty-all</artifactId>
    <version>4.1.79.Final</version>
</dependency>
```

#### 方法二

修改`yudao-spring-boot-starter-redis`包中的`pom.xml`文件，通过`<scope>`标签控制运行与测试阶段指定arrch64版本的依赖

```xml
<dependency>
    <groupId>io.netty</groupId>
    <artifactId>netty-resolver-dns-native-macos</artifactId>
    <scope>runtime</scope>
    <classifier>osx-aarch_64</classifier>
</dependency>
```

#### 方法三

修改`yudao-spring-boot-starter-redis`包中的`pom.xml`文件，直接排除依赖，重新引入arrch64版本的依赖

```xml
<dependency>
    <groupId>org.redisson</groupId>
    <artifactId>redisson-spring-boot-starter</artifactId>
    <exclusions>
        <exclusion>
            <groupId>io.netty</groupId>
            <artifactId>netty-resolver-dns-native-macos</artifactId>
        </exclusion>
    </exclusions>
</dependency>

<dependency>
    <groupId>io.netty</groupId>
    <artifactId>netty-resolver-dns-native-macos</artifactId>
    <scope>runtime</scope>
    <classifier>osx-aarch_64</classifier>
</dependency>
```

#### 方法四

修改`yudao-spring-boot-starter-redis`包中的`pom.xml`文件，通过修改profile属性，在macos、aarch64架构下，运行与编译阶段使用arrch64的依赖包。**本人使用idea自带maven时，profile自动激活不生效，尚不清楚是否与idea的maven配置有关**

```xml
<profiles>
    <profile>
        <id>Apple Silicon</id>
        <activation>
            <os>
                <family>mac</family>
                <arch>aarch64</arch>
            </os>
        </activation>
        <!-- 解决apple silicon架构本地调试时出现版本错误的问题 -->
        <dependencies>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-resolver-dns-native-macos</artifactId>
                <scope>runtime</scope>
                <classifier>osx-aarch_64</classifier>
            </dependency>
        </dependencies>
    </profile>
</profiles>
```

<img width="1072" alt="image" src="https://github.com/YunaiV/ruoyi-vue-pro/assets/39334548/4f315df3-078f-4681-b497-5439e992018f">

**Comment by YunaiV** [comment]
不错的建议。你比较倾向那个方案？

**Comment by ch1lam** [comment]
> 不错的建议。你比较倾向那个方案？

方案四，理论上应该是比较完美的，开箱即用。但是由于profiles没有自动激活，导致目前要先勾上profiles配置。
出现问题有可能是我对idea的配置理解错误或者对maven profiles配置理解错误引起的。

**Comment by YunaiV** [comment]
理解。我其实有点纠结。

因为貌似不解决，也不影响功能的使用？

**Comment by ch1lam** [comment]
是的，这个问题的优先级不高，可以在之后有空再处理这类问题。

最后感谢作者和维护者的付出:)

**Comment by ldw4033** [comment]
![Xnip-20240126233852](https://github.com/YunaiV/ruoyi-vue-pro/assets/5718303/e46b99ed-9bab-4e2c-a7a3-73f67f432bcd) 我这里是可用的，使用的不是 idea 自带的maven

**Comment by ldw4033** [comment]
个人感觉方案一和方案四都可以

**Comment by ch1lam** [comment]
> 个人感觉方案一和方案四都可以
> 
> 方案一 不需要 版本号
> 
> ```
> <dependency>
>     <groupId>io.netty</groupId>
>     <artifactId>netty-all</artifactId>
> </dependency>
> ```

**方案一与[减少依赖的这个commit](https://github.com/YunaiV/ruoyi-vue-pro/commit/436fef7efaaee88b3874c72c36f7488fac729dff)有冲突，所以我认为要看作者的意思**

---

> ![Xnip-20240126233852](https://private-user-images.githubusercontent.com/5718303/300031792-e46b99ed-9bab-4e2c-a7a3-73f67f432bcd.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNDUxMDQsIm5iZiI6MTcwNjM0NDgwNCwicGF0aCI6Ii81NzE4MzAzLzMwMDAzMTc5Mi1lNDZiOTllZC05YmFiLTRlMmMtYTdhMy03M2Y2N2Y0MzJiY2QuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjdUMDg0MDA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzMwZmRmOGQ3MWE1OGRkZTA4NjczZjVlYmVlNjViMDUwMDU5Nzk5YmZlMDlhNjJjMjA3NTg4NjBmMGQ0OTcwZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kfGbJwYCtZ_3h0REk0SP4d7mkPFM5i1xkSOy8UNzpDQ) 我这里是可用的，使用的不是 idea 自带的maven

**如果取消勾选Apple Silicon的profile的情况下，执行`maven clean`、`maven reimport` 后启动项目是否仍有效呢？**

**Comment by YunaiV** [comment]
考虑了很久，由于只是 macos 的 m1 芯片会出现，并且不会有 bug，只是 warning 日志，所以先关闭该 issue
因为实际项目中，最终部署到 linux 或者 windows 服务器。

**Comment by YunaiV** [comment]
不引入 netty-all 的原因，还是希望 jar 尽量小一点哈。
