### ISSUE TITLE
application里配置验证码为false不生效

### ISSUE THREAD

**Issue by ZhangEnlin** [YunaiV/ruoyi-vue-pro#395]
### 基本信息

- ruoyi-vue-pro 版本：2.0.0-jdk8-snapshot
- 操作系统：Windows 11 专业版22H2 | 系统版本22621.2134
- 数据库：Windows版 MySQL 8.0.27

### 你猜测可能的原因

（必填）我花费了 1 小时自查，发现可能的原因是：我技术菜，不知道原因...但我可以描述一下我遇到的问题的大概情况：当`@Value("${yudao.captcha.enable:true}")`配置默认值之后，application配置文件中的验证码配置`yudao.captcha.enable`不生效，仅会使用@Value注解内的默认值，如果@Value注解中不配置默认值，则会使用application配置文件中的验证码配置。这两种情况都已经在我本地debug测试过；

### 复现步骤

第一步：根据官方文档配置前后端验证码开关为false

1. 配置`application.yaml`里的属性`spring.profiles.active= local`
2. 配置`application-local.yaml`里的属性`yudao.captcha.enable = false`
3. 配置前端项目`.env`文件内验证码开关为false:`VITE_APP_CAPTCHA_ENABLE=false`

第二步，
保持`yudao-module-system`module下文件`AdminAuthServiceImpl.java`内`captchaEnable`属性为以下默认代码

```java
@Value("${yudao.captcha.enable:true}")
private Boolean captchaEnable;
```

第三步，

 启动项目，登录系统，提示错误信息：<font color='red'>请求参数不正确:验证码不能为空</font>

### 报错信息

带上必要的截图
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/42036645/7a2995b4-0d20-4858-927e-933f8c6751b2)

**Comment by YunaiV** [comment]
测试了下，暂时没碰到这个问题哈，建议自查下。

**Comment by jiangjiang666666** [comment]
我这边也偶尔会出现这个问题，把验证码打开为true就行了

**Comment by x543754000** [comment]
我也出现这个问题了，# 验证码的开关
VITE_APP_CAPTCHA_ENABLE=true 不管用，不弹验证码   env.local 正常， env.dev 不管用

**Comment by YunaiV** [comment]
前后端要么都开启，要么都不开启哈。
