### ISSUE TITLE
目前两个分支 维护了两个jdk版本，分别是jdk21和jdk8，后期是简化成一个jdk版本，还是长期维护两个分支版本？

### ISSUE THREAD

**Issue by victory460** [YunaiV/ruoyi-vue-pro#398]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：yudao-boot-mini-master
- 操作系统：jdk1.8 springboot 2.7.17 rockmq 2.23
- 数据库：

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：xxxxxx

### 复现步骤

不清楚什么原因导致引入了jdk21？后期的规划方向是两个同时维护吗？

### 报错信息

带上必要的截图

**Comment by YunaiV** [comment]
长期都维护哈。
