### ISSUE TITLE
master-jdk21分支是不是不支持开启 yudao-module-report 模块?

### ISSUE THREAD

**Issue by semmywong** [YunaiV/ruoyi-vue-pro#399]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：
- 操作系统：
- 数据库：

### 报错信息

master-jdk21分支是不是不支持开启 yudao-module-report 模块?

**Comment by YunaiV** [comment]
已经支持。
