### ISSUE TITLE
mini版本中的jdk21分支，引入rabbitmq。程序无法启动无法创建bean实例

### ISSUE THREAD

**Issue by zzzzzyw** [YunaiV/ruoyi-vue-pro#411]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：mini
- 操作系统：windows11
- 数据库：mysql

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：rabbitmq发行版本问题。
将mq模块里面的 mq artifactId：spring-rabbit替换为
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/43313102/54843d54-5dd9-4009-855f-47be66cafc9b)

然后在config文件里面修改 @ConditionalOnClass(name = "org.springframework.amqp.core.RabbitTemplate")
就可以正常启动了
不知道原理
### 复现步骤

第一步，
放开mq模块的<optional>true</optional>
第二步，
在其他模块引入 mq模块
第三步，
启动报错无法创建bean
### 报错信息

带上必要的截图

**Comment by puhui999** [comment]
最新版本没有复现出此问题，要不拉新试试？

**Comment by YunaiV** [comment]
由于没有回复，该 issue 先关闭落，应该是个人环境问题

**Comment by helloxtf** [comment]
请问怎么解决的呢 我也遇到这个问题了

**Comment by helloxtf** [comment]
> 最新版本没有复现出此问题，要不拉新试试？

你好我也遇到同样的问题了 请问怎么解决的呢

**Comment by YunaiV** [comment]
@AutoConfiguration
@Slf4j
@ConditionalOnClass(name = "org.springframework.amqp.rabbit.core.RabbitTemplate")
public class YudaoRabbitMQAutoConfiguration {

    /**
     * Jackson2JsonMessageConverter Bean：使用 jackson 序列化消息
     */
    @Bean
    public MessageConverter createMessageConverter() {
        return new Jackson2JsonMessageConverter();
    }

}
