### ISSUE TITLE
snapshot版本号小写，导致被nexus私服识别为release库

### ISSUE THREAD

**Issue by dulio** [YunaiV/ruoyi-vue-pro#417]
### 基本信息

- ruoyi-vue-pro 版本：2.0.0
- Nexus版本：OSS 3.30.1-01

snapshot版本号小写，导致被nexus私服识别为release库，无法redeploy

强制上传snapshot库时，被nexus私服Version policy拦截上传

### 你猜测可能的原因

版本号为2.0.0-jdk8-snapshot

nexus里的snapshot库Version policy配置了Snapshot。但是发现该判断无法识别小写snapshot，必须为标准的2.0.0-jdk8-SNAPSHOT才行

### 复现步骤

给maven配置一个nexus私服地址，snapshot和release库分别配置Version policy为Snapshot和Release

`mvn clean deploy -Dmaven.test.skip=true -f pom.xml`

### 报错信息

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:3.1.1:deploy (default-deploy) on project yudao: Failed to deploy artifacts: Could not transfer artifact cn.iocoder.boot:yudao:pom:2.0.0-jdk8-snapshot from/to nexus-snapshots (https://xxxx.xxx.com/repository/snapshot): status code: 400, reason phrase: Repository version policy: SNAPSHOT does not allow version: 2.0.0-jdk8-snapshot (400) -> [Help 1]

**Comment by Ziyear** [comment]
https://community.sonatype.com/t/400-repository-version-policy-snapshot-does-not-allow-version-3-0-0/4053
不知道这个可不可以解决你的问题

**Comment by YunaiV** [comment]
我研究研究哈

**Comment by YunaiV** [comment]
看了下，应该会改成 SNAPSHOT。
预计是下一次发版

**Comment by dulio** [comment]
> 看了下，应该会改成 SNAPSHOT。 预计是下一次发版

谢谢大佬 :)
