### ISSUE TITLE
哥哥，crm合同相关功能大概啥时候能开发完

### ISSUE THREAD

**Issue by javaAjun** [YunaiV/ruoyi-vue-pro#420]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：
- 操作系统：
- 数据库：

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：xxxxxx

### 复现步骤

第一步，

第二步，

第三步，

### 报错信息

带上必要的截图

**Comment by javaAjun** [comment]
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/38597827/faea96d0-d5ac-4b86-944a-705d045cba1f)
选择不了工作流和商机，但是看你文档里面的截图能选

**Comment by linechengchen** [comment]
回回复你么  你看的是文档还是视频教程啊

**Comment by javaAjun** [comment]
> 回回复你么 你看的是文档还是视频教程啊

https://github.com/YunaiV/ruoyi-vue-pro/issues/420#issuecomment-1963287462

你们文档截图有这功能，但是实际代码里面没这功能

**Comment by linechengchen** [comment]
> > 回回复你么 你看的是文档还是视频教程啊
> 
> https://github.com/YunaiV/ruoyi-vue-pro/issues/420#issuecomment-1963287462
> 
> 你们文档截图有这功能，但是实际代码里面没这功能

我不知道，我在看erp的模块，我wx hdsrw888交流下
