### ISSUE TITLE
终于搞定了一个棘手问题——关于BPM工作流自定义上传控件无法预览的问题

### ISSUE THREAD

**Issue by benbenbaby09** [YunaiV/ruoyi-vue-pro#421]
### 基本信息

- ruoyi-vue-pro 版本：master
- 前端yudao-ui-admin-vue3：master
- 操作系统：windows
- 数据库：mysql8

### 你猜测可能的原因

终于搞定了一个棘手问题——关于BPM工作流自定义上传控件无法预览的问题
1、根据form-create组件排查，发现bpm模块的控件缺少了上传文件的回调函数定义（onSuccess），上传成功后不会赋值给预览图（图1），就会造成预览图无法显示
2、想给前端控件自动加上这个回调函数，因为我是主java，对这个组件不熟悉，但也尽量看他的代码和文档，还是没办法加上去，所以就想到了在后端来加。
3、在BpmFormServiceImpl.java类里面添加了一个updateUploadField方法，用于修改json，为了操作json方便，需要引入
<dependency>
    <groupId>com.alibaba</groupId>
    <artifactId>fastjson</artifactId>
    <version>2.0.31</version>
</dependency>
4、改完之后重新保存一下流程表单，并发起流程，数据表bpm_process_definition_ext中的form_fields字段就可以看到"props\":{\"action\":\"http://localhost:48080/admin-api/infra/file/upload\",\"onSuccess\":\"function(res, file) {console.log(res); file.url=res.data;}\"}这个数据值了，那么就表示成功了（console.log)是我方便调试的，可以去掉

### 复现步骤

第一步，
在流程管理中创建流程，拖入上传文件控件保存并发布。
第二步，
到任务管理-我的流程，发起流程，选择刚才发布的流程，上传一张图片文件，上传成功后预览图无法显示

### 报错信息
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/96015432/b74ec5d9-9c01-4ef1-bd37-da44ae9d2701)

带上必要的截图，解决思路相关截图
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/96015432/42178659-97d9-4def-a5e0-3843e766c54e)
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/96015432/015ac45c-7d00-4215-8fef-db44e32a3e16)
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/96015432/1203b29b-1fb7-4090-b18d-6483de484766)
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/96015432/7b2fa780-c488-45f1-ad06-89c68c896a9b)

**Comment by YunaiV** [comment]
不错不错，我最近会开始优化 bpm，这块我一起跟进下

**Comment by YunaiV** [comment]
合并到 https://gitee.com/yudaocode/yudao-ui-admin-vue3/issues/I783FH 一起跟进
