### ISSUE TITLE
无法正常启动后端项目（已查看开发文档且自行搜索解决未果）

### ISSUE THREAD

**Issue by Yolanda-Zeng** [YunaiV/ruoyi-vue-pro#423]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：最新代码
- 操作系统：win11
- 数据库：mysql

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：maven加载依赖项的问题或者是idea构建项目时存在的问题

### 复现步骤

第一步，启动项目报错

### 报错信息

带上必要的截图
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'diffParseFunction' defined in class path resource [com/mzt/logapi/starter/configuration/LogRecordProxyAutoConfiguration.class]: Unsatisfied dependency expressed through method 'diffParseFunction' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'diffItemsToLogContentService' defined in class path resource [com/mzt/logapi/starter/configuration/LogRecordProxyAutoConfiguration.class]: Post-processing of merged bean definition failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [com.mzt.logapi.starter.diff.DefaultDiffItemsToLogContentService] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@63947c6b]

![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/103943109/5e745e55-81e7-4bb0-94a3-e9af85d298cc)

![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/103943109/daf2412c-873a-457b-afb4-2c7cb3f6abac)

**Comment by YunaiV** [comment]
测试了下，暂时没碰到
建议在查询下哈。或者拉下最新代码~

**Comment by jfieji** [comment]
同样遇到该问题

**Comment by liyujiang-gzu** [comment]
看报错信息，目测是自己写的某些类问题，和这个框架无关

**Comment by sjzsp** [comment]
同样是遇到该问题，还没开始编写任何代码啊
