### ISSUE TITLE
开启crm 运行报错，java: 程序包org.springdoc.core.models不存在

### ISSUE THREAD

**Issue by arvinhan** [YunaiV/ruoyi-vue-pro#425]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：[yudao-vue-pro](https://gitee.com/zhijiantianya/ruoyi-vue-pro)
- 操作系统：win11
- 数据库：mysql

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：xxxxxx

### 复现步骤

第一步，

第二步，

第三步，

### 报错信息
开启crm 运行报错，java: 程序包org.springdoc.core.models不存在，已更新maven 
 
![7c782464a65e685ad60375af48d9e36](https://github.com/YunaiV/ruoyi-vue-pro/assets/31042264/054f6166-1274-4a38-8c7b-2738e5b3bac0)

**Comment by YunaiV** [comment]
拉下最新代码，这块已经修复。
