### ISSUE TITLE
crm新租户分配完权限后操作无权限

### ISSUE THREAD

**Issue by maioria** [YunaiV/ruoyi-vue-pro#428]
创建一个套餐  勾选crm下所有权限，新租户使用这个套餐，新租户登录后创建一个客户，点客户到详情页面，会有无权限的弹窗。
crm-2024-02-26.sql 这个文件下是否缺少了权限

crm/follow-up-record/page
{"code":403,"data":null,"msg":"没有该操作权限"}

**Comment by YunaiV** [comment]
合并到 https://github.com/YunaiV/ruoyi-vue-pro/issues/430 里面一起跟进
