### ISSUE TITLE
可以把docker镜像部署的脚本也加上吗？

### ISSUE THREAD

**Issue by superknight** [YunaiV/ruoyi-vue-pro#43]

**Comment by doterlin** [comment]
> 其实不用牵扯到jenkens，前后端分开docker打包，然后通过docker命令部署或者通过docker-compose.yaml整合也OK。毕竟jenkins太重了，已经很少用了

我也觉得，建议就留docker和k8s描述文件就行，具体执行环境应该不需要考虑，大家都不太一样

**Comment by YunaiV** [comment]
已经提供部署相关的文档

https://doc.iocoder.cn/dev-env/
