### ISSUE TITLE
新的租户，套餐包含支付的所有权限，租房登录创建完应用信息，进行支付配置时，提示无操作权限

### ISSUE THREAD

**Issue by maioria** [YunaiV/ruoyi-vue-pro#430]
http://localhost:48080/admin-api/pay/channel/get?appId=10&code=wx_lite
{"code":403,"data":null,"msg":"没有该操作权限"}

**Comment by Bennett-Q** [comment]
一样会有这种:"没有该操作权限"问题, 明明分配了, 你是怎么解决的?

**Comment by maioria** [comment]
暂时手动补的权限

**Comment by Bennett-Q** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by YunaiV** [comment]
@maioria 手动补的权限，指的是？
menu 少插入了一些么？

**Comment by YunaiV** [comment]
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/2015545/288907e2-8d5a-4272-a10c-9b71b529329f)

https://github.com/YunaiV/ruoyi-vue-pro/issues/428

合并跟进

**Comment by William-02-02** [comment]
> @maioria 手动补的权限，指的是？ menu 少插入了一些么？
应该是sql少了 搜不到 pay:channel:query相关的
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/63051334/50585213-478b-4e73-8f20-49169e26273c)

**Comment by Bennett-Q** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by William-02-02** [comment]
我目前发现这些 后续继续补充
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/63051334/ce6bd6e5-6aa7-41fc-8830-a55cd1dba352)

**Comment by YunaiV** [comment]
已修复。

**Comment by YunaiV** [comment]
public class BootCloudMenuMain {

    public static void main(String[] args) {
        MysqlDataSource dataSource = new MysqlDataSource();
        dataSource.setURL("jdbc:mysql://127.0.0.1:3306/ruoyi-vue-pro");
        dataSource.setUser("root");
        dataSource.setPassword("123456");
        dataSource.setDatabaseName("ruoyi-vue-pro");
        JdbcTemplate jdbcTemplate = new JdbcTemplate(dataSource);
        List<Map<String, Object>> maps = jdbcTemplate.queryForList("SELECT * FROM system_menu");
        Set<String> permissions = new HashSet<>();
        maps.forEach(stringObjectMap -> permissions.add((String) stringObjectMap.get("permission")));

        List<File> files = FileUtil.loopFiles("/Users/yunai/Java/ruoyi-vue-pro-jdk21");
        Set<String> miss = new HashSet<>();
        files.forEach(file -> {
            if (!file.getPath().contains("Controller.java")) {
                return;
            }
            List<String> strings = FileUtil.readLines(file, "utf-8");
            for (String string : strings) {
                string = StrUtil.subBetween(string, "hasPermission('", "'");
                if (StrUtil.isEmpty(string)) {
                    continue;
                }
                if (permissions.contains(string)) {
                    continue;
                }
                miss.add(file.getName() + ":" + string);
            }
        });

        for (String s : miss) {
            System.out.println(s);
        }
    }

}

一个建议的查询脚本。

大家处理这类问题，尽量通过自动化匹配解决
