### ISSUE TITLE
微信支付时，  无法保证，父线程 的 ThreadLocal 传入  子线程 

### ISSUE THREAD

**Issue by blank-empty** [YunaiV/ruoyi-vue-pro#432]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：2.0.1
- 操作系统：win11
- 数据库：mysql

### 你猜测可能的原因
在后台调启，新的线程是，没有设置  ThreadLocal  TENANT_ID 的值，导致，报错
        Executor executor = Executors.newCachedThreadPool(  // TODO 芋艿：可能要思考下，未来要不要做成可配置
            TtlExecutors.getDefaultDisableInheritableThreadFactory()); // TTL 保证 ThreadLocal 可以透传
            上述代码，无法保证  ThreadLocal 正常传递。
            下面的代码，我测试了，可以保证 ThreadLocal 正常传递。
        ExecutorService executorService = Executors.newCachedThreadPool();
        Executor executor = TtlExecutors.getTtlExecutorService(executorService);
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/73057148/a17094cf-bef8-46bc-aa14-470514833ade)

（必填）我花费了 2-4 小时自查，发现可能的原因是：在后台创建线程，运行任务，没有设置 tenantId 

### 复现步骤

第一步，微信支付

第二步，

第三步，

### 报错信息
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/73057148/834fc7e3-bc6c-4736-8f7c-06c215191867)
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/73057148/0d91f011-7471-4b49-8dbb-c21b801f85b6)

带上必要的截图

**Comment by YunaiV** [comment]
已修复，感谢！
