### ISSUE TITLE
快速启动报错

### ISSUE THREAD

**Issue by BigCity8193** [YunaiV/ruoyi-vue-pro#433]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：JDK 8 + Spring Boot 2.7.18
- 操作系统：windows10
- 数据库：mysql8.0

### 你猜测可能的原因

没有成功加入容器，导致找不到bean

### 复现步骤
按着官网启动项目，启动 system 系统服务，infra 基础设施两个模块。

### 报错信息

![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/45333040/6f8e6e2a-645f-4eb8-9028-278a8659848c)

**Comment by BigCity8193** [comment]
追加两个WARN：
No MyBatis mapper was found in '[cn.iocoder.yudao.server]' package. Please check your configuration.
Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'deptApiImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'deptServiceImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'cn.iocoder.yudao.module.system.dal.mysql.dept.DeptMapper' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@javax.annotation.Resource(shareable=true, lookup=, name=, description=, authenticationType=CONTAINER, type=class java.lang.Object, mappedName=)}

**Comment by BigCity8193** [comment]
1

**Comment by qq740427202** [comment]
> 碰到问题，请在 https://github.com/YunaiV/ruoyi-vue-pro/issues 搜索是否存在相似的 issue。
> 
> 不按照模板提交的 issue，会被系统自动删除。
> 
> ### 基本信息
> * ruoyi-vue-pro 版本：JDK 8 + Spring Boot 2.7.18
> * 操作系统：windows10
> * 数据库：mysql8.0
> 
> ### 你猜测可能的原因
> 没有成功加入容器，导致找不到bean
> 
> ### 复现步骤
> 按着官网启动项目，启动 system 系统服务，infra 基础设施两个模块。
> 
> ### 报错信息
> ![image](https://private-user-images.githubusercontent.com/45333040/310436852-6f8e6e2a-645f-4eb8-9028-278a8659848c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4Mjk3MDMsIm5iZiI6MTcwOTgyOTQwMywicGF0aCI6Ii80NTMzMzA0MC8zMTA0MzY4NTItNmY4ZTZlMmEtNjQ1Zi00ZWI4LTkwMjgtMjc4YTg2NTk4NDhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDE2MzY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiNzBhMDc2ZjNkOTkxZTI1MGI4YTJhOThhZTU3MmE2ZGNjMjU0M2NjYmI5NGM1MzU1MjdiYzI4NmQyZDExZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yUzATYv_gNYxNtuRGf_iy17650r-_Fe2wgAoAyUP0jY)

请教下这个怎么解决的？刚刚关注这个项目，也是遇到一样的问题

**Comment by BigCity8193** [comment]
https://t.zsxq.com/18jimZnbf，会员依赖的问题，clean下，#433不是删了，你怎么找到的
