### ISSUE TITLE
启用验证码的情况下，nginx配置ssl后，验证码接口反向代理访问不到

### ISSUE THREAD

**Issue by zhangbei59** [YunaiV/ruoyi-vue-pro#436]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：2.0.1
- 操作系统：centos 7.9.2009
- 数据库：mysql 5.7.40

### 你猜测可能的原因

我花费了一天时间反复测试该问题，后台登录页面，如果不启用ssl，正常用80端口http访问，反向代理正常，启用ssl并且强制访问https后，验证码接口反向代理访问不到，登录页验证码不显示。

### 复现步骤

第一步，
启用ssl，配置证书，其他配置不变
第二步，

第三步，

### 报错信息

带上必要的截图
前端报错
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/25737059/8375274d-6311-4760-b2c5-668e5d5064aa)
xhr请求报错：
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/25737059/e82ba5b4-fd52-433b-a6e0-f2c7acb0fc2b)
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/25737059/52bf8e6c-3908-47a4-9dc4-465eee82d58f)

直接https访问get提示这个：

![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/25737059/489671cf-0e5d-49f2-b9b4-be9acb3b1b86)

**Comment by zhangbei59** [comment]
已解决：
server段添加该配置项：
   add_header Content-Security-Policy upgrade-insecure-requests;

**Comment by YunaiV** [comment]
收到。我看看要不要补充下！
