### ISSUE TITLE
如何更新,加入我的代码是1.99 如何更新到最新2.01  有更新教程么 可以考虑做一个么

### ISSUE THREAD

**Issue by linechengchen** [YunaiV/ruoyi-vue-pro#443]
如题:
如何更新,加入我的代码是1.99 如何更新到最新2.01  有更新教程么 可以考虑做一个么

**Comment by liyujiang-gzu** [comment]
仅供参考：pull -> merge，Git 合并某个提交节点。

**Comment by linechengchen** [comment]
有意义的 谢谢
我问gpt 还是给我比较好的答案

**Comment by YunaiV** [comment]
> 仅供参考：pull -> merge，Git 合并某个提交节点。

目前来说，是不错的方案哈。
