### ISSUE TITLE
【欢迎认领任务】ProjectReactor后的一些BUG

### ISSUE THREAD

**Issue by yaojunWang** [YunaiV/ruoyi-vue-pro#444]
### 基本信息

- ruoyi-vue-pro 版本：所有
- 操作系统：linux
- 数据库：mysql

### 你猜测可能的原因

自动配置类的初始化顺序改变  导致redis 配置初始化异常，无法启动，访问异常等

### 复现步骤

第一步，修改ProjectReactor的参数 包名字母排序在o后面 ，p到z开头如 site.abcd.saas  (因为默认 RedissonAutoConfiguration.class 的包名是org开头的) ,其他参数随意

第二步，运行ProjectReactor重构工程

第三步，新工程启动运行

### 报错信息

启动后所有请求被security拦截，返回302要求登陆   ， spring  bean 冲突等

###解决方法 
在YudaoRedisAutoConfiguration.java 上添加注解 @AutoConfigureBefore(RedissonAutoConfiguration.class)，使其初始化在前,另 framework > security 里 的config包里的 XXXConfiguration 和 XXXAdapter 类 加上@AutoConfigureOrder(-1) 注解。

另外： 同样原因 也会导致  YudaoSwaggerAutoConfiguration.java 的 openApiBuilder    bean 冲突 ，解决方法，在该方法上添加 @Primary注解。

时间有限只测试  改成s开头以后，如果改成z开头，也许更多问题，但是处理方法几乎相同，感谢作者开源！

**Comment by swdong** [comment]
大佬，用t开头 启动后所有请求被security拦截 返回302要求登陆，这个有解决方法吗？没有错误提示 不知道改哪里

**Comment by swdong** [comment]
> 大佬，用t开头 启动后所有请求被security拦截 返回302要求登陆，这个有解决方法吗？没有错误提示 不知道改哪里

原来是ManagementWebSecurityAutoConfiguration这个优先

**Comment by yaojunWang** [comment]
> 大佬，用t开头 启动后所有请求被security拦截 返回302要求登陆，这个有解决方法吗？没有错误提示 不知道改哪里

把 framework  > security 里 的config包里的 Configuration 和 Adapter 类  加上@AutoConfigureOrder(-1)  注解。

**Comment by swdong** [comment]
> > 大佬，用t开头 启动后所有请求被security拦截 返回302要求登陆，这个有解决方法吗？没有错误提示 不知道改哪里
> 
> 这是请求被安全框架拦截了，把 framework > security 里 的config包里的 XXXConfiguration 和 XXXAdapter 类 加上@AutoConfigureOrder(-1) 注解。

谢谢大佬

**Comment by YunaiV** [comment]
> > 大佬，用t开头 启动后所有请求被security拦截 返回302要求登陆，这个有解决方法吗？没有错误提示 不知道改哪里
> 
> 这是请求被安全框架拦截了，把 framework > security 里 的config包里的 XXXConfiguration 和 XXXAdapter 类 加上@AutoConfigureOrder(-1) 注解。

有兴趣 pull request 一个么？

**Comment by YunaiV** [comment]
> > 大佬，用t开头 启动后所有请求被security拦截 返回302要求登陆，这个有解决方法吗？没有错误提示 不知道改哪里
> 
> 这是请求被安全框架拦截了，把 framework > security 里 的config包里的 XXXConfiguration 和 XXXAdapter 类 加上@AutoConfigureOrder(-1) 注解。

按照这个思路，已经修复
