### ISSUE TITLE
CRM无法查看下属合同

### ISSUE THREAD

**Issue by yaojunWang** [YunaiV/ruoyi-vue-pro#445]
### 基本信息
- ruoyi-vue-pro 版本：所有
- 操作系统：linux
- 数据库：mysql

### 你猜测可能的原因

逻辑错误？看了执行SQL, 和对应的参数 :

`SELECT COUNT(*) AS total`
`FROM crm_contract t`
`INNER JOIN crm_permission t1`
`ON t1.biz_type = 5`
`AND t1.biz_id = t.id`
`AND t1.user_id = 130`
`AND t1.deleted = 0`
`WHERE t.deleted = 0 AND (t.owner_user_id IN (131, 132) AND t.owner_user_id IS NOT NULL)`

131,132是下属用户   130是管理用户， 可以看出，这个SQL应该逻辑是不正确的   INNER JOIN 的user_id  和 where中的 owner_user_id是冲突的。
### 复现步骤

第一步，启动系统

第二步，添加多个用户  配置某用户为部门管理员  

第三步，普通用户新建合同，管理员用户查看下属合同

### 报错信息

查询不到该合同(因为使用同一个数据权限处理方法，所以查看下属的多个地方都是有问题的）

**Comment by YunaiV** [comment]
我看这个 pr 里面有好几个东西，要不要加微信 wangwenbin-server 沟通下哈。

**Comment by yaojunWang** [comment]
我撤掉了， 偷懒了没有分开提，应该规范点的，而且这个查下级的问题，权限处理要改很多地方， 也没有改完，只改了合同的地方 ，所以就当bug提，pr看看最近有时间改完整点提吧。

**Comment by yaojunWang** [comment]
> 我看这个 pr 里面有好几个东西，要不要加微信 wangwenbin-server 沟通下哈。

我撤掉了， 偷懒了没有分开提，应该规范点的，而且这个查下级的问题，权限处理要改很多地方， 也没有改完，只改了合同的地方 ，所以就当bug提，pr看看最近有时间改完整点提吧。

**Comment by YunaiV** [comment]
已经修复

**Comment by YunaiV** [comment]
https://gitee.com/yudaocode/yudao-ui-admin-vue3/pulls/433
