### ISSUE TITLE
2.0.1 master MapUtils 报错

### ISSUE THREAD

**Issue by airclear** [YunaiV/ruoyi-vue-pro#448]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本： 2.0.1

### 你猜测可能的原因

gitee下载的master，MapUtils 报错

### 报错信息

<img width="1062" alt="image" src="https://github.com/YunaiV/ruoyi-vue-pro/assets/4103690/69b97ce4-9e35-4e9a-87db-18da902aec03">

**Comment by YunaiV** [comment]
已经修复~
