### ISSUE TITLE
postgresql  目录的数据库脚本ruoyi-vue-pro.sql太旧了，代码生成功能无法使用

### ISSUE THREAD

**Issue by DavidSche** [YunaiV/ruoyi-vue-pro#449]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：
- 操作系统：windows
- 数据库：postgresql 16

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：xxxxxx
postgresql  目录的数据库脚本ruoyi-vue-pro.sql太旧了，代码生成功能根本无法使用,表i结构都对不上。

postgresql 中的

CREATE TABLE "infra_codegen_table"
(
    "id"                    int8                                        NOT NULL,
    "data_source_config_id" int8                                        NOT NULL,
    "scene"                 int2                                        NOT NULL,
    "table_name"            varchar(200) COLLATE "pg_catalog"."default" NOT NULL,
    "table_comment"         varchar(500) COLLATE "pg_catalog"."default" NOT NULL,
    "remark"                varchar(500) COLLATE "pg_catalog"."default",
    "module_name"           varchar(30) COLLATE "pg_catalog"."default"  NOT NULL,
    "business_name"         varchar(30) COLLATE "pg_catalog"."default"  NOT NULL,
    "class_name"            varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
    "class_comment"         varchar(50) COLLATE "pg_catalog"."default"  NOT NULL,
    "author"                varchar(50) COLLATE "pg_catalog"."default"  NOT NULL,
    "template_type"         int2                                        NOT NULL,
    "parent_menu_id"        int8,
    "creator"               varchar(64) COLLATE "pg_catalog"."default",
    "create_time"           timestamp(6)                                NOT NULL,
    "updater"               varchar(64) COLLATE "pg_catalog"."default",
    "update_time"           timestamp(6)                                NOT NULL,
    "deleted"               int2                                        NOT NULL DEFAULT 0
)
;

mysql 对应的脚本结构

DROP TABLE IF EXISTS `infra_codegen_table`;
CREATE TABLE `infra_codegen_table`  (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `data_source_config_id` bigint NOT NULL COMMENT '数据源配置的编号',
  `scene` tinyint NOT NULL DEFAULT 1 COMMENT '生成场景',
  `table_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '表名称',
  `table_comment` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '表描述',
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '备注',
  `module_name` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '模块名',
  `business_name` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '业务名',
  `class_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '类名称',
  `class_comment` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '类描述',
  `author` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '作者',
  `template_type` tinyint NOT NULL DEFAULT 1 COMMENT '模板类型',
  `front_type` tinyint NOT NULL COMMENT '前端类型',
  `parent_menu_id` bigint NULL DEFAULT NULL COMMENT '父菜单编号',
  `master_table_id` bigint NULL DEFAULT NULL COMMENT '主表的编号',
  `sub_join_column_id` bigint NULL DEFAULT NULL COMMENT '子表关联主表的字段编号',
  `sub_join_many` bit(1) NULL DEFAULT NULL COMMENT '主表与子表是否一对多',
  `tree_parent_column_id` bigint NULL DEFAULT NULL COMMENT '树表的父字段编号',
  `tree_name_column_id` bigint NULL DEFAULT NULL COMMENT '树表的名字字段编号',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 171 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '代码生成表定义';

### 复现步骤

第一步，

第二步，

第三步，

### 报错信息

带上必要的截图

**Comment by YunaiV** [comment]
可以参考 mysql，把 pgsql 缺少的字段，进行补充哈。
