### ISSUE TITLE
form Generator 界面文件保存

### ISSUE THREAD

**Issue by fenglaile888** [YunaiV/ruoyi-vue-pro#45]
form Generator 生成器现在只能到处vue文件，是不是可以添加把配置的json文件保存到数据库，这样就可以下次编辑界面时，不用重新一个一个的布置界面了

**Comment by YunaiV** [comment]
准备进入开发了，会新增一个 流程表单，给工作流提供动态表单的能力

**Comment by fenglaile888** [comment]
是不是可以根据不同的用户登录，看到自己定制的首页面，就像window类似，放置功能图标或关心的图表

**Comment by YunaiV** [comment]
> 准备进入开发了，会新增一个 流程表单，给工作流提供动态表单的能力

已支持，可以到 http://dashboard.yudao.iocoder.cn/ 体验一下。

**Comment by YunaiV** [comment]
> 是不是可以根据不同的用户登录，看到自己定制的首页面，就像window类似，放置功能图标或关心的图表

这个暂时不考虑支持哈，不算特别通用的功能。
