### ISSUE TITLE
【欢迎认领任务】微信扫码支付渠道缺失 BUG 

### ISSUE THREAD

**Issue by tianbocheng** [YunaiV/ruoyi-vue-pro#450]
- 应用信息配置界面缺少该项配置
<img width="1511" alt="image" src="https://github.com/YunaiV/ruoyi-vue-pro/assets/20829408/4efc0140-9ab8-485b-9a77-7d04568861df">
<img width="2051" alt="image" src="https://github.com/YunaiV/ruoyi-vue-pro/assets/20829408/7ad21577-e744-4fc2-840f-b26ee1ab2d98">

- 从数据库 pay_channel 中强制增加 code = wx_native 的数据
<img width="1639" alt="image" src="https://github.com/YunaiV/ruoyi-vue-pro/assets/20829408/6fe7db6f-65cc-4b4c-aeee-1aa24055e719">

- 报错：当tadetype是 NATVE时，需指定非空的productid值

- 应在 WxNativePayClient 中增加 setProductld
<img width="903" alt="image" src="https://github.com/YunaiV/ruoyi-vue-pro/assets/20829408/fd8be769-502a-45f6-8d0c-f880dbe3e2aa">

**Comment by YunaiV** [comment]
我测试下来，貌似不需要填写

= = 你目前填写的值是多少？

有没兴趣 pull request 贡献下哈。

**Comment by YunaiV** [comment]
已修复。
应该是 v2 扫码，必须传递。我测试是 v3，不需要传递。
