### ISSUE TITLE
商品交易订单发货日志的物流公司名称显示有问题

### ISSUE THREAD

**Issue by liyujiang-gzu** [YunaiV/ruoyi-vue-pro#453]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：2.0.1
- 操作系统：Windows
- 数据库：MySQL 8

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：传递的参数是“expressName”，但是模板变量里用的是“deliveryName”。

### 复现步骤

第一步，前台订单支付成功

第二步，后台点击发货

第三步，订单详情页发货日志未解析出物流公司名称

### 报错信息

带上必要的截图

gitee上已PR。

**Comment by YunaiV** [comment]
感谢 pr，已经合并！

**Comment by 905407220** [comment]
ruoyi-vue-pro 版本：2.0.1最新的代码发现问题还存在

**Comment by liyujiang-gzu** [comment]
> ruoyi-vue-pro 版本：2.0.1最新的代码发现问题还存在

2.0.1之后的版本才修复的

**Comment by 905407220** [comment]
> > ruoyi-vue-pro 版本：2.0.1最新的代码发现问题还存在
> 
> 2.0.1之后的版本才修复的

我弄错版本了。我下最新的2.3也还是存在该问题。
