### ISSUE TITLE
bug：支付应用信息管理页面开启某些支付渠道后再关闭，列表页会一直显示开启。

### ISSUE THREAD

**Issue by liyujiang-gzu** [YunaiV/ruoyi-vue-pro#454]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：2.0.1
- 操作系统：Windows
- 数据库：MySQL 8

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：根据appid查询支付渠道未排除状态为已关闭的渠道码，在组合chanelcodes数组之前应该移除掉处于关闭状态的。

### 复现步骤

第一步，后台列表页修改支付应用信息，开启钱包支付

第二步，点击钱包支付的“√”，弹窗中修改为“关闭”

第三步，刷新列表页，钱包支付仍然显示“√”，预期应该是“❌”

### 报错信息

带上必要的截图

gitee上已PR

**Comment by YunaiV** [comment]
感谢，https://gitee.com/zhijiantianya/ruoyi-vue-pro/commit/03e3dc01216a532799e39e86a53f1b0d1bf1e46a
