### ISSUE TITLE
疑似mysql和postgresql两个数据库的代码生成功能对应的表结构不一致

### ISSUE THREAD

**Issue by 328500920** [YunaiV/ruoyi-vue-pro#455]
### 基本信息

- ruoyi-vue-pro 版本：1.0.0
- 操作系统：centos7.6
- 数据库：postgresql

### 你猜测可能的原因
疑似mysql和postgresql两个数据库的代码生成功能对应的表结构不一致
（必填）我花费了 1 小时自查，发现可能的原因是：infra_codegen_table表的表结构mysql和postgresql的不一致，
postgresql比mysql的少了字段。

带上必要的截图
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/5036481/601f6bc6-5c73-484f-8fb6-1b65ee756ba1)

**Comment by YunaiV** [comment]
pgsql 需要自己手动基于 mysql 进行转换哈。

**Comment by YunaiV** [comment]
或者参考 mysql，把 pgsql 缺失的字段，手动补上去。
