### ISSUE TITLE
web模块中YudaoXssAutoConfiguration配置导致的工作流设计器失效BUG

### ISSUE THREAD

**Issue by yaojunWang** [YunaiV/ruoyi-vue-pro#456]
启用xss以后，工作流设计器失效。

### 基本信息

- ruoyi-vue-pro 版本：v2.0.1
- 操作系统：linux
- 数据库：mysql

### 你猜测可能的原因

在该配置类中，总共有两个地方会作xss注入检测和处理，一个是xssfilter过滤器，流程引擎可以通过配置xss的exclude-urls 来安全穿过，但是很可惜，却会被反序列化的xssCleaner 清理掉，导致工作流定义文档的xml被破坏，设计器无法使用。
### 复现步骤

第一步，修改  xss.enable: true,将工作流设计相关路径加入xss的exclude-urls。

第二步，启动系统

第三步，使用工作流设计器

### 报错信息

数据库中保存的工作流定义文档为破坏后的文档，无法使用。

**Comment by YunaiV** [comment]
已修复。 https://gitee.com/zhijiantianya/ruoyi-vue-pro/commit/c943233ee56d00d74d41a3fa8dbf85626f10cbdd
