### ISSUE TITLE
pom.xml涉及到yudao的包在huawei的repository无相关jar

### ISSUE THREAD

**Issue by czmchen** [YunaiV/ruoyi-vue-pro#457]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：
- 操作系统：
- 数据库：

![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/13728446/f922ab89-da50-4780-8002-c14e7addc395)
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/13728446/096b0372-b1c5-417a-8e5a-efab4dc74a96)

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：xxxxxx

### 复现步骤

第一步，

第二步，

第三步，

### 报错信息

带上必要的截图

**Comment by yaojunWang** [comment]
先去工程根目录 mvn install.

**Comment by YunaiV** [comment]
https://doc.iocoder.cn/quick-start/

参考文档，谢谢。
