### ISSUE TITLE
没有找到 ruoyi-ui  文件目录

### ISSUE THREAD

**Issue by kkhei** [YunaiV/ruoyi-vue-pro#46]
https://www.iocoder.cn/Yudao/build-debugger-environment/ 链接下的5. 启动前端项目  ，进入项目目录
cd ruoyi-ui   ，但是下载 ruoyi-vue-pro 后没有找到此文件目录，目前如何启动前端服务呢？

**Comment by YunaiV** [comment]
https://github.com/YunaiV/ruoyi-vue-pro/tree/master/yudao-admin-ui
