### ISSUE TITLE
根据文档说明来操作的,项目启动没问题,就是controller中的接口不能被访问

### ISSUE THREAD

**Issue by kang1097** [YunaiV/ruoyi-vue-pro#465]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：vue3
- 操作系统：macos
- 数据库：mysql

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：xxxxxx
----大概是java配置不对

### 复现步骤

第一步，建立模块

第二步，生成代码

第三步，复制代码

### 报错信息
<img width="378" alt="image" src="https://github.com/YunaiV/ruoyi-vue-pro/assets/110171491/68974cb5-adee-468b-9ce2-7f590a8152b6">

带上必要的截图
yudao的pom：
<img width="1473" alt="image" src="https://github.com/YunaiV/ruoyi-vue-pro/assets/110171491/94f26d8e-4328-47c1-a39e-f83c7627fedc">
控制层接口：
<img width="1030" alt="image" src="https://github.com/YunaiV/ruoyi-vue-pro/assets/110171491/08501bf0-3262-4b3a-b6c5-ecc95ea1610a">
<img width="1017" alt="image" src="https://github.com/YunaiV/ruoyi-vue-pro/assets/110171491/33855acf-4ca1-4164-90bd-b23230e23700">
yudao-server的pom里也配置了：
<img width="1467" alt="image" src="https://github.com/YunaiV/ruoyi-vue-pro/assets/110171491/f89f7598-ed50-4a01-945d-03deddb24505">
postman测试了也不通：
<img width="720" alt="image" src="https://github.com/YunaiV/ruoyi-vue-pro/assets/110171491/01c0fa6b-5440-479e-a726-a77192bc7c21">

clean/install都试过了,实在看不明白是哪里的问题啊.请问哪里的问题还会导致404啊？

**Comment by YunaiV** [comment]
idea maven 刷新下，试试看哈。

**Comment by YunaiV** [comment]
然后，看看 package 是不是没放 admin 下？

**Comment by kang1097** [comment]
都试过了😭，代码都是生成的，啥也没改，index页面也能正常显示，就是调用接口报404。
是不是接口配错了：
<img width="1273" alt="image" src="https://github.com/YunaiV/ruoyi-vue-pro/assets/110171491/2a2bf9c2-a716-4819-8823-bb4455416156">
<img width="1087" alt="image" src="https://github.com/YunaiV/ruoyi-vue-pro/assets/110171491/e0736fc2-d1e3-41e0-bc17-4f486a97cf51">
<img width="321" alt="image" src="https://github.com/YunaiV/ruoyi-vue-pro/assets/110171491/039e04f4-c95d-4df2-a0d2-387a382327e9">

**Comment by zeno-sh** [comment]
在yudao-server的pom中添加你的biz模块即可

**Comment by kang1097** [comment]
> 在yudao-server的pom中添加你的biz模块即可

这个加了，我找到原因了，YudaoServerApplication里没有添加package
