### ISSUE TITLE
【欢迎认领任务】ProjectReactor中PACKAGE_NAME 无法以com开头

### ISSUE THREAD

**Issue by gxl-hub** [YunaiV/ruoyi-vue-pro#467]
### 基本信息

- ruoyi-vue-pro 版本：2.0.1
- 操作系统：windows11
- 数据库：mysql 

### 你猜测可能的原因

扫描包顺序造成的BEAN重复加载，包名必须在com 顺序之前

### 复现步骤

第一步，将代码中cn.start.pp  String packageNameNew = "com.start.pp";  

第二步，生成代码，启动

第三步，出现错误

### 报错信息

The bean 'restTemplate', defined in class path resource [com/start/pp/framework/web/config/StarWebAutoConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [com/fhs/trans/config/TransServiceConfig.class] and overriding is disabled.

带上必要的截图

![1712602263291](https://github.com/YunaiV/ruoyi-vue-pro/assets/61272592/2b933ba2-dbfb-41c3-99b9-00cb72cf726d)

**Comment by cybearfish** [comment]
在启动后端项目时出现相同报错，因为com/fhs/trans/config/TransServiceConfig中的bean 'restTemplate'大致相同，故暂时注释StarWebAutoConfiguration中相关代码解决，猜想application-local.yaml中添加allow-bean-definition-overriding: true也可以。

**Comment by chenminjie66** [comment]
修改包名后 easy-trans 包中的 RestTemplate Bean 和 框架中的 xxx-spring-boot-starter-web 包下的 RestTemplate Bean 冲突的问题原因 

这个涉及到 springboot 配置类的注入优先级，具体的可以去官网查看文档。
默认情况下，同等优先级的配置类会根据包名的顺序加载 
例如
   1️⃣ org.a 、2️⃣ org.b 加载顺序为 1️⃣2️⃣
   1️⃣ org.a.k 、2️⃣ com.a 、3️⃣ xyz.a 、4️⃣org.a.b 加载顺序为 2️⃣4️⃣1️⃣3️⃣
## 优雅的解决方法： 在 xxx-spring-boot-starter-web 包下找到MexpWebAutoConfiguration.java 
1. 在其类上添加注解 @AutoConfigureOrder(Ordered.HIGHEST_PRECEDENCE) 
2. 在其中 找到 注入 RestTemplate 的Bean 在其上添加 @ConditionalOnMissingBean(RestTemplate.class) 

注：@AutoConfigureOrder 注解可以控制 使用 org.springframework.boot.autoconfigure.AutoConfiguration.imports 和 spring.factories 文件注入的配置类顺序，同样是值越小优先级越高，其默认值为0

allow-bean-definition-overriding: true配置的风险太高了

**Comment by YunaiV** [comment]
> 修改包名后 easy-trans 包中的 RestTemplate Bean 和 框架中的 xxx-spring-boot-starter-web 包下的 RestTemplate Bean 冲突的问题原因
> 
> 这个涉及到 springboot 配置类的注入优先级，具体的可以去官网查看文档。 默认情况下，同等优先级的配置类会根据包名的顺序加载 例如 1️⃣ org.a 、2️⃣ org.b 加载顺序为 1️⃣2️⃣ 1️⃣ org.a.k 、2️⃣ com.a 、3️⃣ xyz.a 、4️⃣org.a.b 加载顺序为 2️⃣4️⃣1️⃣3️⃣
> 
> ## 优雅的解决方法： 在 xxx-spring-boot-starter-web 包下找到XxxWebAutoConfiguration.java
> 1. 在其类上添加注解 @AutoConfigureOrder(Ordered.HIGHEST_PRECEDENCE)
> 2. 在其中 找到 注入 RestTemplate 的Bean 在其上添加 @ConditionalOnMissingBean(RestTemplate.class)
> 
> 注：@AutoConfigureOrder 注解可以控制 使用 org.springframework.boot.autoconfigure.AutoConfiguration.imports 和 spring.factories 文件注入的配置类顺序，同样是值越小优先级越高，其默认值为0
> 
> allow-bean-definition-overriding: true配置的风险太高了

不错的建议，我下周也测试下
