### ISSUE TITLE
代码生成功能：1.不支持枚举类，2、knife4j中不能下载文件，需要接口增加produces = {"application/octet-stream"}

### ISSUE THREAD

**Issue by aboluo-gy** [YunaiV/ruoyi-vue-pro#47]
枚举类型表定义参考如下：
CREATE TABLE `country` (
  `Code` char(3) NOT NULL DEFAULT '',
  `Name` char(52) NOT NULL DEFAULT '',
  `Continent` enum('Asia','Europe','North America','Africa','Oceania','Antarctica','South America') NOT NULL DEFAULT 'Asia',
  `Region` char(26) NOT NULL DEFAULT '',
  `SurfaceArea` float(10,2) NOT NULL DEFAULT '0.00',
  `IndepYear` smallint(6) DEFAULT NULL,
  `Population` int(11) NOT NULL DEFAULT '0'
  PRIMARY KEY (`Code`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

swagger下载文件说明：https://www.bookstack.cn/read/knife4j/downloadAndPreview.md

**Comment by YunaiV** [comment]
1、枚举类型，大概率不会支持哈。
2、swagger 下载我研究下

**Comment by aboluo-gy** [comment]
好的大佬，再请教个问题，脚手架是maven父子模块，编译打包父项目，会把子模块一起打包，单独打包子模块会报错，有个有啥好的idea吗？

**Comment by YunaiV** [comment]
> 好的大佬，再请教个问题，脚手架是maven父子模块，编译打包父项目，会把子模块一起打包，单独打包子模块会报错，有个有啥好的idea吗？

可以看下 maven 的关联编译 https://blog.csdn.net/zwhfyy/article/details/82049286
