### ISSUE TITLE
关于出现 getInputStream（） has already been called for this request的问题

### ISSUE THREAD

**Issue by chenminjie66** [YunaiV/ruoyi-vue-pro#474]
我发现 在请求404的时候会出现：
```
getInputStream（） has already been called for this request
```
虽然配置了 Request Body 缓存的 Filter ，但是404并不会走这个filter
既然它不走，那么我们直接排除他即可

#### 2. 在 打印 request 日志 的判断里加上一句
```java
!request.getRequestURI().startsWith("/error")
```
如图：
<img width="712" alt="image" src="https://github.com/YunaiV/ruoyi-vue-pro/assets/37528476/5ac80f2d-278f-47e0-94ef-3c202f537d97">
#### 3. 在 afterCompletion 方法中停止计时加一个判断，因为上面跳过了，计时就不会启动，避免报错
<img width="677" alt="image" src="https://github.com/YunaiV/ruoyi-vue-pro/assets/37528476/f5a4f49f-94e8-4abf-902e-7bf9fb6e23dc">

至于诱发此错误的其他途径我并没遇到，如果谁遇到了类似的问题，可以尝试一下这个解决方法

**Comment by YunaiV** [comment]
已修复

**Comment by ca0t** [comment]
有用，增加了一个静态路由地址后，各种报错，根本没往地址拼错上去想
