### ISSUE TITLE
【欢迎贡献】商城模块，商品列表没有排序，排序后商品展示乱序（装修页面 + 商城小程序）

### ISSUE THREAD

**Issue by tianbocheng** [YunaiV/ruoyi-vue-pro#475]
商城模块，商品列表没有排序，排序后商品才能按照正确的顺序展示。
<img width="1785" alt="image" src="https://github.com/YunaiV/ruoyi-vue-pro/assets/20829408/acffdcb7-93be-44c7-af11-dac5853b8cf8">

代码修改改成如图所示。
<img width="1664" alt="image" src="https://github.com/YunaiV/ruoyi-vue-pro/assets/20829408/e01aa08a-826b-4870-9485-210af3e3084e">

**Comment by YunaiV** [comment]
排序的话，可能按照 sort 升序，更合适一点

**Comment by tianbocheng** [comment]
@YunaiV    升序没问题的，我感觉

**Comment by YunaiV** [comment]
我想了下这个场景，不应该排序。

而是按照传递进来的 ids，进行排序。

例如说，传递进来的是 [3,1,2]

那么返回的就是 3, 1, 2 分别对应的商品

**Comment by YunaiV** [comment]
已修复。
