### ISSUE TITLE
打开pom.xml的crm注释后，maven加载失败

### ISSUE THREAD

**Issue by xujizhong** [YunaiV/ruoyi-vue-pro#484]
错误提示：
cn.iocoder.boot:yudao-module-crm-biz:jar:2.0.1-jdk8-snapshot was not found in https://mirrors.huaweicloud.com/repository/maven/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of huaweicloud has elapsed or updates are forced

![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/25857517/eb1238c3-ea45-446a-8f51-d0ff1e8ab3ee)

**Comment by YunaiV** [comment]
https://doc.iocoder.cn/crm/build/
