### ISSUE TITLE
ruoyi-vue-pro.sql 文件过大导致数据库初始化耗时超 20 分钟

### ISSUE THREAD

**Issue by DevDengChao** [YunaiV/ruoyi-vue-pro#486]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：6f42da1b (master-jdk21)
- 操作系统：win
- 数据库：MySQL

现在 /sql/mysql/ruoyi-vue-pro.sql 文件已经有 5000+ 行了, 对于初始化远程数据库而言, 单次执行脚本的时间已经超过 20 分钟, 十分不利于新人上手.

### 你猜测可能的原因

单个 sql 脚本内容过多, 导致在单个事务中运行时间过长.

### 复现步骤

1. 克隆工程到本地
2. 使用任意 MySQL client 链接到远程数据库
3. 执行 /sql/mysql/ruoyi-vue-pro.sql 
4. 等待超过 20 分钟

### 报错信息

不相关

### 改进建议

将上述脚本拆分为多个小的片段并使用 Flyway 对数据库结构进行控制, 以便项目启动时 Flyway 自动对数据库进行初始化, 从而降低新人初始化数据库时的试错成本.

将 ruoyi-vue-pro.sql 分段后再进行初始化显著降低了数据库的初始化时长到 3 分钟左右: 
```
2024-04-25 14:14:37.249 |  INFO 4740 | main [TID: N/A] o.f.core.internal.command.DbMigrate      | Successfully applied 7 migrations to schema `ruoyi-vue-pro`, now at version v2024.0425.6 (execution time 03:11.856s)
```

**Comment by YunaiV** [comment]
暂时没碰到，建议自查下。

= = 秒级初始化完
