### ISSUE TITLE
用户登录的密码默认是明文，请问加密在哪配置

### ISSUE THREAD

**Issue by onunix** [YunaiV/ruoyi-vue-pro#49]

**Comment by YunaiV** [comment]
密码不是明文的，可以在瞅瞅喲

**Comment by onunix** [comment]
我理解了，你说的加密是数据库里面加密后存储的，但是网络传输层对敏感字段（密码）也应该加密。谢谢。

**Comment by YunaiV** [comment]
> 我理解了，你说的加密是数据库里面加密后存储的，但是网络传输层对敏感字段（密码）也应该加密。谢谢。

理解了。一般数据传输，会有 https 所以传输层是保证安全了。之前在过等级保护的时候，一开始没 https，要求前端做下加密进行传输。后来又了 https，也允许使用不加密传输。

不过确实不加密传输，会存在后端泄密的可能性，还是加密一下比较好。后续我加下哈。
