### ISSUE TITLE
oracle 实际运行会出现多个字段无效问题

### ISSUE THREAD

**Issue by sdlushao** [YunaiV/ruoyi-vue-pro#494]
### 基本信息

- ruoyi-vue-pro 版本：2.0.1
- 操作系统：windows
- 数据库：oracle

### 你猜测可能的原因

可能是数据库转换的原因

**Comment by sdlushao** [comment]
system_notify_message 表不存在

**Comment by YunaiV** [comment]
预计 5 月份，会提供最新的

**Comment by YunaiV** [comment]
https://gitee.com/zhijiantianya/ruoyi-vue-pro/blob/feature/db/sql/oracle/ruoyi-vue-pro.sql

可以使用这个
