### ISSUE TITLE
允许管理员主动查询短信日志的下发状态

### ISSUE THREAD

**Issue by DevDengChao** [YunaiV/ruoyi-vue-pro#497]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：6f42da1b master-jdk21
- 操作系统：不相关
- 数据库：不相关

### 场景描述

由于目前阿里云与腾讯云的短信回执功能不完善, 导致开发者无法基于部署环境 (测试环境/正式环境) 分别指定回执的接收地址, 因此管理员无法在不同的部署环境中查看短信日志中的 "接收状态" .

建议添加批量查询短信日志下行状态的接口.

### 复现步骤

第一步，将应用分别部署到测试环境与正式环境

第二步，去云平台上配置短信下行状态的回调地址, 发现只允许填写一处回调地址

第三步，下行状态始终被同步到正式环境或测试环境, 导致另一个环境无法查看短信日志的 "接收状态"

### 报错信息

不相关.

**Comment by DevDengChao** [comment]
( 鉴定为 ROI 较低, 没有实现的动力.

**Comment by YunaiV** [comment]
一般测试环境，不会太关注发送状态哈。

= = 不增加过多复杂性了~~~
