### ISSUE TITLE
 bpm  模块     设计流程表单， select 组件数据，从后台获取数据，能不能自动添加  header  

### ISSUE THREAD

**Issue by tianbocheng** [YunaiV/ruoyi-vue-pro#498]
- 设计流程表单
- 使用 select 组件的接口数据
- 定义接口为：http://localhost:48080/admin-api/system/user/page?pageNo=1&pageSize=10
- 请求如上接口需要加入 Authorization header 才能通
- 要不只能把上述接口不限制权限  @PermitAll  
- form-create 官方给出 可以配置表单配置的options.beforeFetch方法在请求前处理规则,例如设置token

问题：Authorization header  能不能自动添加呢

![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/20829408/67886f78-e887-4460-995a-52da4d06a14f)
<img width="2017" alt="image" src="https://github.com/YunaiV/ruoyi-vue-pro/assets/20829408/95525c38-7028-4d39-a1e4-e7e88b0a894f">

**Comment by tianbocheng** [comment]
找个一个解决办法


<img width="1747" alt="image" src="https://github.com/YunaiV/ruoyi-vue-pro/assets/20829408/3f484111-33c5-4705-85e0-a640c084beb6">

在 src/plugins/formCreate/index.ts 中设置 formCreate.fetch

```
// 第一个是原fetch用到的option，第二个没找到源码中引用的地方不知道有什么用
const overrideFetch = (option: any, effectArgs: any) => {
  // console.log('--fetch option--', option)
  service({
    url: option.action,
    method: option.method,
    data: option.data,
    headers: option.headers,
    withCredentials: option.withCredentials
  })
    .then((res) => {
      try {
        if (option._parse) {
          // 使用内置 api 处理解析函数字符串转化为 函数类型
          const parseFn = formCreate.parseFn(option._parse)
          res.data = parseFn(res)
        }
      } catch (e) {
        console.log('--parseFn error--', e)
      }
      option.onSuccess?.(res)
    })
    .catch((e) => {
      option.onError?.(e)
    })

  return option
}



// 参考 http://www.form-create.com/v3/element-ui/auto-import.html 文档
export const setupFormCreate = (app: App<Element>) => {
  components.forEach((component) => {
    app.component(component.name, component)
  })
  formCreate.use(install)
  formCreate.fetch = overrideFetch
  app.use(formCreate)
  app.use(FcDesigner)
}



```

参考链接：https://blog.csdn.net/lister1005/article/details/131306732

**Comment by YunaiV** [comment]
收到，我们正在搞哈

**Comment by tianbocheng** [comment]
还有个问题是 @YunaiV    保存   解析函数 无法没有保存

- 下拉框组件，点击 修改解析函数，点击保存，没有将解析函数保存

<img width="3390" alt="image" src="https://github.com/YunaiV/ruoyi-vue-pro/assets/20829408/c3c95b52-9271-40f9-a4e1-581f236d9ed9">

**Comment by YunaiV** [comment]
> 还有个问题是 @YunaiV 保存 解析函数 无法没有保存
> 
> * 下拉框组件，点击 修改解析函数，点击保存
> * 第二次进入，重新编辑查看，没有将解析函数保存
> 
> <img alt="image" width="2000" src="https://private-user-images.githubusercontent.com/20829408/326632178-c3c95b52-9271-40f9-a4e1-581f236d9ed9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MzI3NTAsIm5iZiI6MTcxNTQzMjQ1MCwicGF0aCI6Ii8yMDgyOTQwOC8zMjY2MzIxNzgtYzNjOTViNTItOTI3MS00MGY5LWE0ZTEtNTgxZjIzNmQ5ZWQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDEzMDA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjZjAyNmQ3MWMzZWVhMDcyMWVmZmEwNjIxNWIyYzRkOTg0MWU1ZmNiYmI1NWNiNDE4MWMyZGU2NmQ0YzY0M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g-ZBkOC6PupcyxOWFtmd674W8b5PQYRhvk4UunZSe8M">
> * 在 vue debug 插件下是有这个参数的
> 
> <img alt="image" width="2000" src="https://private-user-images.githubusercontent.com/20829408/326640319-08d1300f-62df-47cc-8487-f9c53a90dbe7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MzI3NTAsIm5iZiI6MTcxNTQzMjQ1MCwicGF0aCI6Ii8yMDgyOTQwOC8zMjY2NDAzMTktMDhkMTMwMGYtNjJkZi00N2NjLTg0ODctZjljNTNhOTBkYmU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDEzMDA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhYmM4NDA0YjkxZmZjMmRmNTJmYjRiYjg0YTAxNzE1MTAwM2MxNzg4MDg3ZDE5YzAzZGE4NWJjMDg4NzAyYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.46xDydByqKuGtq2jeU8ubQqZfrO_KShu-J2b_kJmMZc">

和 https://github.com/YunaiV/ruoyi-vue-pro/issues/499 重复，统一跟进
