### ISSUE TITLE
bpm 模块 设计流程表单， select 组件数据， 解析函数 无法保存

### ISSUE THREAD

**Issue by tianbocheng** [YunaiV/ruoyi-vue-pro#499]
保存   解析函数 无法没有保存

- 下拉框组件，点击 修改解析函数，点击保存
- 第二次进入，重新编辑查看，没有将解析函数保存

<img width="3390" alt="image" src="https://github.com/YunaiV/ruoyi-vue-pro/assets/20829408/c3c95b52-9271-40f9-a4e1-581f236d9ed9">

- 在 vue debug 插件下是有这个参数的
<img width="2441" alt="image" src="https://github.com/YunaiV/ruoyi-vue-pro/assets/20829408/08d1300f-62df-47cc-8487-f9c53a90dbe7">

- 修改 src/utils/formCreate.ts
<img width="2208" alt="image" src="https://github.com/YunaiV/ruoyi-vue-pro/assets/20829408/0f36ea82-0d75-496b-9dc1-90981d11825c">

```
// 编码表单 Fields
export const encodeFields = (designerRef: object) => {
  // @ts-ignore
  const rule = designerRef.value.getRule()
  const fields: string[] = []
  
  rule.forEach((item) => {
    if (item?.effect?.fetch?.parse) {
      item.effect.fetch.parse = item.effect.fetch.parse.toString()
    }
    const itemTmp = JSON.stringify(item)
    fields.push(itemTmp)
  })
  return fields
}

// 解码表单 Fields
export const decodeFields = (fields: string[]) => {
  const rule: object[] = []
  fields.forEach((item) => {
    const itemTmp = JSON.parse(item)
    if (itemTmp?.effect?.fetch?.parse) {
      itemTmp.effect.fetch.parse = eval('(' + itemTmp.effect.fetch.parse + ')')
    }
    rule.push(itemTmp)
  })
  return rule
}


```

**Comment by YunaiV** [comment]
https://docs.qq.com/doc/DZlNIVkZSTlVJVEd2
