### ISSUE TITLE
vben BaseTable组件自适应高度计算

### ISSUE THREAD

**Issue by hao2001** [YunaiV/ruoyi-vue-pro#501]
### 基本信息

- ruoyi-vue-pro 版本：vben

vben的BaseTable组件的body height（自适应全页）在计算的时候没有排除底部footer的高度。这个页面我尝试了一下通过const { footerHeightRef } = useLayoutHeight()获取高度并在height中减去，但是首次加载的时候似乎取不到值（值等于0）

参考页面：http://dashboard-vben.yudao.iocoder.cn/http://static-vben.yudao.iocoder.cn/login?redirect=/system/tenant/list

**Comment by summer001-pd** [comment]
其实这玩意也不算bug 下面是版权信息占了页面高度 可以直接干掉 或者将这一块做成可收起的drawer 甚至说可以直接去table的useTableScroll方法中直接减去版权信息高度
