### ISSUE TITLE
【缺陷】yudao-spring-boot-starter-mybatis模块移除Druid广告逻辑未按照期望执行

### ISSUE THREAD

**Issue by ximinghui** [YunaiV/ruoyi-vue-pro#503]
### 基本信息

- ruoyi-vue-pro 版本：v2.0.1 (2.0.1-snapshot)
- 操作系统：Windows 11 Pro (23H2, OS Build 22631.3527)
- 数据库：MySQL 8.3.0

### 原因

问题代码所在位置: cn.iocoder.yudao.framework.datasource.config.YudaoDataSourceAutoConfiguration.java:26

需求：代码中```@ConditionalOnProperty(name = "spring.datasource.druid.web-stat-filter.enabled", havingValue = "true")```部分设置了仅启用```druid.web-stat-filter```的情况才会执行到Druid广告移除逻辑，**该条件应被移除或修改为 ```@ConditionalOnProperty(name = "spring.datasource.druid.stat-view-servlet.enabled", havingValue = "true")``` 。**

理由：```web-stat-filter```开关仅仅用于控制Druid是否对URL进行监控（见 [alibaba / druid Wiki - 配置_配置WebStatFilter](https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_%E9%85%8D%E7%BD%AEWebStatFilter)），控制是否启用整个Druid监控功能的开关为 ```stat-view-servlet``` 。

### 复现步骤

第一步：在生效spring boot profile配置文件中，将 ```spring.datasource.druid.web-stat-filter.enabled``` 设置为 ```false``` ，启动项目

第二步：打开 ```芋道后台管理系统``` ，定位于 ```基础设施 -> 监控中心 -> MySQL监控``` 页面

第三步：可观察到Druid广告被展示

**Comment by YunaiV** [comment]
已修复
