### ISSUE TITLE
crm配置好审批、回款流程后，操作报空指针

### ISSUE THREAD

**Issue by maioria** [YunaiV/ruoyi-vue-pro#504]
如题，本地需要调整下才能正常运行
 // 2. 创建合同审批流程实例
        String processInstanceId = bpmProcessInstanceApi.createProcessInstance(userId, new BpmProcessInstanceCreateReqDTO()
                .setProcessDefinitionKey(BPM_PROCESS_DEFINITION_KEY).setBusinessKey(String.valueOf(id)).setVariables(new HashMap<>()));
                需要加上 setVariables(new HashMap<>()));

**Comment by YunaiV** [comment]
https://gitee.com/zhijiantianya/ruoyi-vue-pro

拉下 gitee 最新代码，master
