### ISSUE TITLE
MemberUserDO.sex 与 MemberUserBaseVO.sex 类型不一致

### ISSUE THREAD

**Issue by DevDengChao** [YunaiV/ruoyi-vue-pro#507]
### 基本信息

- ruoyi-vue-pro 版本：2.1.0
- 操作系统：不相关
- 数据库：不相关

### 你猜测可能的原因

不相关

### 复现步骤

https://github.com/YunaiV/ruoyi-vue-pro/blob/8428cc5b9922080661626d241d1e745117ff9491/yudao-module-member/yudao-module-member-biz/src/main/java/cn/iocoder/yudao/module/member/controller/admin/user/vo/MemberUserBaseVO.java#L40-L41

https://github.com/YunaiV/ruoyi-vue-pro/blob/8428cc5b9922080661626d241d1e745117ff9491/yudao-module-member/yudao-module-member-biz/src/main/java/cn/iocoder/yudao/module/member/dal/dataobject/user/MemberUserDO.java#L94-L98

https://github.com/YunaiV/ruoyi-vue-pro/blob/8428cc5b9922080661626d241d1e745117ff9491/yudao-module-system/yudao-module-system-api/src/main/java/cn/iocoder/yudao/module/system/enums/common/SexEnum.java#L13-L27

### 报错信息

MemberUserBaseVO.sex 使用了 Byte 作为类型, 导致业务操作时需要对类型进行转换才能继续操作, 很不方便.

### 改进建议

统一使用 Integer 类型.

**Comment by YunaiV** [comment]
感谢修复
