### ISSUE TITLE
SexEnum.UNKNOWN.value 与 memeber_user.sex 的默认值不一致

### ISSUE THREAD

**Issue by DevDengChao** [YunaiV/ruoyi-vue-pro#508]
### 基本信息

- ruoyi-vue-pro 版本：2.1.0
- 操作系统：不相关
- 数据库：不相关

### 你猜测可能的原因

不相关

### 复现步骤

https://github.com/YunaiV/ruoyi-vue-pro/blob/8428cc5b9922080661626d241d1e745117ff9491/yudao-module-system/yudao-module-system-api/src/main/java/cn/iocoder/yudao/module/system/enums/common/SexEnum.java#L13-L27

![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/16363180/120d8398-b430-4c06-8463-d94d402f6dbc)

### 报错信息

member-2024-01-18.sql 中对于 sex 字段的默认值是 0 , 但 SexEnum.UNKNOWN.value 的值是 3.

### 改进建议

新增 SexEnum.UNSPECIFED (0), 并废弃 SexEnum.UNKNOWN .

**Comment by YunaiV** [comment]
建议把 UNKNOWN 改成 0 哈

**Comment by YunaiV** [comment]
这块是之前搞的不对，应该就是 0 是未知哈。

**Comment by DevDengChao** [comment]
删除了 UNSPECIFIED, 更换了 UNKNOWN 的值
