### ISSUE TITLE
ProductSpuStatusEnum.status 与 product_spu.status 描述不一致

### ISSUE THREAD

**Issue by DevDengChao** [YunaiV/ruoyi-vue-pro#512]
### 基本信息

- ruoyi-vue-pro 版本：2.1.0
- 操作系统：不相关
- 数据库：不相关

### 复现步骤

https://github.com/YunaiV/ruoyi-vue-pro/blob/8428cc5b9922080661626d241d1e745117ff9491/yudao-module-mall/yudao-module-product-api/src/main/java/cn/iocoder/yudao/module/product/enums/spu/ProductSpuStatusEnum.java#L16-L21

![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/16363180/edd24324-7ece-422d-88e8-15a738652957)

### 改进建议

建议修复 mall-2024-01-17.sql 里的字段描述.

**Comment by YunaiV** [comment]
收到。这块已经修复，没有导出最新的。
