### ISSUE TITLE
商城模块缺少虚拟商品的案例

### ISSUE THREAD

**Issue by DevDengChao** [YunaiV/ruoyi-vue-pro#515]
### 基本信息

- ruoyi-vue-pro 版本：2.1.0
- 操作系统：不相关
- 数据库：不相关

### 现状

目前商城主要以实体商品的买卖作为模型进行搭建的, 如果目标业务以软件服务为主体的话, 目前的商城并不能很好的进行适配, 对开发者而言需要改造的部分较多.

### 建议

建议补充销售虚拟商品相关的示例, 例如: 积分, 会员.

**Comment by YunaiV** [comment]
感谢建议。

近期应该暂时不搞虚拟商品，保持整体的商城简洁性哈。
