### ISSUE TITLE
交易订单教程中的流程图包含错误的状态

### ISSUE THREAD

**Issue by DevDengChao** [YunaiV/ruoyi-vue-pro#516]
### 基本信息

- ruoyi-vue-pro 版本：不相关
- 操作系统：不相关
- 数据库：不相关

### 你猜测可能的原因

不相关

### 复现步骤

![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/16363180/6b1a5ae4-3bcf-4589-bc1f-b30252858d95)

https://doc.iocoder.cn/mall/trade-order/#_1-%E8%AE%A2%E5%8D%95%E8%A1%A8 的图片中包含错误的流程状态, 买家付款后应该是 "已付款" 状态而不是 "待付款" 状态

### 报错信息

不相关

**Comment by YunaiV** [comment]
好的。我 fix 下文档哈。

**Comment by YunaiV** [comment]
已经 fix
