### ISSUE TITLE
没有找到datascope功能实现

### ISSUE THREAD

**Issue by daomoo** [YunaiV/ruoyi-vue-pro#52]
请问，目前这个模块的实现和ruoyi方式不同了吗

**Comment by YunaiV** [comment]
正在实现。
会不太一样，更加自动化~

**Comment by YunaiV** [comment]
https://github.com/YunaiV/ruoyi-vue-pro/tree/master/yudao-framework/yudao-spring-boot-starter-data-permission

已经实现，可见该组件

**Comment by daomoo** [comment]
有非常感谢。
