### ISSUE TITLE
教程网站上缺少对于支付渠道的 "渠道费率" 相关的介绍

### ISSUE THREAD

**Issue by DevDengChao** [YunaiV/ruoyi-vue-pro#520]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：2.1.0
- 操作系统：不相关
- 数据库：不相关

### 你猜测可能的原因

不相关

### 复现步骤

第一步，访问 https://doc.iocoder.cn/pay/build/#_1-%E6%A6%82%E8%BF%B0

第二步，搜索 "渠道费率" 相关内容

第三步，没找到

### 报错信息

![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/16363180/a48f1270-3f8b-477b-b45a-8f48bbda87d8)

**Comment by YunaiV** [comment]
已补充
