### ISSUE TITLE
微信支付渠道配置缺少可选的 merchantSerialNumber 配置项

### ISSUE THREAD

**Issue by DevDengChao** [YunaiV/ruoyi-vue-pro#521]
### 基本信息

- ruoyi-vue-pro 版本：2.1.0
- 操作系统：不相关
- 数据库：不相关

### 你猜测可能的原因

未能充分利用 https://github.com/Wechat-Group/WxJava 项目或未能及时跟进微信开放平台的更新.

### 复现步骤

第一步，在管理端添加微信支付渠道配置

第二步，发现需要 apiclient_cert.pem, 对比现有的历史项目与 [微信支付官方文档](https://pay.weixin.qq.com/docs/merchant/sdk-tools/quickstart-java.html), 发现并不需要该文件
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/16363180/b206f4e3-675b-4a57-8f49-ad7d2efe6e07)

### 报错信息

不相关

### 改进建议

允许开发者在 apiclient_cert.pem 和 merchant_serial_number 之间进行选择, 降低查看官方文档的开发者的上手难度.
同时, 存储证书序号要比存储证书公钥要节省更多数据库磁盘空间.

**Comment by YunaiV** [comment]
如果按照官方的文档，是不是说：
1. 去除 apiclient_cert.pem
2. 增加 merchant_serial_number

**Comment by DevDengChao** [comment]
是的，没错。

**Comment by YunaiV** [comment]
> 是的，没错。

好的，要不贡献下？

**Comment by DevDengChao** [comment]
周一吧

**Comment by YunaiV** [comment]
期待，搞的怎么样啦？

**Comment by YunaiV** [comment]
我看了下，还是只支持 certSerialNo 好点。配置越多，大家越不好理解。

**Comment by YunaiV** [comment]
已优化
