### ISSUE TITLE
启用支付渠道时无法复用已有的支付渠道配置

### ISSUE THREAD

**Issue by DevDengChao** [YunaiV/ruoyi-vue-pro#522]
### 基本信息

- ruoyi-vue-pro 版本：2.1.0
- 操作系统：不相关
- 数据库：不相关

### 你猜测可能的原因

不相关

### 复现步骤

第一步，在支付应用 a 中填写完支付宝原生支付相关配置

第二步，在支付应用 b 中尝试复用 a 已填写的配置

第三步，不能直接进行引用, 需要再次上传证书文件等

### 报错信息

不相关

### 改进建议

1. 服务端提取 pay_channel.config 字段到单独的表, 并新增 pay_channel.config_id 用于索引. 
2. 管理端允许在启用支付渠道时选择已保存的支付配置.

**Comment by YunaiV** [comment]
感谢建议哈。

目前暂时不考虑服用，和 https://www.pingxx.com/ 等商业化产品，保持一致。
