### ISSUE TITLE
无法平滑轮换支付渠道的配置

### ISSUE THREAD

**Issue by DevDengChao** [YunaiV/ruoyi-vue-pro#523]
### 基本信息

- ruoyi-vue-pro 版本：2.1.0
- 操作系统：不相关
- 数据库：不相关

### 你猜测可能的原因

不相关

### 复现步骤

第一步，支付应用 a 的支付宝原生支付被平台限制收款了, 无法用于创建新的订单, 但依然可以用于验证过往订单的回调

第二步，尝试在管理端更换应用 a 的支付宝原生支付渠道配置

第三步，引发潜在的订单回调校验异常

### 报错信息

不相关

### 改进建议

允许同一个支付渠道关联多个支付渠道配置, 以便开发者能够平滑的轮换支付渠道配置.

**Comment by YunaiV** [comment]
不错的建议哈。

短期内，暂时不做这个 feature 功能。原因是，不考虑过多增加这块的复杂性~

**Comment by DevDengChao** [comment]
这个功能对于企业来说十分重要，极大成度规避了支付平台突然封禁收款方式导致公司突然失去营收的问题。

**Comment by YunaiV** [comment]
恩恩，pr 前，微信先沟通哈

**Comment by YunaiV** [comment]
确认下整体的实现方案~
