### ISSUE TITLE
启动报错  'cn.iocoder.yudao.module.system.dal.mysql.dept.DeptMapper' that could not be found.

### ISSUE THREAD

**Issue by hackeryutu** [YunaiV/ruoyi-vue-pro#524]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

https://github.com/YunaiV/ruoyi-vue-pro/issues/472

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：2.1.0-jdk8-snapshot
- 操作系统：14.1.2 (23B92)
- 数据库：mysql8.0.36

### 你猜测可能的原因
试验过maven打jar包，使用java -jar yudao-server.jar --spring.profile.active=dev启动可以

idea启动不行,  
       试过手删target目录不行
       试过idea上点clean install package不行
       试过mvn clean install package不行
       试过File -> invalidate cache不行
       试过删掉.idea重新导入项目不行

### 报错信息

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2024-05-14 17:47:05.895 | ERROR 54816 | main [TID: N/A] o.s.b.d.LoggingFailureAnalysisReporter   | 

***************************
APPLICATION FAILED TO START
***************************

Description:

A component required a bean of type 'cn.iocoder.yudao.module.system.dal.mysql.dept.DeptMapper' that could not be found.

Action:

Consider defining a bean of type 'cn.iocoder.yudao.module.system.dal.mysql.dept.DeptMapper' in your configuration.

Disconnected from the target VM, address: '127.0.0.1:54441', transport: 'socket'

**Comment by YunaiV** [comment]
666 学习了
