### ISSUE TITLE
vue3 EMFILE: too many open files

### ISSUE THREAD

**Issue by yrj-essential** [YunaiV/ruoyi-vue-pro#527]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：yudao-ui-admin-vue3， 版本：2.0.1-snapshot
- 操作系统：windows

### 你猜测可能的原因
经自查，发现可能的原因是：一次导入的文件太多

### 复现步骤

第一步，npm run dev-server

### 报错信息
Error: EMFILE: too many open files
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/24262359/8657fd3a-2c6e-4bbd-825e-d6ebe468a7d9)

**Comment by YunaiV** [comment]
这个应该是操作系统的限制，建议调大可打开的文件数

**Comment by yrj-essential** [comment]
经过搜索，没有找到Windows下调大阈值的方法呢？
参考《Vue3使用了Vite和UnoCSS导致前端项目启动报错：Error：EMFILE：too many open files》（https://blog.csdn.net/u013810234/article/details/135031472）,配置uno.config.ts也不解决问题……
随机掉落这个问题，多试几次又能正常……大大，无法了，请帮忙看下呢。
