### ISSUE TITLE
单表生成时业务名包含 - 或 . 或 / 时会导致异常

### ISSUE THREAD

**Issue by DevDengChao** [YunaiV/ruoyi-vue-pro#529]
### 基本信息

- ruoyi-vue-pro 版本：2.1.0
- 操作系统：不相关
- 数据库：不相关

### 你猜测可能的原因

后端没有将业务名中的 - 和 / 替换成 . 
前端没有将 . 替换为 / 或 - .

### 复现步骤

第一步，新建 member_user_channel_config 表

第二步，登录到管理端, 选择单表生成

第三步，将默认的业务名 userchannelconfig 更改为 user.channel.config 以便后端生成的包名是 `user.channel.config` 而不是 `userchannelconfig`, 发现前端的 Vue3 代码不能正常生成

![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/16363180/9fd76ced-0fd4-4333-8422-6876baae54b8)

第四步, 将默认的业务名 userchannelconfig 更改为 user-channel-config 以便前端生成的文件以中划线分隔单词, 结果后端的包名里也有中划线
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/16363180/cfc93066-e089-4254-8e3f-debafba0d5a9)

第四步, 将默认的业务名 userchannelconfig 更改为 user/channel/config 以便前端生成的文件以文件夹分隔单词, 结果后端的包名里也有 /
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/16363180/325d67ee-53af-4af4-9597-a31cab3fcb9e)

### 报错信息

无

**Comment by YunaiV** [comment]
谢谢建议。

这个场景，我们暂时不考虑哈。比较少出现这个情况。

一般手动改下就好哈。

**Comment by DevDengChao** [comment]
![after](https://github.com/YunaiV/ruoyi-vue-pro/assets/16363180/7f36b221-6b12-4cc5-b6d1-50eb95eeb70d)
