### ISSUE TITLE
把定时任务关掉把！一启动cpu飙升到30%多

### ISSUE THREAD

**Issue by JGMa-java** [YunaiV/ruoyi-vue-pro#53]

**Comment by YunaiV** [comment]
什么配置的电脑？

定时任务去掉后，CPU 是 % 多少？

**Comment by JGMa-java** [comment]
cpu:i7 8750,内存16G,默认启动风扇狂转，cpu 单jvm占用30+%，你的任务不知道放哪里了，关了一些，降了一点，redissonMq最多



在 2021-12-27 09:26:41，"芋道源码" ***@***.***> 写道：

什么配置的电脑？

定时任务去掉后，CPU 是 % 多少？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JGMa-java** [comment]
最近这个版本才出现的，11月初虽然有定时任务跑，但是没有这个问题



在 2021-12-27 09:26:41，"芋道源码" ***@***.***> 写道：

什么配置的电脑？

定时任务去掉后，CPU 是 % 多少？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by YunaiV** [comment]
> cpu:i7 8750,内存16G,默认启动风扇狂转，cpu 单jvm占用30+%，你的任务不知道放哪里了，关了一些，降了一点，redissonMq最多

好的，我研究下。
跟 quartz 的定时任务，估计关系不大。
有可能是 redisson mq 导致的
