### ISSUE TITLE
在字典管理中只能新增字典字典类型，不能新增字典数据

### ISSUE THREAD

**Issue by MR-Robot271** [YunaiV/ruoyi-vue-pro#530]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：2.1.0
- 操作系统：不相关
- 数据库：MySQL

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：可能是版本更新删除了字典数据相关功能，我记得以前的版本是有的

### 复现步骤
直接看截图吧
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/56435346/c5d31637-4ef4-4309-941e-36b75fad5984)
这是以前的版本
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/56435346/66be35f7-a150-425b-92ca-32de088f93f1)
后端代码依然有dict-data模块
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/56435346/941c5399-7a11-4e7c-954d-b30b9bde04ad)

### 报错信息

我觉得原来这种增加字典数据的方式挺好的，为什么删了呢，或者是我使用过程有问题，请大佬指教

**Comment by YunaiV** [comment]
你点击【字典类型】那一列，可以跳转的

**Comment by MR-Robot271** [comment]
这样的啊 谢谢大佬！
