### ISSUE TITLE
【缺陷】由Druid连接验证缺陷导致若依使用Microsoft SQL Server数据库时抛出 java.sql.SQLException: validateConnection false 异常

### ISSUE THREAD

**Issue by ximinghui** [YunaiV/ruoyi-vue-pro#535]
### 基本信息

- ruoyi-vue-pro 版本：v2.1.0
- 操作系统：Windows 11 Pro (23H2, OS Build 22631.3593)
- 数据库：Microsoft SQL Azure (RTM) - 12.0.2000.8 | 相当于Microsoft SQL Server 2014

### 原因

由于 [Druid连接验证缺陷](https://github.com/alibaba/druid/issues/4451) 导致在使用 ```Microsoft SQL Server``` 数据库启动时抛出 ```java.sql.SQLException: validateConnection false``` 异常。

### 修复建议

临时方案：经测试将 ```druid``` 依赖项的版本由 ```1.2.21``` 降级为 ```1.2.20``` 来避免该缺陷对若依造成影响。

所在位置：https://github.com/YunaiV/ruoyi-vue-pro/blob/v2.1.0/yudao-dependencies/pom.xml#L26

**Comment by YunaiV** [comment]
https://gitee.com/zhijiantianya/ruoyi-vue-pro/pulls/968

关注这个 pr 解决哈
