### ISSUE TITLE
【欢迎认领】获取菜单精简信息列表接口没有排除父 ID 非 0 的节点

### ISSUE THREAD

**Issue by DevDengChao** [YunaiV/ruoyi-vue-pro#536]
### 基本信息

- ruoyi-vue-pro 版本：2.1.0
- 操作系统：不相关
- 数据库：不相关

### 复现步骤

第一步，将任意包含子菜单的根目录标记为不可用状态, 例如: 报表管理
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/16363180/e101c531-2a99-48e6-a633-cf5ef620873a)

第二步，生成代码时选择父菜单, 发现报表管理下的子菜单依然出现在候选项中
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/16363180/4c000858-1f43-446f-b182-4835a4840ece)

### 报错信息

不相关

### 改进建议

方案一: 更新父菜单可用状态时, 同步更新所有子菜单的可用状态. 缺点是可能会引发不必要的授权异常.
方案二: 在查询菜单列表时, 在服务端对菜单树进行构建, 将所有父 ID 非 0 的根菜单全部排除后返回给客户端. 缺点是管理端每次加载树的时候服务端都要重新进行一次过滤.

**Comment by YunaiV** [comment]
建议用方案二

因为我们历史的业务经验来说，可能会临时禁用掉某个菜单。后续可能又会开启。

**Comment by YunaiV** [comment]
好的哈。可以联系 wangwenbin-server

然后说下修复思路哈

**Comment by YunaiV** [comment]
感谢 @dongdongxiang 的修复
