### ISSUE TITLE
vue2的代码里请求bpm/task-assign-rule/list接口 404，经查看代码中确实没有这个接口

### ISSUE THREAD

**Issue by LvHuaiSheng** [YunaiV/ruoyi-vue-pro#538]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：最新版
- 操作系统：
- 数据库：mysql

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：代码缺少没有提交或vue2的前端代码没有修改，

### 复现步骤

第一步，
clone vue2-element 的vue前端代码，
第二步，
clone 最新后端代码
第三步，
 运行项目，访问前端【流程模型】点击【分配规则】即可复现
### 报错信息
{"timestamp":"2024-05-25 17:04:16","status":404,"error":"Not Found","message":"No message available","path":"/bpm/task-assign-rule/list"}
带上必要的截图
![图片](https://github.com/YunaiV/ruoyi-vue-pro/assets/35132878/0ad9bd42-9902-42dd-909e-802a363ceea6)
![图片](https://github.com/YunaiV/ruoyi-vue-pro/assets/35132878/610bd139-5bf2-4e19-9ec1-fd666f9e495f)

**Comment by YunaiV** [comment]
建议使用 vue3 管理后台哈

**Comment by YunaiV** [comment]
Vue2 在最新版本的后端接口，会有不兼容的几个接口，工作流这块
