### ISSUE TITLE
yudao-ui-admin dockerfile

### ISSUE THREAD

**Issue by ligang6383** [YunaiV/ruoyi-vue-pro#539]
### 基本信息

- ruoyi-vue-pro 版本：master
- 操作系统：windows
- 数据库：mysql

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：script > docker > Docker-HOWTO.md, yudao-ui-admin信息不全，

### 复现步骤

第一步，我使用[yudao-ui-admin-vue3](https://github.com/yudaocode/yudao-ui-admin-vue3)

第二步，在该目录下，我没有找到.dockerignore，Dockerfile，nginx.conf文件

第三步，导致我的docker-compose无法正常 运行。

### 报错信息

带上必要的截图

**Comment by YunaiV** [comment]
前端通过 nginx 部署

https://doc.iocoder.cn/deployment-linux/
