### ISSUE TITLE
【欢迎认领】工作流+数据权限后展示bug

### ISSUE THREAD

**Issue by zeno-sh** [YunaiV/ruoyi-vue-pro#540]
### 基本信息

- ruoyi-vue-pro 版本：master
- 操作系统：Mac
- 数据库：MySQL

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：设计问题

### 复现步骤
问题描述：开启了仅本人数据权限后，在工作流的【我的流程】页面，审批记录中看不到审批人是谁，隶属于哪个部门。查到的原因：在权限拦截这块，项目中内的dept数据拦截，会增加只允许查询自己的数据，导致最终无法查询task对应的owner信息。

第一步，
设置两个角色，运营（仅本人数据），主管（所有数据）
第二步，
运营提交一个审批流
第三步，
运营查看我的任务，结果无审批人、审批人部门信息
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/19320698/05775c0b-8111-47d9-abfd-c60f135249e1)
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/19320698/40997996-32e4-4418-9e67-fb0fb1bdd525)

**Comment by dongdongxiang** [comment]
@YunaiV 我想认领

**Comment by zby-fendou** [comment]
您好，请问您知道审批创建流程之后，发起人提起审批，这个审批实例在数据库那张表呢？就是假如审批填写名字为张三，电话号为123，这个张三和电话号在数据库那张表呢，请问您知道吗

**Comment by YunaiV** [comment]
已修复。
