### ISSUE TITLE
新需求，不是bug：国际化除了目前在前端比较通用或者公用的部分支持国际化配置文件之外，建议将业务部分中文语言国际化放在数据库表中，中间放在缓存中。

### ISSUE THREAD

**Issue by wwwityc** [YunaiV/ruoyi-vue-pro#542]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：所有版本
- 操作系统：部分系统
- 数据库：所有数据库

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：xxxxxx

新需求，不是bug：国际化除了目前在前端比较通用或者公用的部分支持国际化配置文件之外，建议将业务部分中文语言国际化放在数据库表中，中间放在缓存中。

**优点：可以将数据库中表中的国际化，放在界面中，方便随时更改和添加，并且不用重启系统就立即生效。

希望：在代码生成的时候，考虑到国际化部分

新建模块的数据库字段（中文）需要国际化，下拉列表（中文）需要国际化，报错信息（中文）需要国际化
都建议放在数据库（通过缓存）中**

### 复现步骤

第一步，无

第二步，无

第三步，无

### 报错信息
无

带上必要的截图
无

**Comment by YunaiV** [comment]
不错的建议哈。

国际化暂时不是大多数的诉求~ 虽然做进来可以增加项目的功能，但是反过来也增加了项目的复杂性。

所以，我们可能暂时不会支持这个~ sad but true~
