### ISSUE TITLE
不是bug，是需求，代码生成vue3的时候，2个建议

### ISSUE THREAD

**Issue by wwwityc** [YunaiV/ruoyi-vue-pro#543]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：所有
- 操作系统：所有
- 数据库：所有

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：xxxxxx

### 不是bug，是需求，代码生成vue3的时候，2个建议：
# 1.代码生成时候，列表中  可以生成代码为：可多选删除，首列为复选框
# 2.代码生成时候，列表可以支持表头可以排序，表头的宽度可以拖动修改
### 复现步骤

第一步，无

第二步，无

第三步，无

### 报错信息
无
带上必要的截图
无

**Comment by YunaiV** [comment]
1、支持多选删除，最近有考虑这块。

不过还没确定要不要支持。

实现难度不大，但是不确定多少业务需要哈

**Comment by YunaiV** [comment]
2、表头排序，也是有类似 1 的情况。

less is more~ 

从可能性来说，1 > 2

**Comment by YunaiV** [comment]
综合考虑了下，先暂时不搞了。

后续有想贡献的同学，可以回复该 issue
