### ISSUE TITLE
请问在这个项目中，一对多的分页查询怎么写

### ISSUE THREAD

**Issue by Brunofan** [YunaiV/ruoyi-vue-pro#549]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：2.1.0
- 操作系统：windows
- 数据库：ruoyi-vue-pro

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：比如一个学生有多个成绩。   没有看到项目中有类似的一对多查询。大体的思路是不是如下：
1. 先分页查询学生表的数据集合studentList
2. 拿到上一步中的学生id集合ids
3. 用ids在成绩表中查询，获得到成绩List
4. 把这两个拼接在一起。

### 复现步骤

第一步，

第二步，

第三步，

### 报错信息

带上必要的截图

**Comment by YunaiV** [comment]
在 ERP 模块，搜 selectJoinPage 相关的，有这块的示例

另外，各种联表可见 https://doc.iocoder.cn/mybatis-pro/ 文档
