### ISSUE TITLE
excel下载格式变成了zip

### ISSUE THREAD

**Issue by aboluo-gy** [YunaiV/ruoyi-vue-pro#55]
使用ExcelUtils的write方法生成Excel,调用后生成的是zip不是xlsx
https://github.com/alibaba/easyexcel/issues/225
  大佬的注释说明
// 设置 header 和 contentType。写在最后的原因是，避免报错时，响应 contentType 已经被修改了

实际使用情况：
调用后生成的是zip不是xlsx，先设置 header 和 contentType再下载，下载即可正常变成xlsx

**Comment by YunaiV** [comment]
get，我研究下。

**Comment by YunaiV** [comment]
最近测试了下，没有这个问题噢，可以拉下最新的代码哈。

**Comment by kissIce** [comment]
我也碰到了相同的问题，好像是因为没有成功添加文件头和响应内容。具体可以复现
首先我写了方法往官方示例表 添加了 100w的假数据



然后用官方示例代码的导出，导出后响应头并没有设置的文件名及响应类型
