### ISSUE TITLE
数据权限仅本人可看Bug

### ISSUE THREAD

**Issue by gaokaoli** [YunaiV/ruoyi-vue-pro#553]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：2.0.1
- 操作系统：win11
- 数据库：mysql8

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：xxxxxx

### 复现步骤

第一步，

第二步，

第三步，

### 报错信息

带上必要的截图

**为啥设置数据权限仅本人可看，但是登录另外一个账号（同样配置），也可看到刚刚上一个人设置的数据**

**Comment by YunaiV** [comment]
通读下 https://doc.iocoder.cn/data-permission/ 文档
确认下，该数据，是否配置了数据权限的字段

**Comment by gaokaoli** [comment]
> 通读下 https://doc.iocoder.cn/data-permission/ 文档 确认下，该数据，是否配置了数据权限的字段

基于部门的数据权限没大看懂，是在自已的表中多添加下dept_id字段之后，怎么在做衔接呢
