### ISSUE TITLE
前端【yudao-ui-admin-vue2】无法修改NODE_ENV为production

### ISSUE THREAD

**Issue by 980961628** [YunaiV/ruoyi-vue-pro#556]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：yudao-ui-admin-vue2
- 操作系统：window11
- 数据库：

### 你猜测可能的原因

项目打包上线后，发现 process.env.NODE_ENV 一直为development，
我花费了一整天各种测试，始终无法修改成功。
vue_cli官网中说在.env文件中配置 NODE_ENV = production即可，但是yudao-ui-admin-vue2的.env文件中是这样配置的：ENV = production，所以打包后环境变量并没有修改成功，我试过把ENV改成NODE_ENV，结果项目运行不了。
请问ruoyi为什么要将NODE_ENV改成ENV去设置？如何才能将环境变量改成production？

![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/28433061/45f4f7ae-1aee-496c-a946-14c244f09904)
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/28433061/871e4963-84c8-45ab-97a8-fcf9b71a9b4b)

### 复现步骤
在mian.js打印process.env.NODE_ENV，打包上线后，始终输出的是development

### 报错信息

没有报错信息

**Comment by YunaiV** [comment]
保持和 ruoyi-vue 一致兼容，所以这块用了 ENV
