### ISSUE TITLE
文件管理部署后加载不了图片

### ISSUE THREAD

**Issue by anchyobi** [YunaiV/ruoyi-vue-pro#557]
用的java17单体版，本地文件管理没问题，但是部署到线上，文件可以上传，但是文件无法加载，用的测试七牛云直接用地址可以加载出图片，但是在站内就是加载失败，这是什么问题

**Comment by YunaiV** [comment]
七牛配置的是自己的么？

**Comment by anchyobi** [comment]
> 七牛配置的是自己的么？

是默认的，直接访问是可以，在站内就不行

**Comment by anchyobi** [comment]
![cb1830960bc558291aa3305d88499e8](https://github.com/YunaiV/ruoyi-vue-pro/assets/30885206/8e33f97b-7150-47d8-99f2-4b3895353529)
![605aa36704eff38662b5f2b0fe28739](https://github.com/YunaiV/ruoyi-vue-pro/assets/30885206/b8dd2225-a000-4003-b0b5-d6d5eb7fc8a1)

**Comment by YunaiV** [comment]
= = 要配置自己的啊。。。

用默认的，不是把默认的账户余额给打爆了呀。

为了避免这个情况，我设置了只允许 127.0.0.1 使用。。。

**Comment by anchyobi** [comment]
> = = 要配置自己的啊。。。
> 
> 用默认的，不是把默认的账户余额给打爆了呀。
> 
> 为了避免这个情况，我设置了只允许 127.0.0.1 使用。。。

不是的，我基本不用七牛，只是对比测试了下，我的意思是本地环境能加载，无论是磁盘还是数据库存储都行，一旦部署到线上，测试上传也显示成功了，但访问/admin-api/infra/file/*/get/**这个接口就404了，请问这个是我的配置有问题吗

**Comment by YunaiV** [comment]
> 不是的，我基本不用七牛，只是对比测试了下，我的意思是本地环境能加载，无论是磁盘还是数据库存储都行，一旦部署到线上，测试上传也显示成功了，但访问/admin-api/infra/file/*/get/**这个接口就404了，请问这个是我的配置有问题吗

应该是的。建议自查下哈。

**Comment by YunaiV** [comment]
建议 https://doc.iocoder.cn/file/ 通读下，看看有没哪里配置不对

**Comment by anchyobi** [comment]
应该是nginx配置问题，按照文档写的代理不到http://localhost:48080/admin-api/,写成这样就行了location ~* ^/(admin-api|app-api) {}
