### ISSUE TITLE
能针对不同的功能配置不同的数据权限吗

### ISSUE THREAD

**Issue by anchyobi** [YunaiV/ruoyi-vue-pro#564]
简单配置的情况下，角色数据权限能不能实现某个功能只看个人数据，某个功能看到部门的数据？
我尝试新建了2个角色，数据权限分别设置未个人和部门，配置到一个账号，但是系统默认只认第一个角色的数据权限。
是不是要按照文档自定义的数据权限规则才行

**Comment by YunaiV** [comment]
https://t.zsxq.com/rD4pQ

我提供了实现思路
