### ISSUE TITLE
是不是应该把 getByGranType  命名成 getByGrantType 

### ISSUE THREAD

**Issue by kokodayou2000** [YunaiV/ruoyi-vue-pro#567]
https://github.com/YunaiV/ruoyi-vue-pro/blob/41ea482f8db6bae07cc7fe8bd042b364ec154362/yudao-module-system/yudao-module-system-api/src/main/java/cn/iocoder/yudao/module/system/enums/oauth2/OAuth2GrantTypeEnum.java#L25

**Comment by YunaiV** [comment]
拼写错了，来个 pr 否！

**Comment by kokodayou2000** [comment]
> 拼写错了，来个 pr 否！

我尝试按照教程完成一个pr，希望没有出现问题

**Comment by YunaiV** [comment]
> > 拼写错了，来个 pr 否！
> 
> 我尝试按照教程完成一个pr，希望没有出现问题

蛮好的哈。pull request 是必须掌握的基本功

**Comment by kokodayou2000** [comment]
> > > 拼写错了，来个 pr 否！
> > 
> > 
> > 我尝试按照教程完成一个pr，希望没有出现问题
> 
> 蛮好的哈。pull request 是必须掌握的基本功

谢谢大佬，我希望能在将来更多的参与这个项目😘
