### ISSUE TITLE
【欢迎认领】商城模块添加/修改商品规格报错

### ISSUE THREAD

**Issue by Colin07** [YunaiV/ruoyi-vue-pro#570]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：2.1.0
- 操作系统：windows 11
- 数据库：mysql 5.7

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：代码存在逻辑缺陷

### 复现步骤

第一步，点击修改商品，选择多规格

第二步，添加规格

第三步，点击批量添加 和保存 均报错

### 报错信息
![367c9906e8a1dcc3d3e4c98b8cfaaa8b](https://github.com/YunaiV/ruoyi-vue-pro/assets/30275465/d8382786-23d7-4585-9cfb-6f8f86270820)

带上必要的截图
![3bf09e4037b0548b92c32c177d04f442](https://github.com/YunaiV/ruoyi-vue-pro/assets/30275465/049bd486-b493-472e-b276-a31942a70cd2)

![73581482707eb7f008f6f0e6f57acc47](https://github.com/YunaiV/ruoyi-vue-pro/assets/30275465/1c50f272-9683-4fde-a51f-8929203f725e)

**Comment by YunaiV** [comment]
属性没添加。

不过可以加个校验，稳一点

**Comment by YunaiV** [comment]
加了个校验，妥了
