### ISSUE TITLE
大神好-v2.1.0(jdk17/21)分支的代码版本不对

### ISSUE THREAD

**Issue by DoubleLeo** [YunaiV/ruoyi-vue-pro#576]
### 问题描述：
v2.1.0(jdk17/21)分支的代码版本是jdk1.8，切springboot不是3.2版本。

### 基本信息

- ruoyi-vue-pro 版本：v2.1.0(jdk17/21)

带上必要的截图
![70087af1b749f764fbbaed932f52586](https://github.com/YunaiV/ruoyi-vue-pro/assets/3361414/e7d25366-9fb9-47eb-93a2-c45f9bd5940d)

**Comment by YunaiV** [comment]
好像是的。。。

可以直接拉 jdk17 分支，这块要等我下次发版解决下
