### ISSUE TITLE
验证码更换底层图片错误

### ISSUE THREAD

**Issue by no-orange** [YunaiV/ruoyi-vue-pro#577]
### 基本信息

- ruoyi-vue-pro 版本：2.0.1-snapshot
- 操作系统：win11、linux
- 数据库：mysql5.0

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：文档不全，漏描述

### 复现步骤

第一步，根据文档说明，更改resouces/images/jigsaw/original/ 下的图片为我自己的图片
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/80766973/8bf0b168-438a-4eb1-86a8-0f1b97660125)

第二步，修改图片名称保持和原来一致
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/80766973/a150dd6e-7665-4b3b-84ac-880dbec5dcbd)

第三步，重启服务

### 报错信息
报错一：图片显示失败
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/80766973/62c00cdc-86ca-44c5-b032-0b9368b41448)
报错二：不显示正确区块位置
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/80766973/48e78911-0be3-40e2-8b48-1bc6cfd04bc8)

**Comment by YunaiV** [comment]
需要图片的分辨率，是正确的哈。
