### ISSUE TITLE
DateTime精度问题导致测试断言对象相等不通过

### ISSUE THREAD

**Issue by tshwangq** [YunaiV/ruoyi-vue-pro#578]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：源代码Main 分支
- 操作系统：Windows
- 数据库：MySql 8.0.33

### 你猜测可能的原因

  时间精度不一致

### 复现步骤

第一步,  git clone 最新的代码

第二步，进入项目目录， 运行 mvn clean package -X

### 报错信息

[ERROR] Failures:
[ERROR]   OAuth2ApproveServiceImplTest.testGetApproveList:212 Field(expiresTime) 不匹配 ==> expected: <2024-06-25T15:43:44.204956700> but was: <2024-06-25T15:43:44.204957>
[ERROR]   OAuth2CodeServiceImplTest.testConsumeAuthorizationCode_success:95 Field(expiresTime) 不匹配 ==> expected: <2024-06-25T15:43:46.011518300> but was: <2024-06-25T15:43:46.011518>
[ERROR]   OAuth2CodeServiceImplTest.testCreateAuthorizationCode:53 Field(expiresTime) 不匹配 ==> expected: <2024-06-24T15:48:46.035170800> but was: <2024-06-24T15:48:46.035171>
[ERROR]   OAuth2TokenServiceImplTest.testCheckAccessToken_success:240 Field(expiresTime) 不匹配 ==> expected: <2024-06-25T15:43:47.675418900> but was: <2024-06-25T15:43:47.675419>
[ERROR]   OAuth2TokenServiceImplTest.testCreateAccessToken:80 Field(expiresTime) 不匹配 ==> expected: <2024-06-24T15:44:17.979688600> but was: <2024-06-24T15:44:17.979689>
[ERROR]   OAuth2TokenServiceImplTest.testGetAccessToken:201 Field(expiresTime) 不匹配 ==> expected: <2024-06-25T15:43:47.959763900> but was: <2024-06-25T15:43:47.959764>
[ERROR]   OAuth2TokenServiceImplTest.testRefreshAccessToken_success:180 Field(expiresTime) 不匹配 ==> expected: <2024-06-24T15:44:17.879704500> but was: <2024-06-24T15:44:17.879705>
[ERROR]   OAuth2TokenServiceImplTest.testRemoveAccessToken_success:262 Field(expiresTime) 不匹配 ==> expected: <2024-06-25T15:43:47.999152500> but was: <2024-06-25T15:43:47.999153>

**Comment by YunaiV** [comment]
windows11 貌似会碰到这个问题，可以暂时忽略这个单测噢。

https://github.com/YunaiV/ruoyi-vue-pro/pull/491
