### ISSUE TITLE
代码生成模块功能bug，Mapper中生成的接口不全

### ISSUE THREAD

**Issue by jiushinakecai** [YunaiV/ruoyi-vue-pro#579]
### 基本信息

- ruoyi-vue-pro 版本：latest master分支
- 操作系统：win10
- 数据库：mysql 5.7

### 你猜测可能的原因

代码生成模块功能bug，StudentGradeMapper中未生成对应的接口

### 复现步骤

第一步，按“后端手册-代码生成【主子表】”步骤生成代码，选择“**主表（ERP 模式）**”，其余步骤完全和文档一样
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/60872522/2f7e2d4a-4039-4ff6-9626-239ea0f2ad72)
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/60872522/039dbf13-bb08-449b-b0b7-0d0be7541b0f)

第二步，在项目中导入代码后，出现报错，StudentGradeMapper中并末生成selectByStudentld接，如下图
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/60872522/654d46a8-56fe-42b1-9356-5d05f347a530)
代码预览
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/60872522/0b100379-84d9-4d56-846b-13cfcdb246a2)
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/60872522/b0107b45-e17d-4a83-ad8f-b6ad22fc61c4)

第三步，在StudentGradeMapper中加上对应接口后报错解决，但是代码生成模块太复杂，不知道去哪里改
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/60872522/06be17f0-ddb5-470a-b60e-2f98c1214926)

### 报错信息
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/60872522/a387d981-e100-4922-8819-699d3be80dd3)

**Comment by jiushinakecai** [comment]
问题已解决，在mapper生成模版中补充主表与子表一对一时的情况即可，如下图
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/60872522/14af72f3-0a1f-45aa-90b1-8fe33420dcfc)

## 情况一：MASTER_ERP 时，需要分查询页子表
### 主表与子表是一对一时
` 
`##` 主表与子表是一对一时 `<br>`
#if (!$subTable.subJoinMany)`<br>`
`&nbsp;&nbsp;`default ${subTable.className}DO selectBy${SubJoinColumnName}(${subJoinColumn.javaType} ${subJoinColumn.javaField}) {`<br>`
 `&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`return selectOne(${subTable.className}DO::get${SubJoinColumnName}, ${subJoinColumn.javaField});`<br>`
`&nbsp;&nbsp;` }`<br>`
}`<br>`
 #end
`

**Comment by YunaiV** [comment]
有没兴趣，pull request 下哈

**Comment by jiushinakecai** [comment]
> 有没兴趣，pull request 下哈
好的哟
