### ISSUE TITLE
工作流这块还不能用，后期是否还会加强？对于工作流，大部分需要消息通知，是否后面有websocket消息组件加入。

### ISSUE THREAD

**Issue by peiguihuang** [YunaiV/ruoyi-vue-pro#58]
工作流这块还不能用，后期是否还会加强？对于工作流，大部分需要消息通知，是否后面有websocket消息组件加入。

**Comment by YunaiV** [comment]
> 工作流这块还不能用，后期是否还会加强？对于工作流，大部分需要消息通知，是否后面有websocket消息组件加入。

这块有在规划，会有一个消息发送配置，优先级不会特别高。

每个公司的消息通知模型不太一样，大象、钉钉、短信、邮件都有可能，所以真正开始做，也要等这几个基础设施都接好哈。

**Comment by YunaiV** [comment]
目前先接入了短信通知，在流程被通过、不通过，以及任务被分配给指定人时，进行通知；
未来应该不会去支持 websocket 的通知，还是会考虑钉钉、企业微信等等；
另外，websocket 的组件会提供~
