### ISSUE TITLE
新需求，不是bug，商城模块添加商品预售功能

### ISSUE THREAD

**Issue by Lcxuan** [YunaiV/ruoyi-vue-pro#580]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：
- 操作系统：
- 数据库：

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：xxxxxx
新需求，不是bug，商城模块有计划添加商品预售的功能吗？

### 复现步骤

第一步，

第二步，

第三步，

### 报错信息

带上必要的截图

**Comment by YunaiV** [comment]
目前看需要的人不多。

等未来需要的人多，可能会考虑增加哈。
