### ISSUE TITLE
有什么办法可以简单的在项目中去除redis不连接redis也能运行（预计 Q3 支持）

### ISSUE THREAD

**Issue by Rosejacka** [YunaiV/ruoyi-vue-pro#584]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：最新
- 操作系统：
- 数据库：mysql

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：去掉redis难度有点大

### 复现步骤

第一步，

第二步，

第三步，

### 报错信息

带上必要的截图

**Comment by YunaiV** [comment]
不错的建议，预计 Q3 会支持。

**Comment by YunaiV** [comment]
https://doc.iocoder.cn/remove-redis/

已经支持
