### ISSUE TITLE
我是后端 想在本地运行前端项目 无法通过官方文档给出的启动流程运行项目

### ISSUE THREAD

**Issue by sannan28** [YunaiV/ruoyi-vue-pro#586]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：yudao-ui-admin-vue3 / yudao-ui-admin-vue2 
- 操作系统：mac os 10.13.6
- 数据库：

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：目前尝试使用过的node 版本有16.x 14.x 12.x 10.x  ，发现低版本的node无法运行前端项目

### 复现步骤

参考前端运行启动文档  https://doc.iocoder.cn/quick-start-front/#%F0%9F%91%8D-%E7%9B%B8%E5%85%B3%E8%A7%86%E9%A2%91%E6%95%99%E7%A8%8B
npm run dev/ npm run local

### 报错信息
Syntax Error: Unexpected token, expected "," (1:8)

> 1 | [object Promise]
    |         ^
  2 | export { render, staticRenderFns }
    at parser.next (<anonymous>)
    at normalizeFile.next (<anonymous>)
    at run.next (<anonymous>)
    at transform.next (<anonymous>)
    at runMicrotasks (<anonymous>)

 @ ./src/views/system/user/profile/userSocial.vue?vue&type=template&id=34c563bc& 1:0-557 1:0-557
 @ ./src/views/system/user/profile/userSocial.vue
 @ ./src/views sync ^\.\/.*$
 @ ./src/store/modules/permission.js
 @ ./src/store/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://10.1.183.57:1024&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

带上必要的截图
![前端报错截图](https://github.com/YunaiV/ruoyi-vue-pro/assets/32167053/e2767d25-2590-4fef-8075-05f446fc6d94)

**Comment by YunaiV** [comment]
如果是 vue3 ，使用 node 18
如果是 vue2，使用 node 12、14
