### ISSUE TITLE
基础设施文件上传数据库设计疑问

### ISSUE THREAD

**Issue by ion1ze** [YunaiV/ruoyi-vue-pro#587]
### 基本信息

- ruoyi-vue-pro 版本：master-jdk17-2.1.0
- 操作系统：Windows 11
- 数据库：MySQL 5.7

### 你猜测可能的原因

基础设施文件上传我看 FileDO 继承了 BaseDO，所以使用默认的字段填充规则，填充的使用的是当前登录的用户id，System 用户和 Member 用户貌似会编号会混淆吧。基础设施是不是不应该携带这个字段，然后如果要追溯，是不是需要分别单独创建 System 用户和 Member 用户的文件上传记录表。

### 复现步骤

第一步，Member 用户上传文件

第二步，Admin 用户上传文件

### 报错信息

无

**Comment by YunaiV** [comment]
或者增加一个 user_type 字段
