### ISSUE TITLE
重复校验

### ISSUE THREAD

**Issue by yangzehan** [YunaiV/ruoyi-vue-pro#588]
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/76773988/f6343d3a-fa63-4932-b1ed-5196ee8c9418)
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/76773988/f6f43ec1-c985-45a0-8aaf-fc19ca2fe840)
官网这里是表示注册为bean会导致spring调一次Spring Security？

**Comment by YunaiV** [comment]
不会噢
