### ISSUE TITLE
数据权限存在严重问题，会导致权限失效（看到了不属于自己的数据）

### ISSUE THREAD

**Issue by Loren1999** [YunaiV/ruoyi-vue-pro#589]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：master-jdk17
- 操作系统：windows11
- 数据库：postgresql16.2

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：cn.iocoder.yudao.framework.datapermission.core.aop.DataPermissionContextHolder 类中使用了TransmittableThreadLocal，代码如下：

private static final ThreadLocal<LinkedList<DataPermission>> DATA_PERMISSIONS =
            TransmittableThreadLocal.withInitial(LinkedList::new);

并发情况下会导致权限失效（看到了不属于自己的数据）
同时该类下 remove 方法会抛出无法移除数据的异常（栈内数据为空）

将本类中 TransmittableThreadLocal 更换为 ThreadLocal后正常
### 复现步骤

第一步，创建一个接口，并使用数据权限注解

第二步，建立一个角色，为该角色配置数据权限（可查看本部门及以下的权限）

第三步，使用JMeter进行接口调用，（配置token）创建线程组并发调用该接口

### 报错信息

带上必要的截图
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/20633409/1ddcafd1-d0d7-4726-ab0e-7a248fc8959c)
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/20633409/e5db15d4-88ff-49f6-bc90-62998a7b970f)
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/20633409/6d460993-2d42-496e-91d6-e21f6f5b208a)
![image](https://github.com/YunaiV/ruoyi-vue-pro/assets/20633409/09c222ce-82f9-4825-8bdf-d4aa543ba924)

**Comment by Loren1999** [comment]
最新版本测试后已无该问题

**Comment by YunaiV** [comment]
> 最新版本测试后已无该问题

被发现了。嘿嘿。

周末疯狂思考修复了下~

**Comment by lawrence-peng** [comment]
系统增加了 rule.addUserColumn(OrderDO.class, "creator")， 系统运行一会，有发现SQL不拼接 creator 的情况，导致其它的人数据查出来了，重启后问题消失，应该是框架问题，需要进一步排查

**Comment by YunaiV** [comment]
> 系统增加了 rule.addUserColumn(OrderDO.class, "creator")， 系统运行一会，有发现SQL不拼接 creator 的情况，导致其它的人数据查出来了，重启后问题消失，应该是框架问题，需要进一步排查

哪个版本的代码？

**Comment by lawrence-peng** [comment]
jdk17 、 2.1.0-snapshot 的版本

**Comment by YunaiV** [comment]
> jdk17 、 2.1.0-snapshot 的版本

使用 2.3.0 

这块 fix 过。

**Comment by lawrence-peng** [comment]
请问在项目中如何安全升级到 2.3.0 。项目中用的是mini那个版本
