### ISSUE TITLE
工作流（业务表单）数据权限问题

### ISSUE THREAD

**Issue by javachens** [YunaiV/ruoyi-vue-pro#590]
- ruoyi-vue-pro 版本：最新
- 操作系统：Win10
- 数据库：MySQL8

业务表单模式下的工作流，提交审核之后工作流的审核人员在打开审核进度进行审核时，表单详情页面加载不了数据，后台debug发现没有相应的（read 2）权限给到当前审批的用户，造成没有查询业务表单的权限
    @Override
    @CrmPermission(bizType = CrmBizTypeEnum.CRM_CONTRACT, bizId = "#id", level = CrmPermissionLevelEnum.READ)
    public CrmContractDO getContract(Long id) {
        return contractMapper.selectById(id);
    }
我想问下这个地方代码需要怎么处理给到审批流上响应人权限？流程模型创建时候分配规则有岗位、角色等类型，并不一定是具体到人，但是这个地方查询拦截时候校验的是当前用户的权限（crm_permission表里存储的当前用户对应的数据类型biz_type、数据编号biz_id）,所以这个地方有点迷茫了，我只知道在业务表单提交审核时候会给当前用户插入了一条负责人的权限进入

**Comment by YunaiV** [comment]
对的。业务表单，会存在数据权限没有的情况。

我们在公司里的实践，也是要求去开通对应的权限哈。

**Comment by wxbdsssssss** [comment]
有个问题， 审批人 应该是默认自动有这个权限的，要不然这个工作流是有问题的，他都没权限 他能审批个蛋，如果要主动把他添加到客户团队联系人中去，那这个审批人离职了，要删除多少个关联关系？
