### ISSUE TITLE
bpm相关sql不存在

### ISSUE THREAD

**Issue by huangjunGo** [YunaiV/ruoyi-vue-pro#591]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：master&bpm
- 操作系统：mac
- 数据库：mysql

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：未上传

### 复现步骤

第一步，导入项目，结合DO定义搜索相关表，提示无结果，eg bpm_process_definition_info 

第二步，
有sql的两个地方 ，都人肉确认了下，也没有，bmp-module下的sql只有3张表

第三步，

### 报错信息

带上必要的截图
![image](https://github.com/user-attachments/assets/2a1a63c8-682c-4f85-bc49-768b42ba4feb)
![image](https://github.com/user-attachments/assets/4bf9bffb-f1dc-41aa-9c60-89dae04ad914)

**Comment by YunaiV** [comment]
https://doc.iocoder.cn/bpm/

**Comment by hkdwolf** [comment]
代码开源，但很多模块不提供SQL，需要付费加入星球下载
