### ISSUE TITLE
java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to cn.iocoder.yudao.module.trade.dal.dataobject.order.TradeOrderItemDO$Property

### ISSUE THREAD

**Issue by smwsk** [YunaiV/ruoyi-vue-pro#593]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：
- 操作系统：window
- 数据库：mysql

### 你猜测可能的原因

应该是环境问题
List<TradeOrderItemDO.Property> list 在传递的过程中对象变成了LinkedHashMap

### 复现步骤

第一步，
商城系统模块，点击订单列表
第二步，

第三步，

### 报错信息
ava.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to cn.iocoder.yudao.module.trade.dal.dataobject.order.TradeOrderItemDO$Property
	at cn.iocoder.yudao.module.trade.convert.order.TradeOrderConvertImpl.propertyListToProductPropertyValueDetailRespVOList(TradeOrderConvertImpl.java:748)
带上必要的截图
![1721357137810](https://github.com/user-attachments/assets/9c3847ac-b1b8-4d6e-af78-b01bdb9a9956)

**Comment by YunaiV** [comment]
测试了下，暂时没碰到哈。

猜测可能是你 maven 没刷新下。最新版本的 mybatis plus 可以基于 field 解析了
