### ISSUE TITLE
新增菜单问题

### ISSUE THREAD

**Issue by MrKaGod** [YunaiV/ruoyi-vue-pro#595]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：
- 操作系统：win10
- 数据库：mysql8

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：xxxxxx

### 复现步骤

第一步，

第二步，

第三步，

### 报错信息
新增菜单后，需要重新登录之后，菜单才会显示，这是算bug还是设计如此啊？
带上必要的截图

**Comment by YunaiV** [comment]
设计如此。

目的是，刷新界面的时候，不用从后端读取，提升速度
