### ISSUE TITLE
there is one Arbitrary file read vulnerability

### ISSUE THREAD

**Issue by LockeTom** [YunaiV/ruoyi-vue-pro#597]
Chinese version：
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：<=v2.1.0
- 操作系统：linux
- 数据库：mysql

### 你猜测可能的原因

由于用户可在管理台中配置数据库连接，且应用会访问该链接，结合此前mysql-connector-j包中由于外部攻击者可控制jdbc连接串导致的任意文件读取漏洞

### 复现步骤

第一步，
登录管理台，在数据源配置中选择新增数据源，此数据源连接为恶意的数据库地址
<img width="879" alt="image" src="https://github.com/user-attachments/assets/e153095b-eea2-4846-8712-9e52bc212a7f">

第二步，
点击确认后，会提示“数据源配置不正确，无法进行连接”，恶意数据库参考：https://github.com/Al1ex/Rogue-MySql-Server
<img width="1186" alt="image" src="https://github.com/user-attachments/assets/30712fe3-d25e-4318-b303-44da032480b5">

第三步，
查看我们的恶意服务器接受到的数据，可发现已读取到/etc/passwd文件
<img width="1333" alt="image" src="https://github.com/user-attachments/assets/d42e4127-1e88-4069-90f3-58bedc62ac4e">

English version：
- ruoyi-vue-pro version：<=v2.1.0
- operating system：linux
- database：mysql

Steps to reproduce：
Step 1，
Log in to the console and select Add Data Source in the Data Source Configuration, which is connected to a evil jdbc url
<img width="879" alt="image" src="https://github.com/user-attachments/assets/e153095b-eea2-4846-8712-9e52bc212a7f">

Step 2，
After clicking Confirm, a message will be displayed saying "The data source is not configured correctly, and the connection cannot be made"；the evil database code：https://github.com/Al1ex/Rogue-MySql-Server
<img width="1186" alt="image" src="https://github.com/user-attachments/assets/30712fe3-d25e-4318-b303-44da032480b5">

Step 3，
Looking at the data received by our malicious server, we can see that the /etc/passwd file has been read
<img width="1333" alt="image" src="https://github.com/user-attachments/assets/d42e4127-1e88-4069-90f3-58bedc62ac4e">

### 报错信息

带上必要的截图

**Comment by YunaiV** [comment]
我测试了下，貌似暂时没碰到
