### ISSUE TITLE
API访问日志，无法记录query的问题

### ISSUE THREAD

**Issue by MyGitHubPigStar** [YunaiV/ruoyi-vue-pro#599]
### 基本信息

- ruoyi-vue-pro 版本：2.1.0(java8版本)
- 操作系统：MAC  M1
- 数据库：mysql

### 你猜测可能的原因
 编码错误，把代码中的isNotEmpty 更改为 isEmpty 即可

### 复现步骤

第一步，打开项目全局搜索sanitizeMap，即可找到相应方法。
`    // ========== 请求和响应的脱敏逻辑，移除类似 password、token 等敏感字段 ==========

    private static String sanitizeMap(Map<String, ?> map, String[] sanitizeKeys) {
        if (CollUtil.**isNotEmpty**(map)) { 
            return null;
        }
        if (sanitizeKeys != null) {
            MapUtil.removeAny(map, sanitizeKeys);
        }
        MapUtil.removeAny(map, SANITIZE_KEYS);
        return JsonUtils.toJsonString(map);
    }`

### 报错信息
无报错信息，只是无法正常执行，返回null.

**Comment by YunaiV** [comment]
已修复，谢谢。晚点 pr 上来。
