### ISSUE TITLE
S3FileClient 的问题

### ISSUE THREAD

**Issue by travisbikkle** [YunaiV/ruoyi-vue-pro#600]
### 问题一
我看了一下 S3FileClient.java 的写法，这里返回的 url 会给商城装修界面直接用，也就是说在商城也可以直接看到，岂不是没法防止盗刷流量？

```java
    public String upload(byte[] content, String path, String type) throws Exception {
        // 执行上传
        client.putObject(PutObjectArgs.builder()
                .bucket(config.getBucket()) // bucket 必须传递
                .contentType(type)
                .object(path) // 相对路径作为 key
                .stream(new ByteArrayInputStream(content), content.length, -1) // 文件内容
                .build());
        // 拼接返回路径
        return config.getDomain() + "/" + path;
    }
```

### 问题二

目前不支持aws或者aws中国，是吗？因为我看到region没有设置，并且也没有任何 presigned 预签名相关的代码。

**Comment by YunaiV** [comment]
问题一：https://help.aliyun.com/document_detail/362059.html

防盗刷，一般还是 referer 为主。

**Comment by YunaiV** [comment]
问题二：
你可以试下 aws 公开 bucket 可以不。有问题，可以具体提。

**Comment by travisbikkle** [comment]
我试了一下，aws不行，minio 直接报错。
加上 region 好了，可以上传到桶中。
但是 aws 的公开桶，仍然需要预签名 url 才能访问，而 minio client 生成的预签名地址缺少 aws 需要的一些字段，所以 aws 可以认为是走不通了。
就算预签名 url 能用了，它现在的接口只能最多设置 7 天有效期。7天后，保存到数据库中的 file url 都不能用了，要大改。

**Comment by YunaiV** [comment]
好的。下个版本，我申请个 aws 测试下这块哈

**Comment by YunaiV** [comment]
你那方便提供一个 aws s3 账号么？

**Comment by YunaiV** [comment]
已替换 https://gitee.com/zhijiantianya/ruoyi-vue-pro/pulls/1117
aws client sdk。

“aws 的公开桶，仍然需要预签名 url 才能访问”
我搜了下资料，貌似说不需要哈。
