### ISSUE TITLE
[Bug]: 工作流部门领导审批报错(用户部门权限问题)

### ISSUE THREAD

**Issue by yihao5un** [YunaiV/ruoyi-vue-pro#606]
### 基本信息

- ruoyi-vue-pro 版本：master-jdk17
- 操作系统：Windows11
- 数据库：MySQL

### 你猜测可能的原因

发现可能的原因是：
部门权限问题
`AdminUserRespDTO startUser = adminUserApi.getUser(Long.valueOf(processInstance.getStartUserId()));`
`SELECT id,
       username,
       password,
       nickname,
       remark,
       dept_id,
       post_ids,
       email,
       mobile,
       sex,
       avatar,
       status,
       login_ip,
       login_date,
       tenant_id,
       create_time,
       update_time,
       creator,
       updater,
       deleted
FROM system_users
WHERE id = 1
  AND deleted = 0
  AND tenant_id = 1
  AND system_users.dept_id IN (105, 106, 107)`
但是admin的权限是103, 查出来的user为null

### 复现步骤
(
    按照文档中(审批接入(流程表单))案例 
    admin和test两个用户
)
第一步，
工作流管理 -> 审批中心 -> 我的流程 -> 发起流程

第二步，
提交流程

第三步，
部门领导账号审批 -> 点击审批通过

### 报错信息
`java.lang.NullPointerException: Cannot invoke "cn.iocoder.yudao.module.system.api.user.dto.AdminUserRespDTO.getId()" because "startUser" is null
	at cn.iocoder.yudao.module.bpm.convert.task.BpmTaskConvert.convert(BpmTaskConvert.java:146)`

PS: 虽然报错 但是工作流会继续流转

带上必要的截图
![image](https://github.com/user-attachments/assets/7752d436-331b-4ca7-8e9c-b5622fc39942)
test 账号的data_scope_dept_ids的范围是[105,106,107]
![image](https://github.com/user-attachments/assets/2e4eeb48-6b3e-4152-b177-7d20ddccfe7c)
system_user表中 admin的dept_id是103 test的dept_id是107
![image](https://github.com/user-attachments/assets/fea1825d-2ed8-49d0-807a-4191a3908ed9)

**Comment by YunaiV** [comment]
数据权限设置大一点，不然会有问题

这块后续我们会做一些调整。
