### ISSUE TITLE
日志记录功能问题

### ISSUE THREAD

**Issue by jhualee** [YunaiV/ruoyi-vue-pro#607]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：
- 操作系统：windows10
- 数据库：mysql

### 你猜测可能的原因

  操作日志功能组件与security组件是组合在一起

### 复现步骤

* 第一步：目前操作日志功能组件与security组件是组合在一起的，我在开发新的模块时，只用security组件的权限相关功能，不希望引入日志功能组件，日志功能组件无法去除。
* 第二步：我在新的模块下希望使用bizLog组件写一套自己的日志组件，目前无法处理

**Comment by YunaiV** [comment]
好的哈，可以按需进行定制，通过二开代码哈。

**Comment by jhualee** [comment]
煞笔
