### ISSUE TITLE
数据库的表缺失

### ISSUE THREAD

**Issue by 8HH8-me** [YunaiV/ruoyi-vue-pro#61]
AdminServerApplication启动时显示Table 'ruoyi-vue-pro.pay_channel' doesn't exist，但是我没有找到这个表的创表代码

**Comment by YunaiV** [comment]
有的噢，仔细看看 ruoyi-vue-pro.sql 噢

**Comment by 8HH8-me** [comment]
我之前clone的版本里面没有pay_ channel.我重新clone了一下，发现有了，谢谢了

**Comment by YunaiV** [comment]
> 我之前clone的版本里面没有pay_ channel.我重新clone了一下，发现有了，谢谢了

客气，之前我不小心，没搞全。后续我慢慢把自动化做好，这个困扰就少点
