### ISSUE TITLE
定时任务在多租户情况下租户禁用也会执行执行的问题

### ISSUE THREAD

**Issue by cksspk** [YunaiV/ruoyi-vue-pro#611]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：v2.1.0
- 操作系统：
- 数据库：

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：TenantJobAspect 切面在获取租户编号时没有去判读租户是否启用的状态？设计如此吗

### 复现步骤

第一步，
禁用其他租户，只留下一个超级管理员租户

第二步，
执行订单同步定时任务，此时会执行所有的租户订单情况，虽然不会发生异常。但是好像没有必要吧
![CleanShot 2024-08-06 at 10 31 40@2x](https://github.com/user-attachments/assets/9c42c90a-e5a7-4351-b090-f53b27abec4b)

**Comment by YunaiV** [comment]
收到，我 fix 下哈。

**Comment by YunaiV** [comment]
@mentatbot can you fix？

**Comment by YunaiV** [comment]
思考了一下，当时这么写的原因，是因为 disable 之后的租户，也可能需要跑一些 job。

这块，我建议是一个租户真不需要了，删除掉，会更合适。

这个 issue 先暂时不进行调整。看看其他同学的看法
