### ISSUE TITLE
运行test用例报错，，请问你们是如何解决这个问题的？

### ISSUE THREAD

**Issue by kibozh** [YunaiV/ruoyi-vue-pro#612]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：任意版本
- 操作系统：任意操作系统
- 数据库：mysql8

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：看了一下主要是java时间和mysql时间长度不一致。
其中java的LocalDataTime精确到纳秒，mysql的datetime时间精确到微秒。这样存库后再查出来比对，时间是不一致的。
请问你们是如何解决这个问题的？是自己手动把LocalDateTime的精度四舍五入精确到微妙，还是改数据库字段的时间格式？
还是其他更好的解决方法？请指教，谢谢大佬。

### 复现步骤

第一步，

第二步，

第三步，

### 报错信息

![image](https://github.com/user-attachments/assets/2bf7c207-a08f-4671-af46-f36563593d72)

**Comment by kibozh** [comment]
算了，最后选择skipTest

**Comment by YunaiV** [comment]
你是 windows11 么？

目前看，好像就它会出现。

**Comment by YunaiV** [comment]
https://github.com/YunaiV/ruoyi-vue-pro/pulls

先参考这个解决哈

**Comment by kibozh** [comment]
> https://github.com/YunaiV/ruoyi-vue-pro/pulls
> 
> 先参考这个解决哈

我看到有这个pr，但是好像你这边没有选择合并

**Comment by kibozh** [comment]
> 你是 windows11 么？
> 
> 目前看，好像就它会出现。

对的，确实是win11

**Comment by kibozh** [comment]
不是还没解决吗？怎么这么着急标记为已完成

**Comment by YunaiV** [comment]
https://github.com/YunaiV/ruoyi-vue-pro/pull/491
