### ISSUE TITLE
会考虑支持 Azure OpenAI 吗

### ISSUE THREAD

**Issue by maioria** [YunaiV/ruoyi-vue-pro#614]
会考虑支持 Azure OpenAI 吗

**Comment by YunaiV** [comment]
有考虑，不过我没有 Azure OpenAI 的权限

你那可以共享下给我，我来接下么？

wangwenbin-server 我的微信哈

**Comment by maioria** [comment]
可以的

**Comment by YunaiV** [comment]
已实现，周末肝了下。

感谢 @maioria 提供的密钥！
