### ISSUE TITLE
开启多租户后工作流相关自定义查询不可用！

### ISSUE THREAD

**Issue by kmmaru** [YunaiV/ruoyi-vue-pro#616]
开启多租户yudao.tenant.enable: true的情况下，工作流相关的查询是怎么处理的。
业务表的字段是：tenant_id，flowable相关的是tenant_id_带了下划线后缀。
TenantLineHandler的tenantIdColumn默认是tenant_id。
自定义的查询经MyBatis-Plus多租户插件组装的sql就报Unknown column 'xx.tenant_id'，请问是怎么处理？
例如：
SELECT
  book.book_name,
  book.process_number,
  book.responsible_editor,
  book.STATUS,
  RES.PROC_INST_ID_ AS processInstanceId,
  RES.NAME_ AS taskName,
  RES.ASSIGNEE_ AS assignee,
  RES.START_TIME_ AS createTime,
  DEF.KEY_ AS processDefinitionKey,
  procinst.BUSINESS_KEY_ AS businessKey,
  RES.ID_ AS id,
  RES.TASK_DEF_KEY_ AS taskDefinitionKey,
  reasonVar.TEXT_ AS reason,
  timeVar.TEXT_ AS nextFinshTime,
  RES.END_TIME_ 
FROM
  ( SELECT taskinst.* FROM ACT_HI_TASKINST taskinst WHERE taskinst.tenant_id = 1 ORDER BY taskinst.END_TIME_ DESC ) RES
  LEFT OUTER JOIN ACT_HI_VARINST reasonVar ON RES.ID_ = reasonVar.TASK_ID_ 
  AND reasonVar.NAME_ = 'TASK_REASON' 
  AND reasonVar.tenant_id = 1
  LEFT OUTER JOIN ACT_HI_VARINST timeVar ON RES.ID_ = timeVar.TASK_ID_ 
  AND timeVar.NAME_ = 'NEXT_FINISH_TIME' 
  AND timeVar.tenant_id = 1
  INNER JOIN ACT_HI_PROCINST procinst ON procinst.PROC_INST_ID_ = RES.PROC_INST_ID_ 
  AND procinst.tenant_id = 1
  LEFT OUTER JOIN ACT_RE_PROCDEF DEF ON RES.PROC_DEF_ID_ = DEF.ID_ 
  AND DEF.tenant_id = 1
  INNER JOIN ink_book_production book ON book.id = procinst.BUSINESS_KEY_ 
  AND book.tenant_id = 1
  INNER JOIN system_users USER ON USER.id = RES.ASSIGNEE_ 
  AND USER.dept_id = '1' 
  AND USER.tenant_id = 1 
ORDER BY
  RES.END_TIME_ DESC

**Comment by YunaiV** [comment]
https://doc.iocoder.cn/saas-tenant/

参考这篇文档，把类似 ACT_HI_PROCINST 配置成忽略租户，然后使用它原生的租户字段查询

**Comment by kmmaru** [comment]
这。。。“医生我脚疼？”专家：“你把脚砍了就不疼了”。开个玩笑^_^
您这种方案有一个前提是：业务表（自己开业务建的表）去关联查询，在业务表上做租户过滤。
治了标，but，this is BUG
