### ISSUE TITLE
关于private void validateBpmnXml(byte[] bpmnBytes) 方法的问题

### ISSUE THREAD

**Issue by siqn3046** [YunaiV/ruoyi-vue-pro#618]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：2.2.0
- 操作系统：win11
- 数据库：MySQL 8.0

### 你猜测可能的原因
// 2. 校验 UserTask 的 name 都配置了
        List<UserTask> userTasks = BpmnModelUtils.getBpmnModelElements(bpmnModel, UserTask.class);
        userTasks.forEach(userTask -> {
            if (StrUtil.isEmpty(userTask.getName())) {
                throw exception(MODEL_DEPLOY_FAIL_BPMN_USER_TASK_NAME_NOT_EXISTS, userTask.getId());
            }
        });
UserTask  name 字段null

（必填）我花费了 2-4 小时自查，发现可能的原因是：xxxxxx

### 复现步骤

第一步，

第二步，

第三步，

### 报错信息

带上必要的截图

**Comment by YunaiV** [comment]
具体的问题是？？

**Comment by siqn3046** [comment]
![1723167032770](https://github.com/user-attachments/assets/7fdce907-659c-49f2-b559-53545578ca95)
必须有名称才可以  发布流程了
