### ISSUE TITLE
演示系统打不开了

### ISSUE THREAD

**Issue by dongweizhao** [YunaiV/ruoyi-vue-pro#629]
系统登录提示跨域
![image](https://github.com/user-attachments/assets/75937568-1781-47c5-9682-35ca0875dbb9)

**Comment by newives** [comment]
😂 都三周不能打开了 估计还在维护吧

**Comment by dongweizhao** [comment]
现在是不提供演示环境了吗，试了还是不行

**Comment by newives** [comment]
应该会 估计遇到啥大难题了😂
