### ISSUE TITLE
请问这个仓库和若依(https://ruoyi.vip/)有什么区别

### ISSUE THREAD

**Issue by baymax55** [YunaiV/ruoyi-vue-pro#63]
https://ruoyi.vip/

**Comment by YunaiV** [comment]
建议可以看看 README.md 和更新日志，有这块的说明哈。
https://github.com/YunaiV/ruoyi-vue-pro/blob/master/README.md
https://github.com/YunaiV/ruoyi-vue-pro/blob/master/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97.md

简单来说，更优秀的代码实现，更完善的功能。
