### ISSUE TITLE
member_user 会员用户怎么控制的菜单/接口权限？

### ISSUE THREAD

**Issue by ixuranran** [YunaiV/ruoyi-vue-pro#635]
你好，想问下，member_user会员用户目前怎么控制的菜单/接口权限？是不是没有控制？

**Comment by YunaiV** [comment]
会员没有菜单一说哈。

建议在想想呢。。。

**Comment by ixuranran** [comment]
接口权限也不控制？会员相关的操作接口可以无权限请求？

**Comment by YunaiV** [comment]
> 接口权限也不控制？会员相关的操作接口可以无权限请求？

会员，一般只控制是否登录。

如果真有权限，一般可能是论坛 lv1、lv2、lv3 可以做什么，又是另外的业务需求了呀。

**Comment by ixuranran** [comment]
如果会员相关的接口没有控制权限，如果被人拿到接口地址，是不是会有可能被攻击？

**Comment by YunaiV** [comment]
= = /app-api/ 提供给会员的接口，是不存在权限一说呀。。。。

或者，你可以举个具体哪个 app 的，哪个类型的接口，需要做校验。

这样交流起来，比较高效哈。

**Comment by ixuranran** [comment]
比如一些新增类型的接口，不做权限限制，是不是可以随意调用?

**Comment by YunaiV** [comment]
> 比如一些新增类型的接口，不做权限限制，是不是可以随意调用?

例如说呢？可以举个举个我们常用的 app 例子，它的哪个接口，需要考虑这个情况呢。
