### ISSUE TITLE
BPMN工作流添加定时捕获事件后后续用户任务无法获得租户信息

### ISSUE THREAD

**Issue by originalchou** [YunaiV/ruoyi-vue-pro#636]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：v2.1.0
- 操作系统：mac
- 数据库：mysql

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：添加定时事件后flowable的异步线程池没有得到租户上下文

### 复现步骤

第一步，部署以下流程（定时事件设置为十秒后触发）
`<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:flowable="http://flowable.org/bpmn" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.activiti.org/processdef">
  <process id="common_form2" name="vacation" isExecutable="true">
    <startEvent id="Event_1kgld94">
      <extensionElements>
        <flowable:formData />
      </extensionElements>
      <outgoing>Flow_1ulv8ir</outgoing>
    </startEvent>
    <userTask id="Activity_0y8jwms" name="部门领导审批" flowable:candidateStrategy="60" flowable:candidateParam="${bpmTaskAssignLeaderExpression.calculateUsers(execution, 1)}">
      <extensionElements>
        <flowable:formData />
      </extensionElements>
      <incoming>Flow_0wtp5sl</incoming>
      <outgoing>Flow_0lzdrlv</outgoing>
    </userTask>
    <userTask id="Activity_1me20o2" name="HR审批" flowable:candidateStrategy="22" flowable:candidateParam="5">
      <extensionElements>
        <flowable:formData />
      </extensionElements>
      <incoming>Flow_0lzdrlv</incoming>
      <outgoing>Flow_18k0b9p</outgoing>
    </userTask>
    <endEvent id="Event_0xidqag">
      <incoming>Flow_18k0b9p</incoming>
    </endEvent>
    <sequenceFlow id="Flow_18k0b9p" sourceRef="Activity_1me20o2" targetRef="Event_0xidqag" />
    <intermediateCatchEvent id="timer" name="计时器">
      <documentation />
      <incoming>Flow_1ulv8ir</incoming>
      <outgoing>Flow_0wtp5sl</outgoing>
      <timerEventDefinition id="TimerEventDefinition_0jqw73x">
        <timeDuration>PT10S</timeDuration>
      </timerEventDefinition>
    </intermediateCatchEvent>
    <sequenceFlow id="Flow_1ulv8ir" sourceRef="Event_1kgld94" targetRef="timer" />
    <sequenceFlow id="Flow_0wtp5sl" sourceRef="timer" targetRef="Activity_0y8jwms" />
    <sequenceFlow id="Flow_0lzdrlv" sourceRef="Activity_0y8jwms" targetRef="Activity_1me20o2" />
  </process>
  <bpmndi:BPMNDiagram id="BPMNDiagram">
    <bpmndi:BPMNPlane id="common_form_di" bpmnElement="common_form">
      <bpmndi:BPMNEdge id="Flow_0lzdrlv_di" bpmnElement="Flow_0lzdrlv">
        <di:waypoint x="990" y="390" />
        <di:waypoint x="1150" y="390" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_0wtp5sl_di" bpmnElement="Flow_0wtp5sl">
        <di:waypoint x="758" y="390" />
        <di:waypoint x="890" y="390" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1ulv8ir_di" bpmnElement="Flow_1ulv8ir">
        <di:waypoint x="588" y="390" />
        <di:waypoint x="722" y="390" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_18k0b9p_di" bpmnElement="Flow_18k0b9p">
        <di:waypoint x="1250" y="390" />
        <di:waypoint x="1362" y="390" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape id="Event_1kgld94_di" bpmnElement="Event_1kgld94">
        <dc:Bounds x="552" y="372" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_0y8jwms_di" bpmnElement="Activity_0y8jwms">
        <dc:Bounds x="890" y="350" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_1me20o2_di" bpmnElement="Activity_1me20o2">
        <dc:Bounds x="1150" y="350" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_0xidqag_di" bpmnElement="Event_0xidqag">
        <dc:Bounds x="1362" y="372" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="timer_di" bpmnElement="timer">
        <dc:Bounds x="722" y="372" width="36" height="36" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="724" y="415" width="33" height="14" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</definitions>`

第二步，发起流程

第三步，十秒后会报错

### 报错信息
`Caused by: java.lang.NullPointerException: TenantContextHolder 不存在租户编号！可参考文档：https://doc.iocoder.cn
	at cn.iocoder.yudao.framework.tenant.core.context.TenantContextHolder.getRequiredTenantId(TenantContextHolder.java:41)
	at cn.iocoder.yudao.framework.tenant.core.db.TenantDatabaseInterceptor.getTenantId(TenantDatabaseInterceptor.java:34)
	at com.baomidou.mybatisplus.extension.plugins.inner.TenantLineInnerInterceptor.buildTableExpression(TenantLineInnerInterceptor.java:271)
	at com.baomidou.mybatisplus.extension.plugins.inner.BaseMultiTableInnerInterceptor.lambda$builderExpression$3(BaseMultiTableInnerInterceptor.java:386)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.baomidou.mybatisplus.extension.plugins.inner.BaseMultiTableInnerInterceptor.builderExpression(BaseMultiTableInnerInterceptor.java:388)
	at com.baomidou.mybatisplus.extension.plugins.inner.BaseMultiTableInnerInterceptor.processPlainSelect(BaseMultiTableInnerInterceptor.java:113)
	at com.baomidou.mybatisplus.extension.plugins.inner.BaseMultiTableInnerInterceptor.processSelectBody(BaseMultiTableInnerInterceptor.java:54)
	at com.baomidou.mybatisplus.extension.plugins.inner.TenantLineInnerInterceptor.processSelect(TenantLineInnerInterceptor.java:92)
	at com.baomidou.mybatisplus.extension.parser.JsqlParserSupport.processParser(JsqlParserSupport.java:90)
	at com.baomidou.mybatisplus.extension.parser.JsqlParserSupport.parserSingle(JsqlParserSupport.java:49)
	at com.baomidou.mybatisplus.extension.plugins.inner.TenantLineInnerInterceptor.beforeQuery(TenantLineInnerInterceptor.java:72)
	at com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor.intercept(MybatisPlusInterceptor.java:78)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:62)
	at jdk.proxy2/jdk.proxy2.$Proxy377.query(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor94.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
	at com.github.yulichang.interceptor.MPJInterceptor.intercept(MPJInterceptor.java:90)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:62)
	at jdk.proxy2/jdk.proxy2.$Proxy377.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:151)
	... 85 common frames omitted`
带上必要的截图
流程图：
[
![Screenshot 2024-08-19 at 11 00 38 PM](https://github.com/user-attachments/assets/e288a28e-a438-450c-9d0a-989f42fb49ec)
](url)

**Comment by originalchou** [comment]
目前手动添加了租户信息可以解决问题：
`public class CustomAsyncExecutor extends DefaultAsyncJobExecutor {
    @Override
    protected boolean executeAsyncJob(final JobInfo job, Runnable runnable) {
        if (StringUtil.isNotEmpty(job.getTenantId())) {
            TenantContextHolder.setTenantId(Long.parseLong(job.getTenantId()));
        }
        return super.executeAsyncJob(job, runnable);
    }
}`
BpmFlowableConfiguration.java:
`/**
     * BPM 模块的 ProcessEngineConfigurationConfigurer 实现类：
     *
     * 1. 设置各种监听器
     * 2. 设置自定义的 ActivityBehaviorFactory 实现
     */
    @Bean
    public EngineConfigurationConfigurer<SpringProcessEngineConfiguration> bpmProcessEngineConfigurationConfigurer(
            ObjectProvider<FlowableEventListener> listeners,
            BpmActivityBehaviorFactory bpmActivityBehaviorFactory) {
        return configuration -> {
            // 注册监听器，例如说 BpmActivityEventListener
            configuration.setEventListeners(ListUtil.toList(listeners.iterator()));
            // 设置 ActivityBehaviorFactory 实现类，用于流程任务的审核人的自定义
            configuration.setActivityBehaviorFactory(bpmActivityBehaviorFactory);
            configuration.setAsyncExecutor(new CustomAsyncExecutor());
        };
    }`
但是依然有疑问的是为什么用TTL记录的租户上下文丢失了，希望大佬解惑

**Comment by YunaiV** [comment]
因为是 flowable 的 executor，所以会丢失。

   @Override
    public void processProcessInstanceCompleted(ProcessInstance instance) {
        // 注意：需要基于 instance 设置租户编号，避免 Flowable 内部异步时，丢失租户编号
        FlowableUtils.execute(instance.getTenantId(), () -> {
            // 1.1 获取当前状态
            Integer status = (Integer) instance.getProcessVariables().get(BpmnVariableConstants.PROCESS_INSTANCE_VARIABLE_STATUS);
            String reason = (String) instance.getProcessVariables().get(BpmnVariableConstants.PROCESS_INSTANCE_VARIABLE_REASON);
            // 1.2 当流程状态还是审批状态中，说明审批通过了，则变更下它的状态
            // 为什么这么处理？因为流程完成，并且完成了，说明审批通过了
            if (Objects.equals(status, BpmProcessInstanceStatusEnum.RUNNING.getStatus())) {
                status = BpmProcessInstanceStatusEnum.APPROVE.getStatus();
                runtimeService.setVariable(instance.getId(), BpmnVariableConstants.PROCESS_INSTANCE_VARIABLE_STATUS, status);
            }

            // 2. 发送对应的消息通知
            if (Objects.equals(status, BpmProcessInstanceStatusEnum.APPROVE.getStatus())) {
                messageService.sendMessageWhenProcessInstanceApprove(BpmProcessInstanceConvert.INSTANCE.buildProcessInstanceApproveMessage(instance));
            } else if (Objects.equals(status, BpmProcessInstanceStatusEnum.REJECT.getStatus())) {
                messageService.sendMessageWhenProcessInstanceReject(
                        BpmProcessInstanceConvert.INSTANCE.buildProcessInstanceRejectMessage(instance, reason));
            }

            // 3. 发送流程实例的状态事件
            processInstanceEventPublisher.sendProcessInstanceResultEvent(
                    BpmProcessInstanceConvert.INSTANCE.buildProcessInstanceStatusEvent(this, instance, status));
        });
    }


可以类似这么搞~

**Comment by originalchou** [comment]
> 因为是 flowable 的 executor，所以会丢失。
> 
> @OverRide public void processProcessInstanceCompleted(ProcessInstance instance) { // 注意：需要基于 instance 设置租户编号，避免 Flowable 内部异步时，丢失租户编号 FlowableUtils.execute(instance.getTenantId(), () -> { // 1.1 获取当前状态 Integer status = (Integer) instance.getProcessVariables().get(BpmnVariableConstants.PROCESS_INSTANCE_VARIABLE_STATUS); String reason = (String) instance.getProcessVariables().get(BpmnVariableConstants.PROCESS_INSTANCE_VARIABLE_REASON); // 1.2 当流程状态还是审批状态中，说明审批通过了，则变更下它的状态 // 为什么这么处理？因为流程完成，并且完成了，说明审批通过了 if (Objects.equals(status, BpmProcessInstanceStatusEnum.RUNNING.getStatus())) { status = BpmProcessInstanceStatusEnum.APPROVE.getStatus(); runtimeService.setVariable(instance.getId(), BpmnVariableConstants.PROCESS_INSTANCE_VARIABLE_STATUS, status); }
> 
> ```
>         // 2. 发送对应的消息通知
>         if (Objects.equals(status, BpmProcessInstanceStatusEnum.APPROVE.getStatus())) {
>             messageService.sendMessageWhenProcessInstanceApprove(BpmProcessInstanceConvert.INSTANCE.buildProcessInstanceApproveMessage(instance));
>         } else if (Objects.equals(status, BpmProcessInstanceStatusEnum.REJECT.getStatus())) {
>             messageService.sendMessageWhenProcessInstanceReject(
>                     BpmProcessInstanceConvert.INSTANCE.buildProcessInstanceRejectMessage(instance, reason));
>         }
> 
>         // 3. 发送流程实例的状态事件
>         processInstanceEventPublisher.sendProcessInstanceResultEvent(
>                 BpmProcessInstanceConvert.INSTANCE.buildProcessInstanceStatusEvent(this, instance, status));
>     });
> }
> ```
> 
> 可以类似这么搞~

谢谢！
