### ISSUE TITLE
文档错误文档有Repo吗

### ISSUE THREAD

**Issue by hunao0221** [YunaiV/ruoyi-vue-pro#641]
关于[自动翻译的说明](https://doc.iocoder.cn/vo/#_2-4-%E8%87%AA%E5%8A%A8%E7%BF%BB%E8%AF%91%E7%9A%84%E8%AF%B4%E6%98%8E) 忽略某个API翻译应该使用 `@IgnoreTrans` 而不是 `@TransIgnore`.

See details [here](http://easy-trans.fhs-opensource.top/components/basic.html#_5%E3%80%81%E5%BF%BD%E7%95%A5%E7%BF%BB%E8%AF%91)

~另外请问下，如何忽略某张表的逻辑删除，而使用物理删除~
> 可以使用mapper xml

**Comment by YunaiV** [comment]
我修复下哈

**Comment by YunaiV** [comment]
谢谢！
