### ISSUE TITLE
vue3版本启动问题

### ISSUE THREAD

**Issue by MrKaGod** [YunaiV/ruoyi-vue-pro#646]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：
- 操作系统：
- 数据库：

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：xxxxxx

### 复现步骤

第一步，

第二步，

第三步，

### 报错信息

带上必要的截图
![image](https://github.com/user-attachments/assets/3cd7cf15-c1b2-4355-b86c-2b9c4cfe9348)
偶发问题，启动后打开浏览器会提示这个，请问什么情况呢？

**Comment by YunaiV** [comment]
前端是不是 https 了。

然后的后端，也必须是 https。这就是图里，为什么连接了 443 端口。

**Comment by MrKaGod** [comment]
都是本地环境，没有牵扯到https这个问题啊
