### ISSUE TITLE
[CI]建议使用github action做CI

### ISSUE THREAD

**Issue by zzc7211** [YunaiV/ruoyi-vue-pro#65]
建议使用github action功能，提交pull request或者入库后可以自动使用多个java版本以及node版本进行一次编译，将编译结果标签结果加到ReadMe里就可以方便的看到项目支持的编译环境情况了，希望可以配置上。

**Comment by YunaiV** [comment]
感谢，有兴趣 pr 下么，嘿嘿。

**Comment by zzc7211** [comment]
已提交PR #67

**Comment by zzc7211** [comment]
怎么样，这个配置要入吗。

**Comment by zzc7211** [comment]
已经完成，关闭本单
