### ISSUE TITLE
您好，使用流程设计去设计流程，在使用用户任务的时候没有问题，但是切换使用服务任务的就会出现以下报错

### ISSUE THREAD

**Issue by pengjianxi** [YunaiV/ruoyi-vue-pro#651]
报错如下：
[Validation set: 'flowable-executable-process' | Problem: 'flowable-servicetask-missing-implementation'] : One of the attributes 'class', 'delegateExpression', 'type', 'operation', or 'expression' is mandatory on serviceTask. - [Extra info : processDefinitionId = common-form | processDefinitionName = 通用表单 |  | id = Activity_1y6fln2 |  | activityName = 服务任务 | ] ( line: 2, column: 3553)
（图1是报错的组件，图2是报错的截图）
![1](https://github.com/user-attachments/assets/fb8d6d0c-6754-4431-8b1e-d9f72778914e)
![2](https://github.com/user-attachments/assets/d6fd9988-4cd2-4153-a5f7-5aab345a1ecf)

求帮忙解决，谢谢！！

**Comment by YunaiV** [comment]
合并到 https://gitee.com/zhijiantianya/yudao-cloud/issues/I9G5GE 跟进
