### ISSUE TITLE
【欢迎贡献】yudao-mall-uniapp在线客服，toolsPopup组件问题。

### ISSUE THREAD

**Issue by liruijun960206** [YunaiV/ruoyi-vue-pro#652]
### 基本信息

- yudao-mall-uniapp 版本：
- 操作系统：window10
- 数据库：无

### 你猜测可能的原因

问题原因是su-popup组件使用uni-transition组件实现组件切换的时候，弹框由translateY0变为ranslateY100%，导致在弹出选择表情弹框的情况下，再去点击选择商品、相册、订单的功能，组件消失，只剩下一个蒙层。

### 复现步骤

第一步，打开选择表情

第二步，在表情弹框出现的情况下，点击+。

### 报错信息

选择选择商品、相册、订单的弹框未出现，只剩下蒙层。
![微信截图_20240912153630](https://github.com/user-attachments/assets/7b29f990-996d-4811-9c46-e1aa7e40d4aa)
![微信截图_20240912153710](https://github.com/user-attachments/assets/ec70107e-184d-4c4d-ad06-9682f3a660d5)

**Comment by YunaiV** [comment]
有没兴趣，pull request 贡献下哈？

**Comment by liruijun960206** [comment]
我手动将su-popup组件中第449行，手动写死style样式transform: 'translateY(0)'，办法有点粗暴，不是最佳处理方式。没想到别的办法。
