### ISSUE TITLE
请问ERP和Mall能打通，比如库存

### ISSUE THREAD

**Issue by AllenHxy** [YunaiV/ruoyi-vue-pro#653]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息
请问ERP和Mall能打通，比如ERP的库存同步商城下订单后库存的扣减；
这个是合理需求么？一般有什么解决方案吗

- ruoyi-vue-pro 版本：
- 操作系统：
- 数据库：

### 复现步骤

第一步，

第二步，

第三步，

### 报错信息

带上必要的截图

**Comment by YunaiV** [comment]
erp 和 mall 可以打通哈，按照自己的业务需求进行实现。

我们提供了 mall 和 erp，两者目前是解耦，方便大家定制。

一般的解决方案，可以和大模型做下沟通哈。
