### ISSUE TITLE
yudao-ui-admin-vue3打包生产环境env文件验证码的开关配置无效

### ISSUE THREAD

**Issue by liruijun960206** [YunaiV/ruoyi-vue-pro#655]
### 基本信息

- ruoyi-vue-pro 版本：
- 操作系统：
- 数据库：

### 你猜测可能的原因

原因是取不到loginForm.vue取不到VITE_APP_CAPTCHA_ENABLE值。不管配置true或者false，都走直接登录

### 复现步骤

第一步，

第二步，

第三步，

**Comment by YunaiV** [comment]
测试了下，可以开启和关闭。

建议自查下

**Comment by YunaiV** [comment]
https://doc.iocoder.cn/captcha/
