### ISSUE TITLE
未正确获取ip, 可以任意伪造IP

### ISSUE THREAD

**Issue by relufi** [YunaiV/ruoyi-vue-pro#657]
```java
	public static String getClientIP(HttpServletRequest request, String... otherHeaderNames) {
		String[] headers = {"X-Forwarded-For", "X-Real-IP", "Proxy-Client-IP", "WL-Proxy-Client-IP", "HTTP_CLIENT_IP", "HTTP_X_FORWARDED_FOR"};
		if (ArrayUtil.isNotEmpty(otherHeaderNames)) {
			headers = ArrayUtil.addAll(headers, otherHeaderNames);
		}

		return getClientIPByHeader(request, headers);
	}
```
因为ServletUtils.getClientIP() 内部实现是优先使用 X-Forwarded-For 。调用方只需要携带请求头 X-Forwarded-For: 1.1.1.1  即可伪造ip

**Comment by relufi** [comment]
只有一层nginx的,应该使用以下方式从X-Real-IP头中取, 在nginx中将真实ip设置到X-Real-IP请求头上，就如 [https://doc.iocoder.cn/deployment-linux](_5-2-方式一-服务器-ip-访问) 这里配置的
```
JakartaServletUtil.getClientIPByHeader(request,"X-Real-IP")
```
如果没有使用 nginx 转发,就不应该从请求头中取,直接调用request.getRemoteAddr

**Comment by YunaiV** [comment]
可以看下 https://doc.iocoder.cn/deployment-linux/ 文档，已经写了 nginx 的转发配置噢

**Comment by relufi** [comment]
```
        location /admin-api/ { ## 后端项目 - 管理后台
            proxy_pass http://localhost:48080/admin-api/; ## 重要！！！proxy_pass 需要设置为后端项目所在服务器的 IP
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header REMOTE-HOST $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
```
？？？ 文档里不就是这样配置的吗， 
 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  这行, 会取客户端的请求头 X-Forwarded-For 。 而后端ServletUtils.getClientIP()  又会优先取  X-Forwarded-For 作为用户ip。  所以请求头上带个 X-Forwarded-For: xxxxx 就能随意伪装ip了,

**Comment by relufi** [comment]
![微信图片_20240920093908](https://github.com/user-attachments/assets/81a22a33-5ec7-441d-a615-8aea04875a54)

![微信图片_20240920093913](https://github.com/user-attachments/assets/37f1a6ed-c41e-4439-83e3-472b7bde77bf)

**Comment by relufi** [comment]
这个看下,复现挺容易的
