### ISSUE TITLE
master分支最新版是基于jdk8吗 ai模块报语法错误

### ISSUE THREAD

**Issue by lb1565387341** [YunaiV/ruoyi-vue-pro#665]
![image](https://github.com/user-attachments/assets/2a3a7dd0-8080-4c5a-9fa6-ae1bed316521)

**Comment by 1235wsg** [comment]
master是jdk8，ai模块只能在17 的环境下使用

**Comment by YunaiV** [comment]
参考文档 https://doc.iocoder.cn/ai/build/
