### ISSUE TITLE
Midjourney成功后回调会报没有tenantId的问题

### ISSUE THREAD

**Issue by maioria** [YunaiV/ruoyi-vue-pro#669]
### 基本信息

- ruoyi-vue-pro 版本： 
- 操作系统：
- 数据库：

### 你猜测可能的原因

需要在 ignore-urls - /admin-api/ai/image/midjourney/notify

另外midjourney的定时任务也报错，没有tenantId

### 复现步骤

第一步，

第二步，

第三步，

### 报错信息

带上必要的截图

**Comment by YunaiV** [comment]
已经修复 https://gitee.com/zhijiantianya/ruoyi-vue-pro/commit/6f7fe84c41d23d3f67ca043efef680d5c0973a25
