### ISSUE TITLE
knowledge_id找不到对应的字段和表

### ISSUE THREAD

**Issue by kai0099** [YunaiV/ruoyi-vue-pro#670]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：
- 操作系统：win
- 数据库：mysql

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：数据库中没有对应的knowledge_id字段和表

是数据库还没有更新最新的原因吗

### 复现步骤

第一步，

第二步，

第三步，

### 报错信息

带上必要的截图
![图片](https://github.com/user-attachments/assets/55bb8eee-e0d7-4e3d-9792-00c4e93f4835)
![图片](https://github.com/user-attachments/assets/6be1039d-c55d-453b-9848-2b295cd85642)

**Comment by YunaiV** [comment]
https://wx.zsxq.com/group/88858522214142/topic/2855214828548251
