### ISSUE TITLE
weixin-java from 4.6.0 to 4.6.5.B升级导致的支付异常：请确保证书文件地址【privateCertPath】或者内容已配置

### ISSUE THREAD

**Issue by cuiwei1** [YunaiV/ruoyi-vue-pro#671]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：v2.3.0
- 操作系统：windows11
- 数据库：mysql

### 你猜测可能的原因

（必填）原因是：由于weixin-java版本升级，导致的程序异常，降级回4.6.0即可

weixin-java 4.6.0 ---> initApiV3HttpClient 这里的逻辑是对的

![image](https://github.com/user-attachments/assets/2ef0a1ba-2848-4710-9ffd-5ba2317db245)

weixin-java 4.6.5.B ---> initApiV3HttpClient 这里的逻辑是有缺陷的

![image](https://github.com/user-attachments/assets/e217dcd7-853b-497b-a566-1e5537411d33)

### 报错信息

带上必要的截图
![image](https://github.com/user-attachments/assets/908daf60-e108-4f23-805d-24fbdc611032)

**Comment by YunaiV** [comment]
如果使用 4.6.5.B 的情况下，应该怎么配置合适点？

**Comment by YunaiV** [comment]
已经降级解决，谢谢
