### ISSUE TITLE
建议增加一个QQ小程序的登录接入

### ISSUE THREAD

**Issue by hurentian** [YunaiV/ruoyi-vue-pro#673]
qq小程序文档：https://q.qq.com/wiki/develop/miniprogram/server/
希望新增此登录方式
根据文档来看，qq小程序与微信小程序的接口几乎一致

**Comment by YunaiV** [comment]
QQ 登录，需要的暂时不多，暂时不考虑接入哈。

目前接入，已经改很方便的，自己搞下就好哈。
