### ISSUE TITLE
pom 添加 profile

### ISSUE THREAD

**Issue by softboy99** [YunaiV/ruoyi-vue-pro#675]
![image](https://github.com/user-attachments/assets/e09e7537-3517-4e22-8e82-6facfe4a3487)

![image](https://github.com/user-attachments/assets/fe3af6a9-3969-4a45-a55b-e280b2bb6965)

**Comment by YunaiV** [comment]
也是一个实践哈。

不过实际用 maven 定义 profiles 比较少。

**Comment by softboy99** [comment]
> 也是一个实践哈。
> 
> 不过实际用 maven 定义 profiles 比较少。

大佬，还有别的方式吗？
