### ISSUE TITLE
如果使用mybatisplus join多表查询，只希望主表有数据权限的控制，join表不要有数据权限关联，如何在mapper层控制

### ISSUE THREAD

**Issue by edwardshen3033** [YunaiV/ruoyi-vue-pro#676]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：
- 操作系统：
- 数据库：

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：xxxxxx

### 复现步骤

第一步，
通过mybatisplus左关联合同和项目两张表，但只想查出来当前人创建的合同，要查出所有可以关联上的项目（即非自己创建的项目）
![image](https://github.com/user-attachments/assets/80bebd3d-f4c2-42af-ad6b-d58bf856d468)

第二步，
结果查出的所有表都有数据权限控制，请问如何配置或设置可以做到只有contract表有权限控制，项目表没有权限控制（两个表都需要存在dept_id）
![image](https://github.com/user-attachments/assets/d9846363-7579-4c9a-a64c-a721fe1cc468)

第三步，

### 报错信息

带上必要的截图

**Comment by YunaiV** [comment]
mybatis plus join 不支持这个功能。
