### ISSUE TITLE
文心一言不能使用

### ISSUE THREAD

**Issue by banghha** [YunaiV/ruoyi-vue-pro#677]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：2.2.0
- 操作系统：win10
- 数据库：mysql

### 你猜测可能的原因
使用文心一言进行聊天时报错null，可能是集合的ai有问题，最近文心一言好像更新了，
（必填）我花费了 2-4 小时自查，发现可能的原因是：xxxxxx

### 复现步骤

第一步，更换文心一言秘钥，

第二步，打开聊天

第三步，给文心一言发送消息

### 报错
![微信截图_20241019034415](https://github.com/user-attachments/assets/b7c5d30b-d0be-4618-9ca9-4c6a1b1e0d54)
![微信截图_20241019034545](https://github.com/user-attachments/assets/bda9ca3c-d22f-4366-a40d-9f0c599c053d)

带上必要的截图

**Comment by banghha** [comment]
![微信截图_20241019034707](https://github.com/user-attachments/assets/0975d5cf-2c2f-44ed-a64a-f49207b9624e)
buchon补充截图

**Comment by YunaiV** [comment]
https://doc.iocoder.cn/ai/yiyan/

参考这个操作。

猜测有可能模型选择不对。

我本地试了下，没问题哈。
