### ISSUE TITLE
审批中心>发起流程：无法查询出流程数据

### ISSUE THREAD

**Issue by XIAYUN-XY** [YunaiV/ruoyi-vue-pro#678]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：
- 操作系统：
- 数据库：

### 你猜测可能的原因
![图片](https://github.com/user-attachments/assets/f15ab89c-f1d4-42d9-9147-406f478d1424)

（必填）我花费了 2-4 小时自查，发现可能的原因是：用户ID类型不匹配导致方法总是返回false

### 复现步骤

第一步，表面上类型是一致的，都是Long
![图片](https://github.com/user-attachments/assets/6a4778cc-fbf4-4d50-8584-f5642015c410)

第二步，实际startUserIds字段存储的是字符串
![图片](https://github.com/user-attachments/assets/ba7ae808-9668-4172-8620-80836e9132b7)

### 报错信息

带上必要的截图

**Comment by YunaiV** [comment]
已修复。

= = 土鳖了我，应该是 @TableField(typeHandler = LongListTypeHandler.class)
