### ISSUE TITLE
代码生成器生成的列表界面排版问题

### ISSUE THREAD

**Issue by softboy99** [YunaiV/ruoyi-vue-pro#684]
### 基本信息

- ruoyi-vue-pro 版本：2.3
- 操作系统：win11
- 数据库：mysql 8.4.

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：模板问题

### 复现步骤

第一步，生成表的字段名称故意设置的比较长

第二步，生成后复制到项目中运行

第三步，查看界面，发现排版比较乱

### 报错信息

![image](https://github.com/user-attachments/assets/791319bb-d67a-4f81-b7b2-9f736cd5af30)

**Comment by YunaiV** [comment]
字段比较长的情况下，需要自己设置下 labelwidth
