### ISSUE TITLE
添加字典表白名单功能，实现把一个表的数据当作字典，可参考jeecgboot

### ISSUE THREAD

**Issue by softboy99** [YunaiV/ruoyi-vue-pro#685]
### 基本信息

- ruoyi-vue-pro 版本：2.3.0
- 操作系统：win11
- 数据库：mysql 8.4.2

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：无法将一个表的数据作为字典供另外一个表的表单界面下拉选择，可参照jeecgboot的字典表白名单功能

### 复现步骤

第一步，建立一个文件类型表，其中一字段对应工作流的ID，需要在界面上选择对应的工作流

第二步，工作流的ID就对应流程模型中的某条记录

第三步，现在不写代码无法实现，可参照jeecgboot的字典表白名单功能

**Comment by YunaiV** [comment]
这个功能，可能不太合理，从数据的安全性角度哈。

**Comment by softboy99** [comment]
怎么个不安全法？这个功能跟代码生成一样只是开发人员用的，这个场景是很常见的，几乎每个业务开发都会用到，每次都要写代码。

**Comment by YunaiV** [comment]
> 怎么个不安全法？这个功能跟代码生成一样只是开发人员用的，这个场景是很常见的，几乎每个业务开发都会用到，每次都要写代码。

我举个例子。一般中型公司，人员、组织，又或者商品类目等等，都是敏感信息。
因为一旦知道看到这些信息，基本就知道公司流程是怎么样的。

类似这些表的数据，如果通过一个通用的接口提供，会有信息泄露的风险。

我们实际在企业级的项目里，会单独开发敏感数据的接口，然后做好数据权限的控制。
