### ISSUE TITLE
BPMN设计器需支持业务表单

### ISSUE THREAD

**Issue by softboy99** [YunaiV/ruoyi-vue-pro#688]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：2.3.0
- 操作系统：win11
- 数据库：mysql 8.4.2

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：需要和系统已有的功能整合，没有了业务表单，跑完流程，数据没有保存

**Comment by YunaiV** [comment]
BPMN 发起的时候，支持业务表单、流程表单
每个节点，支持流程表单

https://doc.iocoder.cn/bpm/model-designer-bpmn/#_1-3-%E4%BB%BB%E5%8A%A1-%E8%A1%A8%E5%8D%95
