### ISSUE TITLE
core-js npm

### ISSUE THREAD

**Issue by qq13836848** [YunaiV/ruoyi-vue-pro#69]
This dependency was not found:

* core-js/modules/es.error.cause.js in ./node_modules/@babel/runtime/helpers/createForOfIteratorHelper.js, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/bpmnProcessDesigner/package/designer/ProcessDesigner.vue?vue&type=script&lang=js& and 5 others

To install it, you can run: npm install --save core-js/modules/es.error.cause.js

**Comment by YunaiV** [comment]
使用的 node 版本号是多少？可以参考我写的《环境搭建》，尽量保持跟我一致哈

**Comment by qq13836848** [comment]
换了一样的node版本也报错
npm run dev

> ruoyi@3.3.0 dev /Users/mac/Documents/justdoit/ruoyi-vue-pro/yudao-admin-ui
> vue-cli-service serve

 INFO  Starting development server...
98% after emitting CopyPlugin

 ERROR  Failed to compile with 7 errors                                                                                                          下午4:15:03

This dependency was not found:

* core-js/modules/es.error.cause.js in ./node_modules/@babel/runtime/helpers/createForOfIteratorHelper.js, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/bpmnProcessDesigner/package/designer/ProcessDesigner.vue?vue&type=script&lang=js& and 5 others

To install it, you can run: npm install --save core-js/modules/es.error.cause.js

**Comment by qq13836848** [comment]
这个是安装的日志
npm i
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm WARN deprecated axios@0.21.0: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410

> fsevents@1.2.13 install /Users/mac/Documents/justdoit/ruoyi-vue-pro/yudao-admin-ui/node_modules/fsevents
> node install.js

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
ld: warning: text-based stub file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation.tbd and library file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//CoreServices.framework/CoreServices.tbd and library file /System/Library/Frameworks//CoreServices.framework/CoreServices are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//CFNetwork.framework/Versions/A/CFNetwork.tbd and library file /System/Library/Frameworks//CFNetwork.framework/Versions/A/CFNetwork are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList are out of sync. Falling back to library file for linking.

> yorkie@2.0.0 install /Users/mac/Documents/justdoit/ruoyi-vue-pro/yudao-admin-ui/node_modules/yorkie
> node bin/install.js

setting up Git hooks
can't find .git directory, skipping Git hooks installation

> core-js@3.21.0 postinstall /Users/mac/Documents/justdoit/ruoyi-vue-pro/yudao-admin-ui/node_modules/@vue/babel-preset-app/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js:
> https://opencollective.com/core-js 
> https://patreon.com/zloirock 
> https://paypal.me/zloirock 
> bitcoin: bc1qlea7544qtsmj2rayg0lthvza9fau63ux0fstcz 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js@2.6.12 postinstall /Users/mac/Documents/justdoit/ruoyi-vue-pro/yudao-admin-ui/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> ejs@2.7.4 postinstall /Users/mac/Documents/justdoit/ruoyi-vue-pro/yudao-admin-ui/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)


> core-js@3.19.1 postinstall /Users/mac/Documents/justdoit/ruoyi-vue-pro/yudao-admin-ui/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> highlight.js@9.18.5 postinstall /Users/mac/Documents/justdoit/ruoyi-vue-pro/yudao-admin-ui/node_modules/highlight.js
> node deprecated.js

-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

  Verion 9 of Highlight.js has reached EOL.  It will no longer
  be supported or receive security updates in the future.
  Please upgrade to version 10 or encourage your indirect
  dependencies to do so.

  For more info:
  
  https://github.com/highlightjs/highlight.js/issues/2877
  https://github.com/highlightjs/highlight.js/blob/master/VERSION_10_UPGRADE.md
 
-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
npm WARN The package axios is included as both a dev and production dependency.
npm WARN The package element-ui is included as both a dev and production dependency.

added 1525 packages from 987 contributors in 165.379s

115 packages are looking for funding
  run `npm fund` for details

**Comment by YunaiV** [comment]
换完之后，有删除下 node modules 么？

**Comment by YunaiV** [comment]
优化了下，目前支持 node 16 版本，可以在尝试下~
