### ISSUE TITLE
流程模型发起时可否没有表单

### ISSUE THREAD

**Issue by softboy99** [YunaiV/ruoyi-vue-pro#691]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：2.3.0
- 操作系统：win11
- 数据库：mysql 8.4.2

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：业务表并不是每次创建了记录就马上走工作流审批，往往是单独发起工作流，按照BPMN规范，也并不是每个节点都一定需要表单，如果仅仅是走审核核批类的简单动作，实际上是不需要表单的

**Comment by YunaiV** [comment]
目前必须有表单。

你真需要的化，可以搞个不需要填写任何信息。
或者表单上，设置个非必填字段。

**Comment by softboy99** [comment]
这种设计不好
