### ISSUE TITLE
建议集成系统编码规则的功能，用于业务表中生成编码，可参考jeecg

### ISSUE THREAD

**Issue by softboy99** [YunaiV/ruoyi-vue-pro#697]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：
- 操作系统：win11
- 数据库：mysql 8.4.2

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：不通的业务表需要不通的的编号规则，和代码生成器集成，否则每个都需要手动写代码，改表单, 建议参考jeecg.
![image](https://github.com/user-attachments/assets/b9a7394c-e321-430e-a9f1-93f75678f78a)

![image](https://github.com/user-attachments/assets/de8d852b-8ba6-41e0-ba0e-a815d637b6cf)

**Comment by YunaiV** [comment]
好的。已经合并到我们的需求池。
