### ISSUE TITLE
代码生成器支持设置字段的默认值

### ISSUE THREAD

**Issue by softboy99** [YunaiV/ruoyi-vue-pro#698]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：2.3.0
- 操作系统：win11
- 数据库：mysql 48.4.2

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：代码生成器需支持设置字段的默认值，可以是字面值，也可以是前端可以自动处理的表达式

**Comment by YunaiV** [comment]
不错的建议。

不过这个不是特别主流的需求，暂时不考虑实现。

非常感谢建议哈。
