### ISSUE TITLE
搭建minio文件服务器上传失败问题

### ISSUE THREAD

**Issue by 905407220** [YunaiV/ruoyi-vue-pro#702]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：2.3
- 操作系统：windows10
- 数据库：mysql5.7

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：我在本地搭建是可以访问的，然后在服务器上利用docker搭建后就不行了。配置文件只修改了节点地址，其他都一样

### 复现步骤

第一步，
![image](https://github.com/user-attachments/assets/2564ca06-9eed-46d0-b09a-ead8f9fbbd04)

第二步，
![image](https://github.com/user-attachments/assets/aaedd850-1136-45c0-8b93-8407bbe2bcca)

第三步，
![image](https://github.com/user-attachments/assets/ba626ac8-55fb-4f0d-bab8-f324ac616b7d)

### 报错信息
![image](https://github.com/user-attachments/assets/b0daa0e8-233c-4806-9c55-0140e617829d)

带上必要的截图

**Comment by YunaiV** [comment]
nginx 转发的时候，需要把 bucket 拼接上去哈。
