### ISSUE TITLE
一个master17分支长期存在的问题,application-local redis配置不生效,一直是默认连接 127.0.0.1:6379无密码

### ISSUE THREAD

**Issue by JBlazingSun** [YunaiV/ruoyi-vue-pro#704]
### 基本信息

- ruoyi-vue-pro 版本：最新master17分支
- 操作系统：WIN11
- 数据库：mysql

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：

一个master17分支长期存在的问题,application-local redis配置不生效或者Redisson没读取成功 ,  一直是默认连接 127.0.0.1:6379无密码

### 报错信息

Caused by: java.util.concurrent.ExecutionException: org.redisson.client.RedisConnectionException: Unable to connect to Redis server: localhost/127.0.0.1:6379

星球链接  https://t.zsxq.com/ga8YY

**Comment by YunaiV** [comment]
密码配置，spring.data.redis.password =  即可。

取消 password 的注释时，需要注意下缩进
