### ISSUE TITLE
ERROR 17432 | http-nio-48080-exec-3 [TID: N/A] c.i.y.f.t.c.s.TenantSecurityWebFilter    | [doFilterInternal][URL(/admin-api/system/auth/social-login/POST) 未传递租户编号]

### ISSUE THREAD

**Issue by sanye8899** [YunaiV/ruoyi-vue-pro#705]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：
- 操作系统：win10
- 数据库：mysql8.0

### 你猜测可能的原因
ERROR 17432 | http-nio-48080-exec-3 [TID: N/A] c.i.y.f.t.c.s.TenantSecurityWebFilter    | [doFilterInternal][URL(/admin-api/system/auth/social-login/POST) 未传递租户编号]

**Comment by sanye8899** [comment]
我在自己的电脑上测试没有问题，但是在局域网用同事的电脑测试一直报这个错误。

**Comment by sanye8899** [comment]
我想应该是  async Cache 无法很好的透传 ThreadLocal

**Comment by YunaiV** [comment]
> 我想应该是 async Cache 无法很好的透传 ThreadLocal

对的。关键，我各种尝试过，有点无解哈。
