### ISSUE TITLE
积木报表设计器空白

### ISSUE THREAD

**Issue by shootleo** [YunaiV/ruoyi-vue-pro#706]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：master-jdk17 + vue3
- 操作系统：win10
- 数据库：mysql8

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：xxxxxx

### 复现步骤

第一步，
 按照文档中的步骤开启报表模块
第二步，
点击报表设计器
第三步，

### 报错信息
打开报表设计器是空白

带上必要的截图
![1732268179879](https://github.com/user-attachments/assets/bab637d8-b93f-4046-a250-e837a1439840)

**Comment by YunaiV** [comment]
测试了下，暂时没碰到。

前端有没什么报错信息？

**Comment by YunaiV** [comment]
由于暂时没有回复，该 issue 进行关闭。

后续有疑问，可以继续 issue 提问哈。

**Comment by softboy99** [comment]
条码需升级企业版
