### ISSUE TITLE
［功能需求］问卷调查表单模块

### ISSUE THREAD

**Issue by sfy2022** [YunaiV/ruoyi-vue-pro#708]
由于我是业余爱好者，工作中有很多场景需要用到问卷表单收集，如何把表单构建升级改造成问卷调查模块，希望大家给我一些思路，或者大佬开发独立问卷调查模块🙏🙏🙏

**Comment by YunaiV** [comment]
感谢建议，后续我们会做这方便哈。

做了后，我们会在更新日志同步噢。
