### ISSUE TITLE
能否先发布下uni-app的微信集成登录，前后端的功能呀

### ISSUE THREAD

**Issue by polly1216** [YunaiV/ruoyi-vue-pro#71]
能否先发布下uni-app的微信集成登录，前后端的功能呀

**Comment by YunaiV** [comment]
预计这个月会提供！

**Comment by polly1216** [comment]
能先把只把微信登录集成发个版本不，比较着急用呢

**Comment by polly1216** [comment]
或者麻烦告诉微信登录后台对应API是那个类呀  我自己先弄这个

**Comment by polly1216** [comment]
> 预计这个月会提供！

麻烦告诉微信登录后台对应API是那个类呀 我自己先弄这个

**Comment by YunaiV** [comment]
> 麻烦告诉微信登录后台对应API是那个类呀 我自己先弄这个

搜下 social 包
