### ISSUE TITLE
【bug】采用流式问答向AI模型提问题，返回的信息不完整

### ISSUE THREAD

**Issue by ShowLink** [YunaiV/ruoyi-vue-pro#716]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：JDK 17+ Spring Boot 3.2
- 操作系统：Windows
- 数据库：MySql 8.2

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：我怀疑是不是网络的问题。因为我查看了我的接口平台，发现实际上问题的答案是完整的，但是接收的流不完整。我换过多个服务商，openai、moonshot效果都是一样的。

### 复现步骤

第一步，在聊天窗口输入问题

第二步，等待模型返回

第三步，发现返回的内容不完整

### 报错信息

![image](https://github.com/user-attachments/assets/a3e440ba-9c5f-4d38-8199-a02766755c70)
![image](https://github.com/user-attachments/assets/e52d2d7d-5187-43d4-80a2-374e1a8ac0c5)

**Comment by YunaiV** [comment]
这个是 spring ai 的 bug。

已经修复，暂时没合并到 master 分支。

**Comment by ShowLink** [comment]
@YunaiV 
你好，具体应该怎么修复，能否提供思路？或者什么时候会发布修复版？
