### ISSUE TITLE
想问下，saas版下，租户的定制化解决方案

### ISSUE THREAD

**Issue by Dagen2369** [YunaiV/ruoyi-vue-pro#719]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：最新版
- 操作系统：cenots7
- 数据库：mysql8.0

### 你猜测可能的原因

目前没有没有问题，就是有的业务在个别租户下，会有差异需要定制化业务，对同一个方法只是实现的业务不同。有什么好的解决方案可以不用 if else 方式切换实现类吗？

### 复现步骤

第一步，

第二步，

第三步，

### 报错信息

带上必要的截图

**Comment by YunaiV** [comment]
这块，我们做一些外包项目的时候，是通过插件机制 or 拓展点机制实现的。

这块，后续看情况，看看怎么从外包项目，通用化抽出来到项目里，更好的帮助大家哈。

**Comment by Dagen2369** [comment]
你好，感谢你的回复，插件机制 or 拓展点机制 这块有可以参考的案例吗？
