### ISSUE TITLE
如何不登录直接访问

### ISSUE THREAD

**Issue by polly1216** [YunaiV/ruoyi-vue-pro#72]
如何实现不登录调用系统方法

**Comment by YunaiV** [comment]
是希望通过 postman 之类，模拟调用接口么？

**Comment by polly1216** [comment]
不是 就是不登录系统就可以调用平台方法，比如商城可以浏览商品，不用登录就可以查看的

**Comment by YunaiV** [comment]
> 不是 就是不登录系统就可以调用平台方法，比如商城可以浏览商品，不用登录就可以查看的

这种需求，一般是面向 c 端用户的接口吧？例如说用户 APP。这套接口，默认是不进行登录校验的。
也就是说，/admin-api 下，默认接口需要登录；/app-api 下，默认接口无需登录

**Comment by YunaiV** [comment]
<img width="1599" alt="image" src="https://user-images.githubusercontent.com/2015545/153093470-a4e8deb3-ffe7-4d48-b5a8-ea513b75e80e.png">
