### ISSUE TITLE
Caused by: java.io.FileNotFoundException: http://test.yudao.iocoder.cn/model.onnx

### ISSUE THREAD

**Issue by Bulua** [YunaiV/ruoyi-vue-pro#721]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：
- 操作系统：windows
- 数据库：mysql

### 你猜测可能的原因

http://test.yudao.iocoder.cn/model.onnx 链接失效了

### 复现步骤

![image](https://github.com/user-attachments/assets/70a07c71-7042-42b3-b799-1eb49f3a500f)

### 报错信息

![image](https://github.com/user-attachments/assets/c6739549-0b7e-42e8-af53-2a0cd81f942b)

**Comment by YunaiV** [comment]
https://gitee.com/zhijiantianya/ruoyi-vue-pro/blob/master/yudao-server/src/main/resources/application.yaml#L154
