### ISSUE TITLE
能否直接无缝从 RuoYi 原版系统迁移到这个 Pro 系统？

### ISSUE THREAD

**Issue by 1834423612** [YunaiV/ruoyi-vue-pro#726]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：暂无
- 操作系统：Windows11
- 数据库：MySQL 8.0

### 问题

能否直接无缝从 RuoYi 原版系统迁移到这个 Pro 系统？谢谢

**Comment by YunaiV** [comment]
会有一些不兼容，可以迁移过程中有问题，找我们咨询哈。
