### ISSUE TITLE
流程回退若回退到的节点为多实例，则回退异常

### ISSUE THREAD

**Issue by wugenshui** [YunaiV/ruoyi-vue-pro#727]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：v2.3.0
- 操作系统：windows
- 数据库：mysql

### 你猜测可能的原因

我花费了很长时间自查，未发现原因

### 复现步骤

第一步，新建流程,包含A（多实例任务）、B、C三个任务
模型xml配置
[diagram.XML.json](https://github.com/user-attachments/files/18257278/diagram.XML.json)

第二步，流程正常流转从A任务到B任务

第三步，点击回退到多实例任务A，这时B任务显示已回退，但是没有创建新的A任务，流程详情界面也是显示截止到已退回的B任务。

预期：这时任务B应该能够正常回退到A任务

### 报错信息

带上必要的截图
![image](https://github.com/user-attachments/assets/12a269f4-4f0f-492a-aa55-9e2af1261677)
![image](https://github.com/user-attachments/assets/a4a78aeb-b012-4e76-a377-e2ebc12e818d)

**Comment by YunaiV** [comment]
拉下最新的分支，这个缺陷已经修复了哈。

**Comment by wugenshui** [comment]
今天才看到，感谢，解决了我的问题 👍
