### ISSUE TITLE
积木报表收费了，有什么好的开源产品替代？

### ISSUE THREAD

**Issue by softboy99** [YunaiV/ruoyi-vue-pro#728]
碰到问题，请在 <https://github.com/YunaiV/ruoyi-vue-pro/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：2.3.0
- 操作系统：win11
- 数据库：mysql8

### 你猜测可能的原因

（必填）积木报表收费了，很多功能有限制，有什么好的开源产品替代？

**Comment by YunaiV** [comment]
我们下个版本，调研下这块哈。感谢建议。

**Comment by softboy99** [comment]
@YunaiV 这个有答案了吗？
