### ISSUE TITLE
拉取最新的代码无法运行

### ISSUE THREAD

**Issue by samho2008** [YunaiV/ruoyi-vue-pro#75]
最新的代码
![image](https://user-images.githubusercontent.com/92196261/153520319-2f3760ff-0797-439e-a710-5e06a0b80799.png)

运行应用后出现以下报错
![image](https://user-images.githubusercontent.com/92196261/153520388-4c748f54-ed05-456a-9d3e-a9c587f25795.png)

点进去发现包是存在的，错误原因不详
![image](https://user-images.githubusercontent.com/92196261/153520502-c730bf46-7508-4026-934c-0e80f65c0ee4.png)

**Comment by samho2008** [comment]
![image](https://user-images.githubusercontent.com/92196261/153521162-684fa6a7-001c-4798-9cd7-8ba83436f05a.png)

**Comment by YunaiV** [comment]
试试删除这个运行项，然后直接去 YudaoServerApplication 运行下看看？

**Comment by lzx13080010188** [comment]
我也没运行下来，感觉你的包管理有问题，maven总会导致包下不全

**Comment by AhahaGe** [comment]
我也跑不起来

**Comment by samho2008** [comment]
> mvn clean package -Dmaven.test.skip=true，可以先跑起来

可以了，感谢回复。

**Comment by samho2008** [comment]
解决方案：先在项目根目录下`ruoyi-vue-pro`下执行`mvn clean package -Dmaven.test.skip=true`，

**Comment by samho2008** [comment]
> 我也没运行下来，感觉你的包管理有问题，maven总会导致包下不全

我后端项目跑起来了，可以参考这个解决。
解决方案：
1. 先在项目根目录下`ruoyi-vue-pro`下执行`mvn clean package -Dmaven.test.skip=true`
2. 如果提示命令行过长
![image](https://user-images.githubusercontent.com/92196261/153642424-6eb1b5de-c784-47a0-9973-7eace2b75e30.png)
可以参考[博客](https://blog.csdn.net/weixin_43689480/article/details/100983585)解决

**Comment by samho2008** [comment]
> mvn clean package -Dmaven.test.skip=true，可以先跑起来

你前端项目`npm install`可以跑起来吗，我提示依赖有问题

**Comment by YunaiV** [comment]
已经完善搭建的文章，感谢各位！

**Comment by AhahaGe** [comment]
> > mvn clean package -Dmaven.test.skip=true，可以先跑起来
> 
> 你前端项目`npm install`可以跑起来吗，我提示依赖有问题

前端环境没弄
