### ISSUE TITLE
怎么关闭不需要的模块

### ISSUE THREAD

**Issue by bensq2** [YunaiV/ruoyi-vue-pro#77]
如果不想用某些模块，例如工作流，支付，请问怎么在springboot 启动时不加载

**Comment by YunaiV** [comment]
> 如果不想用某些模块，例如工作流，支付，请问怎么在springboot 启动时不加载

在 yudao-server 注释掉对应模块的引用即可。

**Comment by bensq2** [comment]
怎么关闭子模块呢，像framework下的monitor

**Comment by YunaiV** [comment]
一样哈，不要引入这个依赖
