### ISSUE TITLE
我想将MySQL数据库转为Oracle数据库有什么注意事项吗？

### ISSUE THREAD

**Issue by hdshsq** [YunaiV/ruoyi-vue-pro#78]
大佬有没有什么快捷方式呢？

**Comment by YunaiV** [comment]
可以尝试用 navicat 转，应该没啥问题

**Comment by hdshsq** [comment]
用navicat转，会在表名和字段名当中生成`（反单引号）例如  `tableName`.`col`,更改脚本即可

**Comment by sdlushao** [comment]
试了好几种方式，转换一直失败

**Comment by YunaiV** [comment]
https://gitee.com/zhijiantianya/ruoyi-vue-pro/tree/feature/db/sql/tools
