### ISSUE TITLE
修复几处小错误

### ISSUE THREAD

**Issue by crimson-gao** [YunaiV/ruoyi-vue-pro#85]
1. ui-admin 下的 components/breadCrumb 内有一处，第 44 行 `isDashboard` 判断是否开头是首页，如果不是则添加首页按钮到最前面 。
我打印了对象，发现首页本身的 name 是 `首页` 不是 `Index`。 这里如果不修改会错误添加，出现 `首页/首页` ，报重复 path 错误
```
isDashboard(route) {
      const name = route && route.name
      if (!name) {
        return false
      }
      return name.trim() === 'Index' // to fix: 应该改成 '首页' 
    },
```
2. system模块下，`convert/auth/AuthConvert ` 有一处转换， 只返回了 nickname ，没有返回 username
```
    default AuthPermissionInfoRespVO convert(AdminUserDO user, List<RoleDO> roleList, List<MenuDO> menuList) {
        return AuthPermissionInfoRespVO.builder()
            .user(AuthPermissionInfoRespVO.UserVO.builder().id(user.getId()).nickname(user.getNickname()).avatar(user.getAvatar()).build())
            .roles(CollectionUtils.convertSet(roleList, RoleDO::getCode))
            .permissions(CollectionUtils.convertSet(menuList, MenuDO::getPermission))
            .build();
    }
```
而后前端 vue 在 `store/modules/user.js` 内 的 `GetInfo` 函数内有一处使用到了 username， 这里会读 undefined
```
commit('SET_NAME', user.username)
```
建议convert 时将 username 一并填充了，最好把 deptId 等等也一起填充了

**Comment by crimson-gao** [comment]
这里 username 我感觉不应该从 getInfo -> get-permission-info 接口去取，后面的 getUserProfile -> userProfile中已经返回了 username、avatar、nickname 等信息， 应当在前端 store 的 user 模块内，在 getUserProfile 的回调中去 commit，这样也就不用在 get-permission-info 的后端接口中返回 username nickname 了

**Comment by YunaiV** [comment]
1. 根据你的建议，已经修复。
2. 我得在考虑下， username 后续可能不考虑返回
