### ISSUE TITLE
头像上传bug

### ISSUE THREAD

**Issue by crimson-gao** [YunaiV/ruoyi-vue-pro#86]
还是上次的bug没有完全解决，上传头像文件时，我看了下数据库，会将租户id 1 写入文件记录中。
然后因为图像使用 src=url 获取，无法使用租户 id，上次修复时把文件获取的接口改成了 ignoreTenant。
这导致了文件获取时使用的 select 语句中 where 带上了 tenant_id = 0 ，导致找不到图像。

这里应当将文件接口设置为非租户的，或者查询时去掉 where tenant_id = 0 或者 写入时租户 id 设置为 0

**Comment by YunaiV** [comment]
已经解决，在多租户的优化分支里

**Comment by YunaiV** [comment]
已经合并到 master 分支。
