### ISSUE TITLE
最新版本运行出现Unknown column 'tenant_id' in 'field list'

### ISSUE THREAD

**Issue by YLbaby** [YunaiV/ruoyi-vue-pro#96]
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/63778983/155990281-d9d255a8-bf8a-43c6-a6f1-1b81e72cca9f.png">
大家有出现这个问题吗？

**Comment by YunaiV** [comment]
重新导入 sql 了么？

**Comment by YLbaby** [comment]
谢谢您的回复，我把数据库清空又重新导了一遍，发现还是出现这样的情况。

**Comment by YunaiV** [comment]
自己在检查下哈，我又重新测试了一次，木有问题。
