### ISSUE TITLE
项目打包异常

### ISSUE THREAD

**Issue by ouminling** [YunaiV/ruoyi-vue-pro#99]
在控制台执行 mvn clean package -Dmaven.test.skip=true 命令，将项目进行初始化的打包，
报错：Unknown lifecycle phase ".test.skip=true". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<p
lugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, genera
te-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integr
ation-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]

**Comment by YunaiV** [comment]
拉取最新，在试试看。

**Comment by lanemy** [comment]
方法一
命令改为：mvn clean package install '-Dmaven.test.skip=true'
方法二
不要使用PowerShell命令行模式，使用 cmd 进入命令行执行：mvn clean package install -Dmaven.test.skip=true

**Comment by YunaiV** [comment]
赞
